// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DanubeData.DanubeData
{
    /// <summary>
    /// ## # danubedata.Cache
    /// 
    /// Manages an in-memory cache instance (Redis, Valkey, or Dragonfly).
    /// 
    /// ## Example Usage
    /// 
    /// ### Redis Cache
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using DanubeData = DanubeData.DanubeData;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var redis = new DanubeData.Cache("redis", new()
    ///     {
    ///         CacheProvider = "redis",
    ///         MemorySizeMb = 512,
    ///         CpuCores = 1,
    ///         Datacenter = "fsn1",
    ///         Version = "7.2",
    ///     });
    /// 
    ///     return new Dictionary&lt;string, object?&gt;
    ///     {
    ///         ["redisEndpoint"] = redis.Endpoint,
    ///     };
    /// });
    /// ```
    /// 
    /// ### Valkey Cache (Redis Fork)
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using DanubeData = DanubeData.DanubeData;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var valkey = new DanubeData.Cache("valkey", new()
    ///     {
    ///         CacheProvider = "valkey",
    ///         CpuCores = 2,
    ///         Datacenter = "fsn1",
    ///         MemorySizeMb = 1024,
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ### Dragonfly Cache (High Performance)
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using DanubeData = DanubeData.DanubeData;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var dragonfly = new DanubeData.Cache("dragonfly", new()
    ///     {
    ///         CacheProvider = "dragonfly",
    ///         CpuCores = 4,
    ///         Datacenter = "fsn1",
    ///         MemorySizeMb = 2048,
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ### Using Resource Profile
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using DanubeData = DanubeData.DanubeData;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var standard = new DanubeData.Cache("standard", new()
    ///     {
    ///         ResourceProfile = "cache-medium",
    ///         Datacenter = "fsn1",
    ///     }, new CustomResourceOptions
    ///     {
    ///         Provider = "redis",
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// Cache instances can be imported using their ID:
    /// 
    /// bash
    /// 
    /// ```sh
    /// $ pulumi import danubedata:index/cache:Cache example cache-abc123
    /// ```
    /// </summary>
    [DanubeDataResourceType("danubedata:index/cache:Cache")]
    public partial class Cache : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Cache provider type (redis, valkey, dragonfly).
        /// </summary>
        [Output("cacheProvider")]
        public Output<string> CacheProvider { get; private set; } = null!;

        /// <summary>
        /// Number of CPU cores. If not specified, determined by resource_profile.
        /// </summary>
        [Output("cpuCores")]
        public Output<int> CpuCores { get; private set; } = null!;

        /// <summary>
        /// Creation timestamp.
        /// </summary>
        [Output("createdAt")]
        public Output<string> CreatedAt { get; private set; } = null!;

        /// <summary>
        /// Datacenter location (ash, fsn1, nbg1, hel1).
        /// </summary>
        [Output("datacenter")]
        public Output<string> Datacenter { get; private set; } = null!;

        /// <summary>
        /// Deployment timestamp.
        /// </summary>
        [Output("deployedAt")]
        public Output<string> DeployedAt { get; private set; } = null!;

        /// <summary>
        /// Connection endpoint hostname.
        /// </summary>
        [Output("endpoint")]
        public Output<string> Endpoint { get; private set; } = null!;

        /// <summary>
        /// Memory size in MB. If not specified, determined by resource_profile.
        /// </summary>
        [Output("memorySizeMb")]
        public Output<int> MemorySizeMb { get; private set; } = null!;

        /// <summary>
        /// Estimated monthly cost.
        /// </summary>
        [Output("monthlyCost")]
        public Output<double> MonthlyCost { get; private set; } = null!;

        /// <summary>
        /// Monthly cost in cents.
        /// </summary>
        [Output("monthlyCostCents")]
        public Output<int> MonthlyCostCents { get; private set; } = null!;

        /// <summary>
        /// Name of the cache instance.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// ID of the parameter group to use for custom configuration.
        /// </summary>
        [Output("parameterGroupId")]
        public Output<string?> ParameterGroupId { get; private set; } = null!;

        /// <summary>
        /// Connection port.
        /// </summary>
        [Output("port")]
        public Output<int> Port { get; private set; } = null!;

        /// <summary>
        /// Resource profile for the cache (micro, small, medium, large).
        /// </summary>
        [Output("resourceProfile")]
        public Output<string> ResourceProfile { get; private set; } = null!;

        /// <summary>
        /// Current status.
        /// </summary>
        [Output("status")]
        public Output<string> Status { get; private set; } = null!;

        [Output("timeouts")]
        public Output<Outputs.CacheTimeouts?> Timeouts { get; private set; } = null!;

        /// <summary>
        /// Timestamp when the cache instance was last updated.
        /// </summary>
        [Output("updatedAt")]
        public Output<string> UpdatedAt { get; private set; } = null!;

        /// <summary>
        /// Version of the cache software.
        /// </summary>
        [Output("version")]
        public Output<string> Version { get; private set; } = null!;


        /// <summary>
        /// Create a Cache resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Cache(string name, CacheArgs args, CustomResourceOptions? options = null)
            : base("danubedata:index/cache:Cache", name, args ?? new CacheArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Cache(string name, Input<string> id, CacheState? state = null, CustomResourceOptions? options = null)
            : base("danubedata:index/cache:Cache", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/AdrianSilaghi/pulumi-danubedata",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Cache resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Cache Get(string name, Input<string> id, CacheState? state = null, CustomResourceOptions? options = null)
        {
            return new Cache(name, id, state, options);
        }
    }

    public sealed class CacheArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Cache provider type (redis, valkey, dragonfly).
        /// </summary>
        [Input("cacheProvider", required: true)]
        public Input<string> CacheProvider { get; set; } = null!;

        /// <summary>
        /// Number of CPU cores. If not specified, determined by resource_profile.
        /// </summary>
        [Input("cpuCores")]
        public Input<int>? CpuCores { get; set; }

        /// <summary>
        /// Datacenter location (ash, fsn1, nbg1, hel1).
        /// </summary>
        [Input("datacenter", required: true)]
        public Input<string> Datacenter { get; set; } = null!;

        /// <summary>
        /// Memory size in MB. If not specified, determined by resource_profile.
        /// </summary>
        [Input("memorySizeMb")]
        public Input<int>? MemorySizeMb { get; set; }

        /// <summary>
        /// Name of the cache instance.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// ID of the parameter group to use for custom configuration.
        /// </summary>
        [Input("parameterGroupId")]
        public Input<string>? ParameterGroupId { get; set; }

        /// <summary>
        /// Resource profile for the cache (micro, small, medium, large).
        /// </summary>
        [Input("resourceProfile", required: true)]
        public Input<string> ResourceProfile { get; set; } = null!;

        [Input("timeouts")]
        public Input<Inputs.CacheTimeoutsArgs>? Timeouts { get; set; }

        /// <summary>
        /// Version of the cache software.
        /// </summary>
        [Input("version")]
        public Input<string>? Version { get; set; }

        public CacheArgs()
        {
        }
        public static new CacheArgs Empty => new CacheArgs();
    }

    public sealed class CacheState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Cache provider type (redis, valkey, dragonfly).
        /// </summary>
        [Input("cacheProvider")]
        public Input<string>? CacheProvider { get; set; }

        /// <summary>
        /// Number of CPU cores. If not specified, determined by resource_profile.
        /// </summary>
        [Input("cpuCores")]
        public Input<int>? CpuCores { get; set; }

        /// <summary>
        /// Creation timestamp.
        /// </summary>
        [Input("createdAt")]
        public Input<string>? CreatedAt { get; set; }

        /// <summary>
        /// Datacenter location (ash, fsn1, nbg1, hel1).
        /// </summary>
        [Input("datacenter")]
        public Input<string>? Datacenter { get; set; }

        /// <summary>
        /// Deployment timestamp.
        /// </summary>
        [Input("deployedAt")]
        public Input<string>? DeployedAt { get; set; }

        /// <summary>
        /// Connection endpoint hostname.
        /// </summary>
        [Input("endpoint")]
        public Input<string>? Endpoint { get; set; }

        /// <summary>
        /// Memory size in MB. If not specified, determined by resource_profile.
        /// </summary>
        [Input("memorySizeMb")]
        public Input<int>? MemorySizeMb { get; set; }

        /// <summary>
        /// Estimated monthly cost.
        /// </summary>
        [Input("monthlyCost")]
        public Input<double>? MonthlyCost { get; set; }

        /// <summary>
        /// Monthly cost in cents.
        /// </summary>
        [Input("monthlyCostCents")]
        public Input<int>? MonthlyCostCents { get; set; }

        /// <summary>
        /// Name of the cache instance.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// ID of the parameter group to use for custom configuration.
        /// </summary>
        [Input("parameterGroupId")]
        public Input<string>? ParameterGroupId { get; set; }

        /// <summary>
        /// Connection port.
        /// </summary>
        [Input("port")]
        public Input<int>? Port { get; set; }

        /// <summary>
        /// Resource profile for the cache (micro, small, medium, large).
        /// </summary>
        [Input("resourceProfile")]
        public Input<string>? ResourceProfile { get; set; }

        /// <summary>
        /// Current status.
        /// </summary>
        [Input("status")]
        public Input<string>? Status { get; set; }

        [Input("timeouts")]
        public Input<Inputs.CacheTimeoutsGetArgs>? Timeouts { get; set; }

        /// <summary>
        /// Timestamp when the cache instance was last updated.
        /// </summary>
        [Input("updatedAt")]
        public Input<string>? UpdatedAt { get; set; }

        /// <summary>
        /// Version of the cache software.
        /// </summary>
        [Input("version")]
        public Input<string>? Version { get; set; }

        public CacheState()
        {
        }
        public static new CacheState Empty => new CacheState();
    }
}
