// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DanubeData.DanubeData
{
    /// <summary>
    /// ## # danubedata.Database
    /// 
    /// Manages a managed database instance (MySQL, PostgreSQL, or MariaDB).
    /// 
    /// ## Example Usage
    /// 
    /// ### Using Resource Profile
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using DanubeData = DanubeData.DanubeData;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var standard = new DanubeData.Database("standard", new()
    ///     {
    ///         Datacenter = "fsn1",
    ///         Engine = "mysql",
    ///         ResourceProfile = "db-medium",
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Notes
    /// 
    /// - Database credentials are managed separately and can be retrieved via the API.
    /// - Storage size can only be increased, not decreased.
    /// - Version upgrades may cause brief downtime.
    /// 
    /// ## Import
    /// 
    /// Database instances can be imported using their ID:
    /// 
    /// bash
    /// 
    /// ```sh
    /// $ pulumi import danubedata:index/database:Database example db-abc123
    /// ```
    /// </summary>
    [DanubeDataResourceType("danubedata:index/database:Database")]
    public partial class Database : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Number of CPU cores. Derived from resource_profile.
        /// </summary>
        [Output("cpuCores")]
        public Output<int> CpuCores { get; private set; } = null!;

        /// <summary>
        /// Creation timestamp.
        /// </summary>
        [Output("createdAt")]
        public Output<string> CreatedAt { get; private set; } = null!;

        /// <summary>
        /// Name of the initial database to create. Must start with a letter and contain only letters, numbers, and underscores.
        /// </summary>
        [Output("databaseName")]
        public Output<string?> DatabaseName { get; private set; } = null!;

        /// <summary>
        /// Datacenter location (fsn1, nbg1, hel1).
        /// </summary>
        [Output("datacenter")]
        public Output<string> Datacenter { get; private set; } = null!;

        /// <summary>
        /// Deployment timestamp.
        /// </summary>
        [Output("deployedAt")]
        public Output<string> DeployedAt { get; private set; } = null!;

        /// <summary>
        /// Connection endpoint hostname.
        /// </summary>
        [Output("endpoint")]
        public Output<string> Endpoint { get; private set; } = null!;

        /// <summary>
        /// Database engine (mysql, postgresql, mariadb).
        /// </summary>
        [Output("engine")]
        public Output<string> Engine { get; private set; } = null!;

        /// <summary>
        /// Memory size in MB. Derived from resource_profile.
        /// </summary>
        [Output("memorySizeMb")]
        public Output<int> MemorySizeMb { get; private set; } = null!;

        /// <summary>
        /// Estimated monthly cost.
        /// </summary>
        [Output("monthlyCost")]
        public Output<double> MonthlyCost { get; private set; } = null!;

        /// <summary>
        /// Monthly cost in cents.
        /// </summary>
        [Output("monthlyCostCents")]
        public Output<int> MonthlyCostCents { get; private set; } = null!;

        /// <summary>
        /// Name of the database instance. Must be lowercase alphanumeric with hyphens (DNS compatible).
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// ID of the parameter group to use for custom configuration.
        /// </summary>
        [Output("parameterGroupId")]
        public Output<string?> ParameterGroupId { get; private set; } = null!;

        /// <summary>
        /// Connection port.
        /// </summary>
        [Output("port")]
        public Output<int> Port { get; private set; } = null!;

        /// <summary>
        /// Resource profile for the database (small, medium, large).
        /// </summary>
        [Output("resourceProfile")]
        public Output<string> ResourceProfile { get; private set; } = null!;

        /// <summary>
        /// Current status.
        /// </summary>
        [Output("status")]
        public Output<string> Status { get; private set; } = null!;

        /// <summary>
        /// Storage size in GB. Derived from resource_profile.
        /// </summary>
        [Output("storageSizeGb")]
        public Output<int> StorageSizeGb { get; private set; } = null!;

        [Output("timeouts")]
        public Output<Outputs.DatabaseTimeouts?> Timeouts { get; private set; } = null!;

        /// <summary>
        /// Timestamp when the database instance was last updated.
        /// </summary>
        [Output("updatedAt")]
        public Output<string> UpdatedAt { get; private set; } = null!;

        /// <summary>
        /// Database admin username.
        /// </summary>
        [Output("username")]
        public Output<string> Username { get; private set; } = null!;

        /// <summary>
        /// Version of the database software.
        /// </summary>
        [Output("version")]
        public Output<string> Version { get; private set; } = null!;


        /// <summary>
        /// Create a Database resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Database(string name, DatabaseArgs args, CustomResourceOptions? options = null)
            : base("danubedata:index/database:Database", name, args ?? new DatabaseArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Database(string name, Input<string> id, DatabaseState? state = null, CustomResourceOptions? options = null)
            : base("danubedata:index/database:Database", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/AdrianSilaghi/pulumi-danubedata",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Database resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Database Get(string name, Input<string> id, DatabaseState? state = null, CustomResourceOptions? options = null)
        {
            return new Database(name, id, state, options);
        }
    }

    public sealed class DatabaseArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Name of the initial database to create. Must start with a letter and contain only letters, numbers, and underscores.
        /// </summary>
        [Input("databaseName")]
        public Input<string>? DatabaseName { get; set; }

        /// <summary>
        /// Datacenter location (fsn1, nbg1, hel1).
        /// </summary>
        [Input("datacenter", required: true)]
        public Input<string> Datacenter { get; set; } = null!;

        /// <summary>
        /// Database engine (mysql, postgresql, mariadb).
        /// </summary>
        [Input("engine", required: true)]
        public Input<string> Engine { get; set; } = null!;

        /// <summary>
        /// Name of the database instance. Must be lowercase alphanumeric with hyphens (DNS compatible).
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// ID of the parameter group to use for custom configuration.
        /// </summary>
        [Input("parameterGroupId")]
        public Input<string>? ParameterGroupId { get; set; }

        /// <summary>
        /// Resource profile for the database (small, medium, large).
        /// </summary>
        [Input("resourceProfile", required: true)]
        public Input<string> ResourceProfile { get; set; } = null!;

        [Input("timeouts")]
        public Input<Inputs.DatabaseTimeoutsArgs>? Timeouts { get; set; }

        /// <summary>
        /// Version of the database software.
        /// </summary>
        [Input("version")]
        public Input<string>? Version { get; set; }

        public DatabaseArgs()
        {
        }
        public static new DatabaseArgs Empty => new DatabaseArgs();
    }

    public sealed class DatabaseState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Number of CPU cores. Derived from resource_profile.
        /// </summary>
        [Input("cpuCores")]
        public Input<int>? CpuCores { get; set; }

        /// <summary>
        /// Creation timestamp.
        /// </summary>
        [Input("createdAt")]
        public Input<string>? CreatedAt { get; set; }

        /// <summary>
        /// Name of the initial database to create. Must start with a letter and contain only letters, numbers, and underscores.
        /// </summary>
        [Input("databaseName")]
        public Input<string>? DatabaseName { get; set; }

        /// <summary>
        /// Datacenter location (fsn1, nbg1, hel1).
        /// </summary>
        [Input("datacenter")]
        public Input<string>? Datacenter { get; set; }

        /// <summary>
        /// Deployment timestamp.
        /// </summary>
        [Input("deployedAt")]
        public Input<string>? DeployedAt { get; set; }

        /// <summary>
        /// Connection endpoint hostname.
        /// </summary>
        [Input("endpoint")]
        public Input<string>? Endpoint { get; set; }

        /// <summary>
        /// Database engine (mysql, postgresql, mariadb).
        /// </summary>
        [Input("engine")]
        public Input<string>? Engine { get; set; }

        /// <summary>
        /// Memory size in MB. Derived from resource_profile.
        /// </summary>
        [Input("memorySizeMb")]
        public Input<int>? MemorySizeMb { get; set; }

        /// <summary>
        /// Estimated monthly cost.
        /// </summary>
        [Input("monthlyCost")]
        public Input<double>? MonthlyCost { get; set; }

        /// <summary>
        /// Monthly cost in cents.
        /// </summary>
        [Input("monthlyCostCents")]
        public Input<int>? MonthlyCostCents { get; set; }

        /// <summary>
        /// Name of the database instance. Must be lowercase alphanumeric with hyphens (DNS compatible).
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// ID of the parameter group to use for custom configuration.
        /// </summary>
        [Input("parameterGroupId")]
        public Input<string>? ParameterGroupId { get; set; }

        /// <summary>
        /// Connection port.
        /// </summary>
        [Input("port")]
        public Input<int>? Port { get; set; }

        /// <summary>
        /// Resource profile for the database (small, medium, large).
        /// </summary>
        [Input("resourceProfile")]
        public Input<string>? ResourceProfile { get; set; }

        /// <summary>
        /// Current status.
        /// </summary>
        [Input("status")]
        public Input<string>? Status { get; set; }

        /// <summary>
        /// Storage size in GB. Derived from resource_profile.
        /// </summary>
        [Input("storageSizeGb")]
        public Input<int>? StorageSizeGb { get; set; }

        [Input("timeouts")]
        public Input<Inputs.DatabaseTimeoutsGetArgs>? Timeouts { get; set; }

        /// <summary>
        /// Timestamp when the database instance was last updated.
        /// </summary>
        [Input("updatedAt")]
        public Input<string>? UpdatedAt { get; set; }

        /// <summary>
        /// Database admin username.
        /// </summary>
        [Input("username")]
        public Input<string>? Username { get; set; }

        /// <summary>
        /// Version of the database software.
        /// </summary>
        [Input("version")]
        public Input<string>? Version { get; set; }

        public DatabaseState()
        {
        }
        public static new DatabaseState Empty => new DatabaseState();
    }
}
