// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DanubeData.DanubeData
{
    public static class GetCaches
    {
        /// <summary>
        /// ## # danubedata.getCaches
        /// 
        /// Lists all cache instances in your account.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using DanubeData = Pulumi.DanubeData;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var all = DanubeData.GetCaches.Invoke();
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["cacheCount"] = all.Apply(getCachesResult =&gt; getCachesResult.Instances).Length,
        ///         ["cacheEndpoints"] = .ToDictionary(item =&gt; {
        ///             var cache = item.Value;
        ///             return cache.Name;
        ///         }, item =&gt; {
        ///             var cache = item.Value;
        ///             return $"{cache.Endpoint}:{cache.Port}";
        ///         }),
        ///     };
        /// });
        /// ```
        /// 
        /// ### Find Cache by Name
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using DanubeData = Pulumi.DanubeData;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var all = DanubeData.GetCaches.Invoke();
        /// 
        ///     var mainCache = .Where(c =&gt; c.Name == "main-cache").Select(c =&gt; 
        ///     {
        ///         return c;
        ///     }).ToList()[0];
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["redisUrl"] = $"redis://{mainCache.Endpoint}:{mainCache.Port}",
        ///     };
        /// });
        /// ```
        /// 
        /// ### Filter by Provider
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using DanubeData = Pulumi.DanubeData;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var all = DanubeData.GetCaches.Invoke();
        /// 
        ///     var redisCaches = .Where(c =&gt; c.CacheProvider == "Redis").Select(c =&gt; 
        ///     {
        ///         return c;
        ///     }).ToList();
        /// 
        ///     var dragonflyCaches = .Where(c =&gt; c.CacheProvider == "Dragonfly").Select(c =&gt; 
        ///     {
        ///         return c;
        ///     }).ToList();
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["redisCount"] = redisCaches.Length,
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Task<GetCachesResult> InvokeAsync(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetCachesResult>("danubedata:index/getCaches:getCaches", InvokeArgs.Empty, options.WithDefaults());

        /// <summary>
        /// ## # danubedata.getCaches
        /// 
        /// Lists all cache instances in your account.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using DanubeData = Pulumi.DanubeData;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var all = DanubeData.GetCaches.Invoke();
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["cacheCount"] = all.Apply(getCachesResult =&gt; getCachesResult.Instances).Length,
        ///         ["cacheEndpoints"] = .ToDictionary(item =&gt; {
        ///             var cache = item.Value;
        ///             return cache.Name;
        ///         }, item =&gt; {
        ///             var cache = item.Value;
        ///             return $"{cache.Endpoint}:{cache.Port}";
        ///         }),
        ///     };
        /// });
        /// ```
        /// 
        /// ### Find Cache by Name
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using DanubeData = Pulumi.DanubeData;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var all = DanubeData.GetCaches.Invoke();
        /// 
        ///     var mainCache = .Where(c =&gt; c.Name == "main-cache").Select(c =&gt; 
        ///     {
        ///         return c;
        ///     }).ToList()[0];
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["redisUrl"] = $"redis://{mainCache.Endpoint}:{mainCache.Port}",
        ///     };
        /// });
        /// ```
        /// 
        /// ### Filter by Provider
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using DanubeData = Pulumi.DanubeData;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var all = DanubeData.GetCaches.Invoke();
        /// 
        ///     var redisCaches = .Where(c =&gt; c.CacheProvider == "Redis").Select(c =&gt; 
        ///     {
        ///         return c;
        ///     }).ToList();
        /// 
        ///     var dragonflyCaches = .Where(c =&gt; c.CacheProvider == "Dragonfly").Select(c =&gt; 
        ///     {
        ///         return c;
        ///     }).ToList();
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["redisCount"] = redisCaches.Length,
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Output<GetCachesResult> Invoke(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetCachesResult>("danubedata:index/getCaches:getCaches", InvokeArgs.Empty, options.WithDefaults());
    }


    [OutputType]
    public sealed class GetCachesResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// List of cache instances. Each instance contains:
        /// </summary>
        public readonly ImmutableArray<Outputs.GetCachesInstanceResult> Instances;

        [OutputConstructor]
        private GetCachesResult(
            string id,

            ImmutableArray<Outputs.GetCachesInstanceResult> instances)
        {
            Id = id;
            Instances = instances;
        }
    }
}
