// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DanubeData.DanubeData
{
    public static class GetCacheProviders
    {
        /// <summary>
        /// ## # danubedata.getCacheProviders
        /// 
        /// Lists available cache providers (Redis, Valkey, Dragonfly).
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using DanubeData = Pulumi.DanubeData;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var all = DanubeData.GetCacheProviders.Invoke();
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["cacheProviders"] = .Select(p =&gt; 
        ///         {
        ///             return 
        ///             {
        ///                 { "id", p.Id },
        ///                 { "name", p.Name },
        ///             };
        ///         }).ToList(),
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Task<GetCacheProvidersResult> InvokeAsync(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetCacheProvidersResult>("danubedata:index/getCacheProviders:getCacheProviders", InvokeArgs.Empty, options.WithDefaults());

        /// <summary>
        /// ## # danubedata.getCacheProviders
        /// 
        /// Lists available cache providers (Redis, Valkey, Dragonfly).
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using DanubeData = Pulumi.DanubeData;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var all = DanubeData.GetCacheProviders.Invoke();
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["cacheProviders"] = .Select(p =&gt; 
        ///         {
        ///             return 
        ///             {
        ///                 { "id", p.Id },
        ///                 { "name", p.Name },
        ///             };
        ///         }).ToList(),
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Output<GetCacheProvidersResult> Invoke(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetCacheProvidersResult>("danubedata:index/getCacheProviders:getCacheProviders", InvokeArgs.Empty, options.WithDefaults());
    }


    [OutputType]
    public sealed class GetCacheProvidersResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// List of cache providers. Each provider contains:
        /// </summary>
        public readonly ImmutableArray<Outputs.GetCacheProvidersProviderResult> Providers;

        [OutputConstructor]
        private GetCacheProvidersResult(
            string id,

            ImmutableArray<Outputs.GetCacheProvidersProviderResult> providers)
        {
            Id = id;
            Providers = providers;
        }
    }
}
