// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DanubeData.DanubeData
{
    public static class GetSshKeys
    {
        /// <summary>
        /// ## # danubedata.getSshKeys
        /// 
        /// Lists all SSH keys in your account.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using DanubeData = Pulumi.DanubeData;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var all = DanubeData.GetSshKeys.Invoke();
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["sshKeyIds"] = .Select(key =&gt; 
        ///         {
        ///             return key.Id;
        ///         }).ToList(),
        ///         ["sshKeyNames"] = .Select(key =&gt; 
        ///         {
        ///             return key.Name;
        ///         }).ToList(),
        ///     };
        /// });
        /// ```
        /// 
        /// ### Find Key by Name
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using DanubeData = DanubeData.DanubeData;
        /// using DanubeData = Pulumi.DanubeData;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var all = DanubeData.GetSshKeys.Invoke();
        /// 
        ///     var deployKey = .Where(key =&gt; key.Name == "deploy-key").Select(key =&gt; 
        ///     {
        ///         return key;
        ///     }).ToList()[0];
        /// 
        ///     var server = new DanubeData.Vps("server", new()
        ///     {
        ///         Image = "ubuntu-22.04",
        ///         Datacenter = "fsn1",
        ///         AuthMethod = "ssh_key",
        ///         SshKeyId = deployKey.Id,
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Task<GetSshKeysResult> InvokeAsync(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetSshKeysResult>("danubedata:index/getSshKeys:getSshKeys", InvokeArgs.Empty, options.WithDefaults());

        /// <summary>
        /// ## # danubedata.getSshKeys
        /// 
        /// Lists all SSH keys in your account.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using DanubeData = Pulumi.DanubeData;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var all = DanubeData.GetSshKeys.Invoke();
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["sshKeyIds"] = .Select(key =&gt; 
        ///         {
        ///             return key.Id;
        ///         }).ToList(),
        ///         ["sshKeyNames"] = .Select(key =&gt; 
        ///         {
        ///             return key.Name;
        ///         }).ToList(),
        ///     };
        /// });
        /// ```
        /// 
        /// ### Find Key by Name
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using DanubeData = DanubeData.DanubeData;
        /// using DanubeData = Pulumi.DanubeData;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var all = DanubeData.GetSshKeys.Invoke();
        /// 
        ///     var deployKey = .Where(key =&gt; key.Name == "deploy-key").Select(key =&gt; 
        ///     {
        ///         return key;
        ///     }).ToList()[0];
        /// 
        ///     var server = new DanubeData.Vps("server", new()
        ///     {
        ///         Image = "ubuntu-22.04",
        ///         Datacenter = "fsn1",
        ///         AuthMethod = "ssh_key",
        ///         SshKeyId = deployKey.Id,
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetSshKeysResult> Invoke(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetSshKeysResult>("danubedata:index/getSshKeys:getSshKeys", InvokeArgs.Empty, options.WithDefaults());
    }


    [OutputType]
    public sealed class GetSshKeysResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// List of SSH keys. Each key contains:
        /// </summary>
        public readonly ImmutableArray<Outputs.GetSshKeysKeyResult> Keys;

        [OutputConstructor]
        private GetSshKeysResult(
            string id,

            ImmutableArray<Outputs.GetSshKeysKeyResult> keys)
        {
            Id = id;
            Keys = keys;
        }
    }
}
