// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DanubeData.DanubeData
{
    public static class GetStorageAccessKeys
    {
        /// <summary>
        /// ## # danubedata.getStorageAccessKeys
        /// 
        /// Lists all S3 storage access keys in your account.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using DanubeData = Pulumi.DanubeData;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var all = DanubeData.GetStorageAccessKeys.Invoke();
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["keyCount"] = all.Apply(getStorageAccessKeysResult =&gt; getStorageAccessKeysResult.Keys).Length,
        ///         ["activeKeys"] = .Where(k =&gt; k.Status == "active").Select(k =&gt; 
        ///         {
        ///             return k.Name;
        ///         }).ToList(),
        ///     };
        /// });
        /// ```
        /// 
        /// ### Find Key by Name
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using DanubeData = Pulumi.DanubeData;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var all = DanubeData.GetStorageAccessKeys.Invoke();
        /// 
        ///     var appKey = .Where(k =&gt; k.Name == "app-access-key").Select(k =&gt; 
        ///     {
        ///         return k;
        ///     }).ToList()[0];
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["appAccessKeyId"] = appKey.AccessKeyId,
        ///     };
        /// });
        /// ```
        /// 
        /// ### Filter Active Keys
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using DanubeData = Pulumi.DanubeData;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var all = DanubeData.GetStorageAccessKeys.Invoke();
        /// 
        ///     var activeKeys = .Where(k =&gt; k.Status == "active" &amp;&amp; !k.IsExpired).Select(k =&gt; 
        ///     {
        ///         return k;
        ///     }).ToList();
        /// 
        ///     var expiredKeys = ;
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["activeCount"] = activeKeys.Length,
        ///         ["expiredCount"] = expiredKeys.Apply(expiredKeys =&gt; expiredKeys.Length),
        ///     };
        /// });
        /// ```
        /// 
        /// ## Notes
        /// 
        /// - The `secret_access_key` is not included in this data source for security reasons.
        /// - Secret access keys are only available during creation.
        /// - To get a new secret key, create a new access key resource.
        /// </summary>
        public static Task<GetStorageAccessKeysResult> InvokeAsync(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetStorageAccessKeysResult>("danubedata:index/getStorageAccessKeys:getStorageAccessKeys", InvokeArgs.Empty, options.WithDefaults());

        /// <summary>
        /// ## # danubedata.getStorageAccessKeys
        /// 
        /// Lists all S3 storage access keys in your account.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using DanubeData = Pulumi.DanubeData;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var all = DanubeData.GetStorageAccessKeys.Invoke();
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["keyCount"] = all.Apply(getStorageAccessKeysResult =&gt; getStorageAccessKeysResult.Keys).Length,
        ///         ["activeKeys"] = .Where(k =&gt; k.Status == "active").Select(k =&gt; 
        ///         {
        ///             return k.Name;
        ///         }).ToList(),
        ///     };
        /// });
        /// ```
        /// 
        /// ### Find Key by Name
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using DanubeData = Pulumi.DanubeData;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var all = DanubeData.GetStorageAccessKeys.Invoke();
        /// 
        ///     var appKey = .Where(k =&gt; k.Name == "app-access-key").Select(k =&gt; 
        ///     {
        ///         return k;
        ///     }).ToList()[0];
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["appAccessKeyId"] = appKey.AccessKeyId,
        ///     };
        /// });
        /// ```
        /// 
        /// ### Filter Active Keys
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using DanubeData = Pulumi.DanubeData;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var all = DanubeData.GetStorageAccessKeys.Invoke();
        /// 
        ///     var activeKeys = .Where(k =&gt; k.Status == "active" &amp;&amp; !k.IsExpired).Select(k =&gt; 
        ///     {
        ///         return k;
        ///     }).ToList();
        /// 
        ///     var expiredKeys = ;
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["activeCount"] = activeKeys.Length,
        ///         ["expiredCount"] = expiredKeys.Apply(expiredKeys =&gt; expiredKeys.Length),
        ///     };
        /// });
        /// ```
        /// 
        /// ## Notes
        /// 
        /// - The `secret_access_key` is not included in this data source for security reasons.
        /// - Secret access keys are only available during creation.
        /// - To get a new secret key, create a new access key resource.
        /// </summary>
        public static Output<GetStorageAccessKeysResult> Invoke(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetStorageAccessKeysResult>("danubedata:index/getStorageAccessKeys:getStorageAccessKeys", InvokeArgs.Empty, options.WithDefaults());
    }


    [OutputType]
    public sealed class GetStorageAccessKeysResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// List of storage access keys. Each key contains:
        /// </summary>
        public readonly ImmutableArray<Outputs.GetStorageAccessKeysKeyResult> Keys;

        [OutputConstructor]
        private GetStorageAccessKeysResult(
            string id,

            ImmutableArray<Outputs.GetStorageAccessKeysKeyResult> keys)
        {
            Id = id;
            Keys = keys;
        }
    }
}
