// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DanubeData.DanubeData
{
    public static class GetServerlessContainers
    {
        /// <summary>
        /// ## # danubedata.getServerlessContainers
        /// 
        /// Lists all serverless containers in your account.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using DanubeData = Pulumi.DanubeData;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var all = DanubeData.GetServerlessContainers.Invoke();
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["containerCount"] = all.Apply(getServerlessContainersResult =&gt; getServerlessContainersResult.Containers).Length,
        ///         ["containerUrls"] = .ToDictionary(item =&gt; {
        ///             var c = item.Value;
        ///             return c.Name;
        ///         }, item =&gt; {
        ///             var c = item.Value;
        ///             return c.Url;
        ///         }),
        ///     };
        /// });
        /// ```
        /// 
        /// ### Find Container by Name
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using DanubeData = Pulumi.DanubeData;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var all = DanubeData.GetServerlessContainers.Invoke();
        /// 
        ///     var apiContainer = .Where(c =&gt; c.Name == "api-server").Select(c =&gt; 
        ///     {
        ///         return c;
        ///     }).ToList()[0];
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["apiUrl"] = apiContainer.Url,
        ///         ["apiStatus"] = apiContainer.Status,
        ///     };
        /// });
        /// ```
        /// 
        /// ### Filter by Deployment Type
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using DanubeData = Pulumi.DanubeData;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var all = DanubeData.GetServerlessContainers.Invoke();
        /// 
        ///     var dockerContainers = .Where(c =&gt; c.DeploymentType == "docker").Select(c =&gt; 
        ///     {
        ///         return c;
        ///     }).ToList();
        /// 
        ///     var gitContainers = .Where(c =&gt; c.DeploymentType == "git").Select(c =&gt; 
        ///     {
        ///         return c;
        ///     }).ToList();
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["dockerCount"] = dockerContainers.Length,
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Task<GetServerlessContainersResult> InvokeAsync(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetServerlessContainersResult>("danubedata:index/getServerlessContainers:getServerlessContainers", InvokeArgs.Empty, options.WithDefaults());

        /// <summary>
        /// ## # danubedata.getServerlessContainers
        /// 
        /// Lists all serverless containers in your account.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using DanubeData = Pulumi.DanubeData;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var all = DanubeData.GetServerlessContainers.Invoke();
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["containerCount"] = all.Apply(getServerlessContainersResult =&gt; getServerlessContainersResult.Containers).Length,
        ///         ["containerUrls"] = .ToDictionary(item =&gt; {
        ///             var c = item.Value;
        ///             return c.Name;
        ///         }, item =&gt; {
        ///             var c = item.Value;
        ///             return c.Url;
        ///         }),
        ///     };
        /// });
        /// ```
        /// 
        /// ### Find Container by Name
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using DanubeData = Pulumi.DanubeData;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var all = DanubeData.GetServerlessContainers.Invoke();
        /// 
        ///     var apiContainer = .Where(c =&gt; c.Name == "api-server").Select(c =&gt; 
        ///     {
        ///         return c;
        ///     }).ToList()[0];
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["apiUrl"] = apiContainer.Url,
        ///         ["apiStatus"] = apiContainer.Status,
        ///     };
        /// });
        /// ```
        /// 
        /// ### Filter by Deployment Type
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using DanubeData = Pulumi.DanubeData;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var all = DanubeData.GetServerlessContainers.Invoke();
        /// 
        ///     var dockerContainers = .Where(c =&gt; c.DeploymentType == "docker").Select(c =&gt; 
        ///     {
        ///         return c;
        ///     }).ToList();
        /// 
        ///     var gitContainers = .Where(c =&gt; c.DeploymentType == "git").Select(c =&gt; 
        ///     {
        ///         return c;
        ///     }).ToList();
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["dockerCount"] = dockerContainers.Length,
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Output<GetServerlessContainersResult> Invoke(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetServerlessContainersResult>("danubedata:index/getServerlessContainers:getServerlessContainers", InvokeArgs.Empty, options.WithDefaults());
    }


    [OutputType]
    public sealed class GetServerlessContainersResult
    {
        /// <summary>
        /// List of serverless containers. Each container contains:
        /// </summary>
        public readonly ImmutableArray<Outputs.GetServerlessContainersContainerResult> Containers;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;

        [OutputConstructor]
        private GetServerlessContainersResult(
            ImmutableArray<Outputs.GetServerlessContainersContainerResult> containers,

            string id)
        {
            Containers = containers;
            Id = id;
        }
    }
}
