// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DanubeData.DanubeData
{
    public static class GetVpsSnapshots
    {
        /// <summary>
        /// ## # danubedata.getVpsSnapshots
        /// 
        /// Lists all VPS snapshots in your account.
        /// 
        /// ### Find Snapshot by Name
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using DanubeData = Pulumi.DanubeData;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var all = DanubeData.GetVpsSnapshots.Invoke();
        /// 
        ///     var preUpgrade = .Where(s =&gt; s.Name == "pre-upgrade-backup").Select(s =&gt; 
        ///     {
        ///         return s;
        ///     }).ToList()[0];
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["preUpgradeSnapshotId"] = preUpgrade.Id,
        ///     };
        /// });
        /// ```
        /// 
        /// ### Filter Snapshots by VPS Instance
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using DanubeData = Pulumi.DanubeData;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var all = DanubeData.GetVpsSnapshots.Invoke();
        /// 
        ///     var config = new Config();
        ///     var vpsId = config.Get("vpsId") ?? "vps-abc123";
        ///     var vpsSnapshots = .Where(s =&gt; s.VpsInstanceId == vpsId).Select(s =&gt; 
        ///     {
        ///         return s;
        ///     }).ToList();
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["vpsSnapshotCount"] = vpsSnapshots.Length,
        ///     };
        /// });
        /// ```
        /// 
        /// ### Filter Ready Snapshots
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using DanubeData = Pulumi.DanubeData;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var all = DanubeData.GetVpsSnapshots.Invoke();
        /// 
        ///     var readySnapshots = .Where(s =&gt; s.Status == "ready").Select(s =&gt; 
        ///     {
        ///         return s;
        ///     }).ToList();
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["readyCount"] = readySnapshots.Length,
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Task<GetVpsSnapshotsResult> InvokeAsync(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetVpsSnapshotsResult>("danubedata:index/getVpsSnapshots:getVpsSnapshots", InvokeArgs.Empty, options.WithDefaults());

        /// <summary>
        /// ## # danubedata.getVpsSnapshots
        /// 
        /// Lists all VPS snapshots in your account.
        /// 
        /// ### Find Snapshot by Name
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using DanubeData = Pulumi.DanubeData;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var all = DanubeData.GetVpsSnapshots.Invoke();
        /// 
        ///     var preUpgrade = .Where(s =&gt; s.Name == "pre-upgrade-backup").Select(s =&gt; 
        ///     {
        ///         return s;
        ///     }).ToList()[0];
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["preUpgradeSnapshotId"] = preUpgrade.Id,
        ///     };
        /// });
        /// ```
        /// 
        /// ### Filter Snapshots by VPS Instance
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using DanubeData = Pulumi.DanubeData;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var all = DanubeData.GetVpsSnapshots.Invoke();
        /// 
        ///     var config = new Config();
        ///     var vpsId = config.Get("vpsId") ?? "vps-abc123";
        ///     var vpsSnapshots = .Where(s =&gt; s.VpsInstanceId == vpsId).Select(s =&gt; 
        ///     {
        ///         return s;
        ///     }).ToList();
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["vpsSnapshotCount"] = vpsSnapshots.Length,
        ///     };
        /// });
        /// ```
        /// 
        /// ### Filter Ready Snapshots
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using DanubeData = Pulumi.DanubeData;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var all = DanubeData.GetVpsSnapshots.Invoke();
        /// 
        ///     var readySnapshots = .Where(s =&gt; s.Status == "ready").Select(s =&gt; 
        ///     {
        ///         return s;
        ///     }).ToList();
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["readyCount"] = readySnapshots.Length,
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Output<GetVpsSnapshotsResult> Invoke(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetVpsSnapshotsResult>("danubedata:index/getVpsSnapshots:getVpsSnapshots", InvokeArgs.Empty, options.WithDefaults());
    }


    [OutputType]
    public sealed class GetVpsSnapshotsResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// List of VPS snapshots. Each snapshot contains:
        /// </summary>
        public readonly ImmutableArray<Outputs.GetVpsSnapshotsSnapshotResult> Snapshots;

        [OutputConstructor]
        private GetVpsSnapshotsResult(
            string id,

            ImmutableArray<Outputs.GetVpsSnapshotsSnapshotResult> snapshots)
        {
            Id = id;
            Snapshots = snapshots;
        }
    }
}
