// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DanubeData.DanubeData
{
    public static class GetVpsImages
    {
        /// <summary>
        /// ## # danubedata.getVpsImages
        /// 
        /// Lists available VPS operating system images.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using DanubeData = Pulumi.DanubeData;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var all = DanubeData.GetVpsImages.Invoke();
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["availableImages"] = .Select(img =&gt; 
        ///         {
        ///             return img.Image;
        ///         }).ToList(),
        ///     };
        /// });
        /// ```
        /// 
        /// ### Filter Ubuntu Images
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using DanubeData = Pulumi.DanubeData;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var all = DanubeData.GetVpsImages.Invoke();
        /// 
        ///     var myUbuntuImages = .Where(img =&gt; img.Distro == "ubuntu").Select(img =&gt; 
        ///     {
        ///         return img;
        ///     }).ToList();
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["ubuntuImages"] = myUbuntuImages,
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Task<GetVpsImagesResult> InvokeAsync(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetVpsImagesResult>("danubedata:index/getVpsImages:getVpsImages", InvokeArgs.Empty, options.WithDefaults());

        /// <summary>
        /// ## # danubedata.getVpsImages
        /// 
        /// Lists available VPS operating system images.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using DanubeData = Pulumi.DanubeData;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var all = DanubeData.GetVpsImages.Invoke();
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["availableImages"] = .Select(img =&gt; 
        ///         {
        ///             return img.Image;
        ///         }).ToList(),
        ///     };
        /// });
        /// ```
        /// 
        /// ### Filter Ubuntu Images
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using DanubeData = Pulumi.DanubeData;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var all = DanubeData.GetVpsImages.Invoke();
        /// 
        ///     var myUbuntuImages = .Where(img =&gt; img.Distro == "ubuntu").Select(img =&gt; 
        ///     {
        ///         return img;
        ///     }).ToList();
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["ubuntuImages"] = myUbuntuImages,
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Output<GetVpsImagesResult> Invoke(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetVpsImagesResult>("danubedata:index/getVpsImages:getVpsImages", InvokeArgs.Empty, options.WithDefaults());
    }


    [OutputType]
    public sealed class GetVpsImagesResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// List of available images. Each image contains:
        /// </summary>
        public readonly ImmutableArray<Outputs.GetVpsImagesImageResult> Images;

        [OutputConstructor]
        private GetVpsImagesResult(
            string id,

            ImmutableArray<Outputs.GetVpsImagesImageResult> images)
        {
            Id = id;
            Images = images;
        }
    }
}
