// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DanubeData.DanubeData
{
    public static class GetVpss
    {
        /// <summary>
        /// ## # danubedata.getVpss
        /// 
        /// Lists all VPS instances in your account.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using DanubeData = Pulumi.DanubeData;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var all = DanubeData.GetVpss.Invoke();
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["vpsCount"] = all.Apply(getVpssResult =&gt; getVpssResult.Instances).Length,
        ///         ["vpsNames"] = .Select(vps =&gt; 
        ///         {
        ///             return vps.Name;
        ///         }).ToList(),
        ///     };
        /// });
        /// ```
        /// 
        /// ### Find VPS by Name
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using DanubeData = Pulumi.DanubeData;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var all = DanubeData.GetVpss.Invoke();
        /// 
        ///     var webServer = .Where(vps =&gt; vps.Name == "web-server").Select(vps =&gt; 
        ///     {
        ///         return vps;
        ///     }).ToList()[0];
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["webServerIp"] = webServer.PublicIp,
        ///     };
        /// });
        /// ```
        /// 
        /// ### Filter Running Instances
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using DanubeData = Pulumi.DanubeData;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var all = DanubeData.GetVpss.Invoke();
        /// 
        ///     var runningInstances = .Where(vps =&gt; vps.Status == "running").Select(vps =&gt; 
        ///     {
        ///         return vps;
        ///     }).ToList();
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["runningCount"] = runningInstances.Length,
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Task<GetVpssResult> InvokeAsync(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetVpssResult>("danubedata:index/getVpss:getVpss", InvokeArgs.Empty, options.WithDefaults());

        /// <summary>
        /// ## # danubedata.getVpss
        /// 
        /// Lists all VPS instances in your account.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using DanubeData = Pulumi.DanubeData;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var all = DanubeData.GetVpss.Invoke();
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["vpsCount"] = all.Apply(getVpssResult =&gt; getVpssResult.Instances).Length,
        ///         ["vpsNames"] = .Select(vps =&gt; 
        ///         {
        ///             return vps.Name;
        ///         }).ToList(),
        ///     };
        /// });
        /// ```
        /// 
        /// ### Find VPS by Name
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using DanubeData = Pulumi.DanubeData;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var all = DanubeData.GetVpss.Invoke();
        /// 
        ///     var webServer = .Where(vps =&gt; vps.Name == "web-server").Select(vps =&gt; 
        ///     {
        ///         return vps;
        ///     }).ToList()[0];
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["webServerIp"] = webServer.PublicIp,
        ///     };
        /// });
        /// ```
        /// 
        /// ### Filter Running Instances
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using DanubeData = Pulumi.DanubeData;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var all = DanubeData.GetVpss.Invoke();
        /// 
        ///     var runningInstances = .Where(vps =&gt; vps.Status == "running").Select(vps =&gt; 
        ///     {
        ///         return vps;
        ///     }).ToList();
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["runningCount"] = runningInstances.Length,
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Output<GetVpssResult> Invoke(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetVpssResult>("danubedata:index/getVpss:getVpss", InvokeArgs.Empty, options.WithDefaults());
    }


    [OutputType]
    public sealed class GetVpssResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// List of VPS instances. Each instance contains:
        /// </summary>
        public readonly ImmutableArray<Outputs.GetVpssInstanceResult> Instances;

        [OutputConstructor]
        private GetVpssResult(
            string id,

            ImmutableArray<Outputs.GetVpssInstanceResult> instances)
        {
            Id = id;
            Instances = instances;
        }
    }
}
