// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DanubeData.DanubeData
{
    /// <summary>
    /// ## # danubedata.Serverless
    /// 
    /// Manages a serverless container with automatic scaling and scale-to-zero support.
    /// 
    /// ## Example Usage
    /// 
    /// ### Docker Image Deployment
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using DanubeData = DanubeData.DanubeData;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var nginx = new DanubeData.Serverless("nginx", new()
    ///     {
    ///         DeploymentType = "docker",
    ///         ImageUrl = "nginx:latest",
    ///         Port = 80,
    ///         MinInstances = 0,
    ///         MaxInstances = 10,
    ///     });
    /// 
    ///     return new Dictionary&lt;string, object?&gt;
    ///     {
    ///         ["appUrl"] = nginx.Url,
    ///     };
    /// });
    /// ```
    /// 
    /// ### Git Repository Deployment
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using DanubeData = DanubeData.DanubeData;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var app = new DanubeData.Serverless("app", new()
    ///     {
    ///         DeploymentType = "git",
    ///         EnvironmentVariables = 
    ///         {
    ///             { "LOG_LEVEL", "info" },
    ///             { "NODE_ENV", "production" },
    ///         },
    ///         GitBranch = "main",
    ///         GitRepository = "https://github.com/user/my-app",
    ///         MaxInstances = 5,
    ///         MinInstances = 1,
    ///         Port = 8080,
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ### With Resource Profile
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using DanubeData = DanubeData.DanubeData;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var api = new DanubeData.Serverless("api", new()
    ///     {
    ///         DeploymentType = "docker",
    ///         EnvironmentVariables = 
    ///         {
    ///             { "DATABASE_URL", "postgres://..." },
    ///             { "REDIS_URL", "redis://..." },
    ///         },
    ///         ImageUrl = "myregistry/api:v1.0",
    ///         MaxInstances = 20,
    ///         MinInstances = 2,
    ///         Port = 3000,
    ///         ResourceProfile = "medium",
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ### Scale to Zero Configuration
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using DanubeData = DanubeData.DanubeData;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var webhook = new DanubeData.Serverless("webhook", new()
    ///     {
    ///         DeploymentType = "docker",
    ///         ImageUrl = "myregistry/webhook:latest",
    ///         MaxInstances = 100,
    ///         MinInstances = 0,
    ///         Port = 8080,
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Scaling Behavior
    /// 
    /// - **min_instances = 0**: Container scales to zero after idle period (cost-effective)
    /// - **min_instances &gt;= 1**: Always keeps instances running (no cold starts)
    /// - Scales up automatically based on traffic
    /// - Scales down when traffic decreases
    /// 
    /// ## Build Process (Git Deployment)
    /// 
    /// When using `git` deployment type:
    /// 1. Repository is cloned
    /// 2. Buildpack detection or Dockerfile is used
    /// 3. Container image is built
    /// 4. Image is deployed to serverless platform
    /// 5. Automatic rebuilds on git push (via webhook)
    /// 
    /// ## Import
    /// 
    /// Serverless containers can be imported using their ID:
    /// 
    /// bash
    /// 
    /// ```sh
    /// $ pulumi import danubedata:index/serverless:Serverless example srv-abc123
    /// ```
    /// </summary>
    [DanubeDataResourceType("danubedata:index/serverless:Serverless")]
    public partial class Serverless : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Creation timestamp.
        /// </summary>
        [Output("createdAt")]
        public Output<string> CreatedAt { get; private set; } = null!;

        /// <summary>
        /// Current month's cost in cents.
        /// </summary>
        [Output("currentMonthCostCents")]
        public Output<int> CurrentMonthCostCents { get; private set; } = null!;

        /// <summary>
        /// Deployment type: 'image' for Docker image, 'git' for Git repository.
        /// </summary>
        [Output("deploymentType")]
        public Output<string> DeploymentType { get; private set; } = null!;

        /// <summary>
        /// Environment variables for the container.
        /// </summary>
        [Output("environmentVariables")]
        public Output<ImmutableDictionary<string, string>?> EnvironmentVariables { get; private set; } = null!;

        /// <summary>
        /// Git branch to deploy.
        /// </summary>
        [Output("gitBranch")]
        public Output<string> GitBranch { get; private set; } = null!;

        /// <summary>
        /// Git repository URL (required if deployment_type is 'git').
        /// </summary>
        [Output("gitRepository")]
        public Output<string?> GitRepository { get; private set; } = null!;

        /// <summary>
        /// Docker image URL (required if deployment_type is 'image').
        /// </summary>
        [Output("imageUrl")]
        public Output<string?> ImageUrl { get; private set; } = null!;

        /// <summary>
        /// Maximum number of instances.
        /// </summary>
        [Output("maxInstances")]
        public Output<int> MaxInstances { get; private set; } = null!;

        /// <summary>
        /// Minimum number of instances (0 for scale-to-zero).
        /// </summary>
        [Output("minInstances")]
        public Output<int> MinInstances { get; private set; } = null!;

        /// <summary>
        /// Name of the serverless container.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Port the container listens on.
        /// </summary>
        [Output("port")]
        public Output<int> Port { get; private set; } = null!;

        /// <summary>
        /// Resource profile for the container (small, medium, large).
        /// </summary>
        [Output("resourceProfile")]
        public Output<string> ResourceProfile { get; private set; } = null!;

        /// <summary>
        /// Current status.
        /// </summary>
        [Output("status")]
        public Output<string> Status { get; private set; } = null!;

        [Output("timeouts")]
        public Output<Outputs.ServerlessTimeouts?> Timeouts { get; private set; } = null!;

        /// <summary>
        /// Timestamp when the container was last updated.
        /// </summary>
        [Output("updatedAt")]
        public Output<string> UpdatedAt { get; private set; } = null!;

        /// <summary>
        /// Public HTTPS URL for the container.
        /// </summary>
        [Output("url")]
        public Output<string> Url { get; private set; } = null!;


        /// <summary>
        /// Create a Serverless resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Serverless(string name, ServerlessArgs args, CustomResourceOptions? options = null)
            : base("danubedata:index/serverless:Serverless", name, args ?? new ServerlessArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Serverless(string name, Input<string> id, ServerlessState? state = null, CustomResourceOptions? options = null)
            : base("danubedata:index/serverless:Serverless", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/AdrianSilaghi/pulumi-danubedata",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Serverless resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Serverless Get(string name, Input<string> id, ServerlessState? state = null, CustomResourceOptions? options = null)
        {
            return new Serverless(name, id, state, options);
        }
    }

    public sealed class ServerlessArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Deployment type: 'image' for Docker image, 'git' for Git repository.
        /// </summary>
        [Input("deploymentType", required: true)]
        public Input<string> DeploymentType { get; set; } = null!;

        [Input("environmentVariables")]
        private InputMap<string>? _environmentVariables;

        /// <summary>
        /// Environment variables for the container.
        /// </summary>
        public InputMap<string> EnvironmentVariables
        {
            get => _environmentVariables ?? (_environmentVariables = new InputMap<string>());
            set => _environmentVariables = value;
        }

        /// <summary>
        /// Git branch to deploy.
        /// </summary>
        [Input("gitBranch")]
        public Input<string>? GitBranch { get; set; }

        /// <summary>
        /// Git repository URL (required if deployment_type is 'git').
        /// </summary>
        [Input("gitRepository")]
        public Input<string>? GitRepository { get; set; }

        /// <summary>
        /// Docker image URL (required if deployment_type is 'image').
        /// </summary>
        [Input("imageUrl")]
        public Input<string>? ImageUrl { get; set; }

        /// <summary>
        /// Maximum number of instances.
        /// </summary>
        [Input("maxInstances")]
        public Input<int>? MaxInstances { get; set; }

        /// <summary>
        /// Minimum number of instances (0 for scale-to-zero).
        /// </summary>
        [Input("minInstances")]
        public Input<int>? MinInstances { get; set; }

        /// <summary>
        /// Name of the serverless container.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Port the container listens on.
        /// </summary>
        [Input("port")]
        public Input<int>? Port { get; set; }

        /// <summary>
        /// Resource profile for the container (small, medium, large).
        /// </summary>
        [Input("resourceProfile")]
        public Input<string>? ResourceProfile { get; set; }

        [Input("timeouts")]
        public Input<Inputs.ServerlessTimeoutsArgs>? Timeouts { get; set; }

        public ServerlessArgs()
        {
        }
        public static new ServerlessArgs Empty => new ServerlessArgs();
    }

    public sealed class ServerlessState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Creation timestamp.
        /// </summary>
        [Input("createdAt")]
        public Input<string>? CreatedAt { get; set; }

        /// <summary>
        /// Current month's cost in cents.
        /// </summary>
        [Input("currentMonthCostCents")]
        public Input<int>? CurrentMonthCostCents { get; set; }

        /// <summary>
        /// Deployment type: 'image' for Docker image, 'git' for Git repository.
        /// </summary>
        [Input("deploymentType")]
        public Input<string>? DeploymentType { get; set; }

        [Input("environmentVariables")]
        private InputMap<string>? _environmentVariables;

        /// <summary>
        /// Environment variables for the container.
        /// </summary>
        public InputMap<string> EnvironmentVariables
        {
            get => _environmentVariables ?? (_environmentVariables = new InputMap<string>());
            set => _environmentVariables = value;
        }

        /// <summary>
        /// Git branch to deploy.
        /// </summary>
        [Input("gitBranch")]
        public Input<string>? GitBranch { get; set; }

        /// <summary>
        /// Git repository URL (required if deployment_type is 'git').
        /// </summary>
        [Input("gitRepository")]
        public Input<string>? GitRepository { get; set; }

        /// <summary>
        /// Docker image URL (required if deployment_type is 'image').
        /// </summary>
        [Input("imageUrl")]
        public Input<string>? ImageUrl { get; set; }

        /// <summary>
        /// Maximum number of instances.
        /// </summary>
        [Input("maxInstances")]
        public Input<int>? MaxInstances { get; set; }

        /// <summary>
        /// Minimum number of instances (0 for scale-to-zero).
        /// </summary>
        [Input("minInstances")]
        public Input<int>? MinInstances { get; set; }

        /// <summary>
        /// Name of the serverless container.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Port the container listens on.
        /// </summary>
        [Input("port")]
        public Input<int>? Port { get; set; }

        /// <summary>
        /// Resource profile for the container (small, medium, large).
        /// </summary>
        [Input("resourceProfile")]
        public Input<string>? ResourceProfile { get; set; }

        /// <summary>
        /// Current status.
        /// </summary>
        [Input("status")]
        public Input<string>? Status { get; set; }

        [Input("timeouts")]
        public Input<Inputs.ServerlessTimeoutsGetArgs>? Timeouts { get; set; }

        /// <summary>
        /// Timestamp when the container was last updated.
        /// </summary>
        [Input("updatedAt")]
        public Input<string>? UpdatedAt { get; set; }

        /// <summary>
        /// Public HTTPS URL for the container.
        /// </summary>
        [Input("url")]
        public Input<string>? Url { get; set; }

        public ServerlessState()
        {
        }
        public static new ServerlessState Empty => new ServerlessState();
    }
}
