// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DanubeData.DanubeData
{
    /// <summary>
    /// ## # danubedata.StorageBucket
    /// 
    /// Manages an S3-compatible object storage bucket.
    /// 
    /// ## Example Usage
    /// 
    /// ### Basic Bucket
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using DanubeData = DanubeData.DanubeData;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var assets = new DanubeData.StorageBucket("assets", new()
    ///     {
    ///         Region = "fsn1",
    ///     });
    /// 
    ///     return new Dictionary&lt;string, object?&gt;
    ///     {
    ///         ["bucketEndpoint"] = assets.EndpointUrl,
    ///     };
    /// });
    /// ```
    /// 
    /// ### Bucket with Versioning
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using DanubeData = DanubeData.DanubeData;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var backups = new DanubeData.StorageBucket("backups", new()
    ///     {
    ///         Region = "fsn1",
    ///         VersioningEnabled = true,
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ### Public Bucket
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using DanubeData = DanubeData.DanubeData;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var @public = new DanubeData.StorageBucket("public", new()
    ///     {
    ///         PublicAccess = true,
    ///         Region = "fsn1",
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ### Complete Configuration
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using DanubeData = DanubeData.DanubeData;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var data = new DanubeData.StorageBucket("data", new()
    ///     {
    ///         DisplayName = "Application Data",
    ///         EncryptionEnabled = true,
    ///         PublicAccess = false,
    ///         Region = "fsn1",
    ///         VersioningEnabled = true,
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Pricing
    /// 
    /// - Base: EUR 3.99/month
    /// - Includes: 1TB storage + 1TB egress traffic
    /// - Overage: EUR 0.01/GB for storage, EUR 0.01/GB for egress
    /// 
    /// ## Import
    /// 
    /// Storage buckets can be imported using their ID:
    /// 
    /// bash
    /// 
    /// ```sh
    /// $ pulumi import danubedata:index/storageBucket:StorageBucket example bucket-abc123
    /// ```
    /// </summary>
    [DanubeDataResourceType("danubedata:index/storageBucket:StorageBucket")]
    public partial class StorageBucket : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Creation timestamp.
        /// </summary>
        [Output("createdAt")]
        public Output<string> CreatedAt { get; private set; } = null!;

        /// <summary>
        /// Human-readable display name for the bucket.
        /// </summary>
        [Output("displayName")]
        public Output<string?> DisplayName { get; private set; } = null!;

        /// <summary>
        /// Whether server-side encryption is enabled.
        /// </summary>
        [Output("encryptionEnabled")]
        public Output<bool> EncryptionEnabled { get; private set; } = null!;

        /// <summary>
        /// Encryption type (none, sse-s3, sse-kms).
        /// </summary>
        [Output("encryptionType")]
        public Output<string> EncryptionType { get; private set; } = null!;

        /// <summary>
        /// S3-compatible endpoint URL.
        /// </summary>
        [Output("endpointUrl")]
        public Output<string> EndpointUrl { get; private set; } = null!;

        /// <summary>
        /// Internal bucket name.
        /// </summary>
        [Output("minioBucketName")]
        public Output<string> MinioBucketName { get; private set; } = null!;

        /// <summary>
        /// Estimated monthly cost.
        /// </summary>
        [Output("monthlyCost")]
        public Output<double> MonthlyCost { get; private set; } = null!;

        /// <summary>
        /// Monthly cost in cents.
        /// </summary>
        [Output("monthlyCostCents")]
        public Output<int> MonthlyCostCents { get; private set; } = null!;

        /// <summary>
        /// Name of the storage bucket. Must follow S3 bucket naming rules (3-63 chars, lowercase alphanumeric with hyphens).
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Number of objects.
        /// </summary>
        [Output("objectCount")]
        public Output<int> ObjectCount { get; private set; } = null!;

        /// <summary>
        /// Whether the bucket has public read access enabled.
        /// </summary>
        [Output("publicAccess")]
        public Output<bool> PublicAccess { get; private set; } = null!;

        /// <summary>
        /// Region for the storage bucket (fsn1).
        /// </summary>
        [Output("region")]
        public Output<string> Region { get; private set; } = null!;

        /// <summary>
        /// Current size in bytes.
        /// </summary>
        [Output("sizeBytes")]
        public Output<int> SizeBytes { get; private set; } = null!;

        /// <summary>
        /// Current status.
        /// </summary>
        [Output("status")]
        public Output<string> Status { get; private set; } = null!;

        [Output("timeouts")]
        public Output<Outputs.StorageBucketTimeouts?> Timeouts { get; private set; } = null!;

        /// <summary>
        /// Timestamp when the bucket was last updated.
        /// </summary>
        [Output("updatedAt")]
        public Output<string> UpdatedAt { get; private set; } = null!;

        /// <summary>
        /// Whether object versioning is enabled.
        /// </summary>
        [Output("versioningEnabled")]
        public Output<bool> VersioningEnabled { get; private set; } = null!;


        /// <summary>
        /// Create a StorageBucket resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public StorageBucket(string name, StorageBucketArgs args, CustomResourceOptions? options = null)
            : base("danubedata:index/storageBucket:StorageBucket", name, args ?? new StorageBucketArgs(), MakeResourceOptions(options, ""))
        {
        }

        private StorageBucket(string name, Input<string> id, StorageBucketState? state = null, CustomResourceOptions? options = null)
            : base("danubedata:index/storageBucket:StorageBucket", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/AdrianSilaghi/pulumi-danubedata",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing StorageBucket resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static StorageBucket Get(string name, Input<string> id, StorageBucketState? state = null, CustomResourceOptions? options = null)
        {
            return new StorageBucket(name, id, state, options);
        }
    }

    public sealed class StorageBucketArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Human-readable display name for the bucket.
        /// </summary>
        [Input("displayName")]
        public Input<string>? DisplayName { get; set; }

        /// <summary>
        /// Whether server-side encryption is enabled.
        /// </summary>
        [Input("encryptionEnabled")]
        public Input<bool>? EncryptionEnabled { get; set; }

        /// <summary>
        /// Encryption type (none, sse-s3, sse-kms).
        /// </summary>
        [Input("encryptionType")]
        public Input<string>? EncryptionType { get; set; }

        /// <summary>
        /// Name of the storage bucket. Must follow S3 bucket naming rules (3-63 chars, lowercase alphanumeric with hyphens).
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Whether the bucket has public read access enabled.
        /// </summary>
        [Input("publicAccess")]
        public Input<bool>? PublicAccess { get; set; }

        /// <summary>
        /// Region for the storage bucket (fsn1).
        /// </summary>
        [Input("region", required: true)]
        public Input<string> Region { get; set; } = null!;

        [Input("timeouts")]
        public Input<Inputs.StorageBucketTimeoutsArgs>? Timeouts { get; set; }

        /// <summary>
        /// Whether object versioning is enabled.
        /// </summary>
        [Input("versioningEnabled")]
        public Input<bool>? VersioningEnabled { get; set; }

        public StorageBucketArgs()
        {
        }
        public static new StorageBucketArgs Empty => new StorageBucketArgs();
    }

    public sealed class StorageBucketState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Creation timestamp.
        /// </summary>
        [Input("createdAt")]
        public Input<string>? CreatedAt { get; set; }

        /// <summary>
        /// Human-readable display name for the bucket.
        /// </summary>
        [Input("displayName")]
        public Input<string>? DisplayName { get; set; }

        /// <summary>
        /// Whether server-side encryption is enabled.
        /// </summary>
        [Input("encryptionEnabled")]
        public Input<bool>? EncryptionEnabled { get; set; }

        /// <summary>
        /// Encryption type (none, sse-s3, sse-kms).
        /// </summary>
        [Input("encryptionType")]
        public Input<string>? EncryptionType { get; set; }

        /// <summary>
        /// S3-compatible endpoint URL.
        /// </summary>
        [Input("endpointUrl")]
        public Input<string>? EndpointUrl { get; set; }

        /// <summary>
        /// Internal bucket name.
        /// </summary>
        [Input("minioBucketName")]
        public Input<string>? MinioBucketName { get; set; }

        /// <summary>
        /// Estimated monthly cost.
        /// </summary>
        [Input("monthlyCost")]
        public Input<double>? MonthlyCost { get; set; }

        /// <summary>
        /// Monthly cost in cents.
        /// </summary>
        [Input("monthlyCostCents")]
        public Input<int>? MonthlyCostCents { get; set; }

        /// <summary>
        /// Name of the storage bucket. Must follow S3 bucket naming rules (3-63 chars, lowercase alphanumeric with hyphens).
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Number of objects.
        /// </summary>
        [Input("objectCount")]
        public Input<int>? ObjectCount { get; set; }

        /// <summary>
        /// Whether the bucket has public read access enabled.
        /// </summary>
        [Input("publicAccess")]
        public Input<bool>? PublicAccess { get; set; }

        /// <summary>
        /// Region for the storage bucket (fsn1).
        /// </summary>
        [Input("region")]
        public Input<string>? Region { get; set; }

        /// <summary>
        /// Current size in bytes.
        /// </summary>
        [Input("sizeBytes")]
        public Input<int>? SizeBytes { get; set; }

        /// <summary>
        /// Current status.
        /// </summary>
        [Input("status")]
        public Input<string>? Status { get; set; }

        [Input("timeouts")]
        public Input<Inputs.StorageBucketTimeoutsGetArgs>? Timeouts { get; set; }

        /// <summary>
        /// Timestamp when the bucket was last updated.
        /// </summary>
        [Input("updatedAt")]
        public Input<string>? UpdatedAt { get; set; }

        /// <summary>
        /// Whether object versioning is enabled.
        /// </summary>
        [Input("versioningEnabled")]
        public Input<bool>? VersioningEnabled { get; set; }

        public StorageBucketState()
        {
        }
        public static new StorageBucketState Empty => new StorageBucketState();
    }
}
