// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DanubeData.DanubeData
{
    /// <summary>
    /// ## # danubedata.VpsSnapshot
    /// 
    /// Manages a VPS snapshot for backup and recovery.
    /// 
    /// ## Example Usage
    /// 
    /// ### Basic Snapshot
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using DanubeData = DanubeData.DanubeData;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var server = new DanubeData.Vps("server", new()
    ///     {
    ///         Image = "ubuntu-22.04",
    ///         Datacenter = "fsn1",
    ///         AuthMethod = "ssh_key",
    ///         SshKeyId = danubedata_ssh_key.Main.Id,
    ///     });
    /// 
    ///     var backup = new DanubeData.VpsSnapshot("backup", new()
    ///     {
    ///         VpsInstanceId = server.Id,
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ### Snapshot with Description
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using DanubeData = DanubeData.DanubeData;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var release = new DanubeData.VpsSnapshot("release", new()
    ///     {
    ///         Description = "Snapshot before v1.0 release deployment",
    ///         VpsInstanceId = danubedata_vps.Server.Id,
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// VPS snapshots can be imported using their ID:
    /// 
    /// bash
    /// 
    /// ```sh
    /// $ pulumi import danubedata:index/vpsSnapshot:VpsSnapshot example snap-abc123
    /// ```
    /// </summary>
    [DanubeDataResourceType("danubedata:index/vpsSnapshot:VpsSnapshot")]
    public partial class VpsSnapshot : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Creation timestamp.
        /// </summary>
        [Output("createdAt")]
        public Output<string> CreatedAt { get; private set; } = null!;

        /// <summary>
        /// Description of the snapshot.
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// Name of the snapshot.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Size of the snapshot in GB.
        /// </summary>
        [Output("sizeGb")]
        public Output<double> SizeGb { get; private set; } = null!;

        /// <summary>
        /// Current status (`creating`, `ready`, `error`).
        /// </summary>
        [Output("status")]
        public Output<string> Status { get; private set; } = null!;

        [Output("timeouts")]
        public Output<Outputs.VpsSnapshotTimeouts?> Timeouts { get; private set; } = null!;

        /// <summary>
        /// Timestamp when the snapshot was last updated.
        /// </summary>
        [Output("updatedAt")]
        public Output<string> UpdatedAt { get; private set; } = null!;

        /// <summary>
        /// ID of the VPS instance to snapshot.
        /// </summary>
        [Output("vpsInstanceId")]
        public Output<string> VpsInstanceId { get; private set; } = null!;


        /// <summary>
        /// Create a VpsSnapshot resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public VpsSnapshot(string name, VpsSnapshotArgs args, CustomResourceOptions? options = null)
            : base("danubedata:index/vpsSnapshot:VpsSnapshot", name, args ?? new VpsSnapshotArgs(), MakeResourceOptions(options, ""))
        {
        }

        private VpsSnapshot(string name, Input<string> id, VpsSnapshotState? state = null, CustomResourceOptions? options = null)
            : base("danubedata:index/vpsSnapshot:VpsSnapshot", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/AdrianSilaghi/pulumi-danubedata",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing VpsSnapshot resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static VpsSnapshot Get(string name, Input<string> id, VpsSnapshotState? state = null, CustomResourceOptions? options = null)
        {
            return new VpsSnapshot(name, id, state, options);
        }
    }

    public sealed class VpsSnapshotArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Description of the snapshot.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Name of the snapshot.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("timeouts")]
        public Input<Inputs.VpsSnapshotTimeoutsArgs>? Timeouts { get; set; }

        /// <summary>
        /// ID of the VPS instance to snapshot.
        /// </summary>
        [Input("vpsInstanceId", required: true)]
        public Input<string> VpsInstanceId { get; set; } = null!;

        public VpsSnapshotArgs()
        {
        }
        public static new VpsSnapshotArgs Empty => new VpsSnapshotArgs();
    }

    public sealed class VpsSnapshotState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Creation timestamp.
        /// </summary>
        [Input("createdAt")]
        public Input<string>? CreatedAt { get; set; }

        /// <summary>
        /// Description of the snapshot.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Name of the snapshot.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Size of the snapshot in GB.
        /// </summary>
        [Input("sizeGb")]
        public Input<double>? SizeGb { get; set; }

        /// <summary>
        /// Current status (`creating`, `ready`, `error`).
        /// </summary>
        [Input("status")]
        public Input<string>? Status { get; set; }

        [Input("timeouts")]
        public Input<Inputs.VpsSnapshotTimeoutsGetArgs>? Timeouts { get; set; }

        /// <summary>
        /// Timestamp when the snapshot was last updated.
        /// </summary>
        [Input("updatedAt")]
        public Input<string>? UpdatedAt { get; set; }

        /// <summary>
        /// ID of the VPS instance to snapshot.
        /// </summary>
        [Input("vpsInstanceId")]
        public Input<string>? VpsInstanceId { get; set; }

        public VpsSnapshotState()
        {
        }
        public static new VpsSnapshotState Empty => new VpsSnapshotState();
    }
}
