// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("danubedata");

/**
 * API token for DanubeData authentication. Can also be set via DANUBEDATA_API_TOKEN environment variable.
 */
export declare const apiToken: string | undefined;
Object.defineProperty(exports, "apiToken", {
    get() {
        return __config.get("apiToken") ?? utilities.getEnv("DANUBEDATA_API_TOKEN");
    },
    enumerable: true,
});

/**
 * Base URL for the DanubeData API. Defaults to https://danubedata.ro/api/v1. Can also be set via DANUBEDATA_BASE_URL
 * environment variable.
 */
export declare const baseUrl: string;
Object.defineProperty(exports, "baseUrl", {
    get() {
        return __config.get("baseUrl") ?? (utilities.getEnv("DANUBEDATA_BASE_URL") || "https://danubedata.ro/api/v1");
    },
    enumerable: true,
});

