// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DanubeData.DanubeData.Outputs
{

    [OutputType]
    public sealed class DatabaseTimeouts
    {
        /// <summary>
        /// Time to wait for database creation.
        /// </summary>
        public readonly string? Create;
        /// <summary>
        /// Time to wait for database deletion.
        /// </summary>
        public readonly string? Delete;
        /// <summary>
        /// Time to wait for database updates.
        /// </summary>
        public readonly string? Update;

        [OutputConstructor]
        private DatabaseTimeouts(
            string? create,

            string? delete,

            string? update)
        {
            Create = create;
            Delete = delete;
            Update = update;
        }
    }
}
