// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DanubeData.DanubeData.Outputs
{

    [OutputType]
    public sealed class GetCachesInstanceResult
    {
        /// <summary>
        /// Cache provider (Redis, Valkey, Dragonfly).
        /// </summary>
        public readonly string CacheProvider;
        /// <summary>
        /// Number of CPU cores.
        /// </summary>
        public readonly int CpuCores;
        /// <summary>
        /// Timestamp when the instance was created.
        /// </summary>
        public readonly string CreatedAt;
        /// <summary>
        /// Datacenter location.
        /// </summary>
        public readonly string Datacenter;
        /// <summary>
        /// Connection endpoint hostname.
        /// </summary>
        public readonly string Endpoint;
        /// <summary>
        /// Unique identifier for the cache instance.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Memory size in MB.
        /// </summary>
        public readonly int MemorySizeMb;
        /// <summary>
        /// Estimated monthly cost.
        /// </summary>
        public readonly double MonthlyCost;
        /// <summary>
        /// Name of the cache instance.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Connection port.
        /// </summary>
        public readonly int Port;
        /// <summary>
        /// Resource profile (predefined CPU/RAM configuration).
        /// </summary>
        public readonly string ResourceProfile;
        /// <summary>
        /// Current status (creating, running, stopped, error).
        /// </summary>
        public readonly string Status;
        /// <summary>
        /// Cache version.
        /// </summary>
        public readonly string Version;

        [OutputConstructor]
        private GetCachesInstanceResult(
            string cacheProvider,

            int cpuCores,

            string createdAt,

            string datacenter,

            string endpoint,

            string id,

            int memorySizeMb,

            double monthlyCost,

            string name,

            int port,

            string resourceProfile,

            string status,

            string version)
        {
            CacheProvider = cacheProvider;
            CpuCores = cpuCores;
            CreatedAt = createdAt;
            Datacenter = datacenter;
            Endpoint = endpoint;
            Id = id;
            MemorySizeMb = memorySizeMb;
            MonthlyCost = monthlyCost;
            Name = name;
            Port = port;
            ResourceProfile = resourceProfile;
            Status = status;
            Version = version;
        }
    }
}
