// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DanubeData.DanubeData.Outputs
{

    [OutputType]
    public sealed class GetDatabasesInstanceResult
    {
        /// <summary>
        /// Number of CPU cores.
        /// </summary>
        public readonly int CpuCores;
        /// <summary>
        /// Timestamp when the instance was created.
        /// </summary>
        public readonly string CreatedAt;
        /// <summary>
        /// Name of the database.
        /// </summary>
        public readonly string DatabaseName;
        /// <summary>
        /// Datacenter location.
        /// </summary>
        public readonly string Datacenter;
        /// <summary>
        /// Connection endpoint hostname.
        /// </summary>
        public readonly string Endpoint;
        /// <summary>
        /// Database engine (MySQL, PostgreSQL, MariaDB).
        /// </summary>
        public readonly string Engine;
        /// <summary>
        /// Unique identifier for the database instance.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Memory size in MB.
        /// </summary>
        public readonly int MemorySizeMb;
        /// <summary>
        /// Estimated monthly cost.
        /// </summary>
        public readonly double MonthlyCost;
        /// <summary>
        /// Name of the database instance.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Connection port.
        /// </summary>
        public readonly int Port;
        /// <summary>
        /// Resource profile (predefined CPU/RAM/Storage configuration).
        /// </summary>
        public readonly string ResourceProfile;
        /// <summary>
        /// Current status (creating, running, stopped, error).
        /// </summary>
        public readonly string Status;
        /// <summary>
        /// Storage size in GB.
        /// </summary>
        public readonly int StorageSizeGb;
        /// <summary>
        /// Database admin username.
        /// </summary>
        public readonly string Username;
        /// <summary>
        /// Database version.
        /// </summary>
        public readonly string Version;

        [OutputConstructor]
        private GetDatabasesInstanceResult(
            int cpuCores,

            string createdAt,

            string databaseName,

            string datacenter,

            string endpoint,

            string engine,

            string id,

            int memorySizeMb,

            double monthlyCost,

            string name,

            int port,

            string resourceProfile,

            string status,

            int storageSizeGb,

            string username,

            string version)
        {
            CpuCores = cpuCores;
            CreatedAt = createdAt;
            DatabaseName = databaseName;
            Datacenter = datacenter;
            Endpoint = endpoint;
            Engine = engine;
            Id = id;
            MemorySizeMb = memorySizeMb;
            MonthlyCost = monthlyCost;
            Name = name;
            Port = port;
            ResourceProfile = resourceProfile;
            Status = status;
            StorageSizeGb = storageSizeGb;
            Username = username;
            Version = version;
        }
    }
}
