// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DanubeData.DanubeData.Outputs
{

    [OutputType]
    public sealed class GetDatabaseProvidersProviderResult
    {
        /// <summary>
        /// Default port number.
        /// </summary>
        public readonly int DefaultPort;
        /// <summary>
        /// Provider description.
        /// </summary>
        public readonly string Description;
        /// <summary>
        /// The provider ID.
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// Provider name (e.g., "MySQL", "PostgreSQL", "MariaDB").
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Provider type identifier.
        /// </summary>
        public readonly string Type;
        /// <summary>
        /// Default version.
        /// </summary>
        public readonly string Version;

        [OutputConstructor]
        private GetDatabaseProvidersProviderResult(
            int defaultPort,

            string description,

            int id,

            string name,

            string type,

            string version)
        {
            DefaultPort = defaultPort;
            Description = description;
            Id = id;
            Name = name;
            Type = type;
            Version = version;
        }
    }
}
