// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DanubeData.DanubeData.Outputs
{

    [OutputType]
    public sealed class GetServerlessContainersContainerResult
    {
        /// <summary>
        /// Timestamp when the container was created.
        /// </summary>
        public readonly string CreatedAt;
        /// <summary>
        /// Deployment type (docker or git).
        /// </summary>
        public readonly string DeploymentType;
        /// <summary>
        /// Git branch (for git deployment).
        /// </summary>
        public readonly string GitBranch;
        /// <summary>
        /// Git repository URL (for git deployment).
        /// </summary>
        public readonly string GitRepository;
        /// <summary>
        /// Unique identifier for the container.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Docker image URL (for docker deployment).
        /// </summary>
        public readonly string ImageUrl;
        /// <summary>
        /// Maximum number of instances.
        /// </summary>
        public readonly int MaxInstances;
        /// <summary>
        /// Minimum number of instances (0 = scale to zero).
        /// </summary>
        public readonly int MinInstances;
        /// <summary>
        /// Name of the container.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Container port.
        /// </summary>
        public readonly int Port;
        /// <summary>
        /// Current status (creating, building, running, error).
        /// </summary>
        public readonly string Status;
        /// <summary>
        /// Public HTTPS URL for the container.
        /// </summary>
        public readonly string Url;

        [OutputConstructor]
        private GetServerlessContainersContainerResult(
            string createdAt,

            string deploymentType,

            string gitBranch,

            string gitRepository,

            string id,

            string imageUrl,

            int maxInstances,

            int minInstances,

            string name,

            int port,

            string status,

            string url)
        {
            CreatedAt = createdAt;
            DeploymentType = deploymentType;
            GitBranch = gitBranch;
            GitRepository = gitRepository;
            Id = id;
            ImageUrl = imageUrl;
            MaxInstances = maxInstances;
            MinInstances = minInstances;
            Name = name;
            Port = port;
            Status = status;
            Url = url;
        }
    }
}
