// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DanubeData.DanubeData.Outputs
{

    [OutputType]
    public sealed class GetStorageAccessKeysKeyResult
    {
        /// <summary>
        /// The S3 access key ID for authentication.
        /// </summary>
        public readonly string AccessKeyId;
        /// <summary>
        /// Access type (full or restricted).
        /// </summary>
        public readonly string AccessType;
        /// <summary>
        /// Timestamp when the key was created.
        /// </summary>
        public readonly string CreatedAt;
        /// <summary>
        /// Expiration timestamp (if set).
        /// </summary>
        public readonly string ExpiresAt;
        /// <summary>
        /// Unique identifier for the access key.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Whether the key has expired.
        /// </summary>
        public readonly bool IsExpired;
        /// <summary>
        /// Whether the key is scoped to specific bucket prefixes.
        /// </summary>
        public readonly bool IsPrefixScoped;
        /// <summary>
        /// Timestamp when the key was last used.
        /// </summary>
        public readonly string LastUsedAt;
        /// <summary>
        /// Name of the access key.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Current status (active, revoked).
        /// </summary>
        public readonly string Status;

        [OutputConstructor]
        private GetStorageAccessKeysKeyResult(
            string accessKeyId,

            string accessType,

            string createdAt,

            string expiresAt,

            string id,

            bool isExpired,

            bool isPrefixScoped,

            string lastUsedAt,

            string name,

            string status)
        {
            AccessKeyId = accessKeyId;
            AccessType = accessType;
            CreatedAt = createdAt;
            ExpiresAt = expiresAt;
            Id = id;
            IsExpired = isExpired;
            IsPrefixScoped = isPrefixScoped;
            LastUsedAt = lastUsedAt;
            Name = name;
            Status = status;
        }
    }
}
