// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DanubeData.DanubeData.Outputs
{

    [OutputType]
    public sealed class GetSshKeysKeyResult
    {
        /// <summary>
        /// Creation timestamp.
        /// </summary>
        public readonly string CreatedAt;
        /// <summary>
        /// SSH key fingerprint.
        /// </summary>
        public readonly string Fingerprint;
        /// <summary>
        /// The SSH key ID.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Name of the key.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The public key content.
        /// </summary>
        public readonly string PublicKey;

        [OutputConstructor]
        private GetSshKeysKeyResult(
            string createdAt,

            string fingerprint,

            string id,

            string name,

            string publicKey)
        {
            CreatedAt = createdAt;
            Fingerprint = fingerprint;
            Id = id;
            Name = name;
            PublicKey = publicKey;
        }
    }
}
