// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DanubeData.DanubeData.Outputs
{

    [OutputType]
    public sealed class GetVpsImagesImageResult
    {
        /// <summary>
        /// Default SSH user for this image.
        /// </summary>
        public readonly string DefaultUser;
        /// <summary>
        /// Image description.
        /// </summary>
        public readonly string Description;
        /// <summary>
        /// Distribution name (e.g., `ubuntu`, `debian`, `almalinux`).
        /// </summary>
        public readonly string Distro;
        /// <summary>
        /// Image family (if applicable).
        /// </summary>
        public readonly string Family;
        /// <summary>
        /// The image ID.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Image identifier used when creating VPS.
        /// </summary>
        public readonly string Image;
        /// <summary>
        /// Human-readable label.
        /// </summary>
        public readonly string Label;
        /// <summary>
        /// Distribution version.
        /// </summary>
        public readonly string Version;

        [OutputConstructor]
        private GetVpsImagesImageResult(
            string defaultUser,

            string description,

            string distro,

            string family,

            string id,

            string image,

            string label,

            string version)
        {
            DefaultUser = defaultUser;
            Description = description;
            Distro = distro;
            Family = family;
            Id = id;
            Image = image;
            Label = label;
            Version = version;
        }
    }
}
