// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DanubeData.DanubeData.Outputs
{

    [OutputType]
    public sealed class GetVpsSnapshotsSnapshotResult
    {
        /// <summary>
        /// Timestamp when the snapshot was created.
        /// </summary>
        public readonly string CreatedAt;
        /// <summary>
        /// Description of the snapshot.
        /// </summary>
        public readonly string Description;
        /// <summary>
        /// Unique identifier for the snapshot.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Name of the snapshot.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Size of the snapshot in GB.
        /// </summary>
        public readonly double SizeGb;
        /// <summary>
        /// Current status (creating, ready, error).
        /// </summary>
        public readonly string Status;
        /// <summary>
        /// ID of the VPS instance this snapshot belongs to.
        /// </summary>
        public readonly string VpsInstanceId;

        [OutputConstructor]
        private GetVpsSnapshotsSnapshotResult(
            string createdAt,

            string description,

            string id,

            string name,

            double sizeGb,

            string status,

            string vpsInstanceId)
        {
            CreatedAt = createdAt;
            Description = description;
            Id = id;
            Name = name;
            SizeGb = sizeGb;
            Status = status;
            VpsInstanceId = vpsInstanceId;
        }
    }
}
