// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DanubeData.DanubeData.Outputs
{

    [OutputType]
    public sealed class GetVpssInstanceResult
    {
        /// <summary>
        /// CPU allocation type (shared or dedicated).
        /// </summary>
        public readonly string CpuAllocationType;
        /// <summary>
        /// Number of CPU cores.
        /// </summary>
        public readonly int CpuCores;
        /// <summary>
        /// Timestamp when the instance was created.
        /// </summary>
        public readonly string CreatedAt;
        /// <summary>
        /// Datacenter location.
        /// </summary>
        public readonly string Datacenter;
        /// <summary>
        /// Unique identifier for the VPS instance.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Operating system image.
        /// </summary>
        public readonly string Image;
        /// <summary>
        /// IPv6 address (if enabled).
        /// </summary>
        public readonly string Ipv6Address;
        /// <summary>
        /// Memory size in GB.
        /// </summary>
        public readonly int MemorySizeGb;
        /// <summary>
        /// Estimated monthly cost.
        /// </summary>
        public readonly double MonthlyCost;
        /// <summary>
        /// Name of the VPS instance.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Private IP address (if assigned).
        /// </summary>
        public readonly string PrivateIp;
        /// <summary>
        /// Public IPv4 address (if assigned).
        /// </summary>
        public readonly string PublicIp;
        /// <summary>
        /// Resource profile (predefined CPU/RAM/Storage configuration).
        /// </summary>
        public readonly string ResourceProfile;
        /// <summary>
        /// Current status (creating, running, stopped, error).
        /// </summary>
        public readonly string Status;
        /// <summary>
        /// Storage size in GB.
        /// </summary>
        public readonly int StorageSizeGb;

        [OutputConstructor]
        private GetVpssInstanceResult(
            string cpuAllocationType,

            int cpuCores,

            string createdAt,

            string datacenter,

            string id,

            string image,

            string ipv6Address,

            int memorySizeGb,

            double monthlyCost,

            string name,

            string privateIp,

            string publicIp,

            string resourceProfile,

            string status,

            int storageSizeGb)
        {
            CpuAllocationType = cpuAllocationType;
            CpuCores = cpuCores;
            CreatedAt = createdAt;
            Datacenter = datacenter;
            Id = id;
            Image = image;
            Ipv6Address = ipv6Address;
            MemorySizeGb = memorySizeGb;
            MonthlyCost = monthlyCost;
            Name = name;
            PrivateIp = privateIp;
            PublicIp = publicIp;
            ResourceProfile = resourceProfile;
            Status = status;
            StorageSizeGb = storageSizeGb;
        }
    }
}
