// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DanubeData.DanubeData.Outputs
{

    [OutputType]
    public sealed class VpsSnapshotTimeouts
    {
        /// <summary>
        /// Time to wait for snapshot creation.
        /// </summary>
        public readonly string? Create;
        /// <summary>
        /// Time to wait for snapshot deletion.
        /// </summary>
        public readonly string? Delete;

        [OutputConstructor]
        private VpsSnapshotTimeouts(
            string? create,

            string? delete)
        {
            Create = create;
            Delete = delete;
        }
    }
}
