# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetCachesResult',
    'AwaitableGetCachesResult',
    'get_caches',
    'get_caches_output',
]

@pulumi.output_type
class GetCachesResult:
    """
    A collection of values returned by getCaches.
    """
    def __init__(__self__, id=None, instances=None):
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if instances and not isinstance(instances, list):
            raise TypeError("Expected argument 'instances' to be a list")
        pulumi.set(__self__, "instances", instances)

    @property
    @pulumi.getter
    def id(self) -> str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @property
    @pulumi.getter
    def instances(self) -> Sequence['outputs.GetCachesInstanceResult']:
        return pulumi.get(self, "instances")


class AwaitableGetCachesResult(GetCachesResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetCachesResult(
            id=self.id,
            instances=self.instances)


def get_caches(opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetCachesResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('danubedata:index/getCaches:getCaches', __args__, opts=opts, typ=GetCachesResult).value

    return AwaitableGetCachesResult(
        id=pulumi.get(__ret__, 'id'),
        instances=pulumi.get(__ret__, 'instances'))
def get_caches_output(opts: Optional[pulumi.InvokeOptions] = None) -> pulumi.Output[GetCachesResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('danubedata:index/getCaches:getCaches', __args__, opts=opts, typ=GetCachesResult)
    return __ret__.apply(lambda __response__: GetCachesResult(
        id=pulumi.get(__response__, 'id'),
        instances=pulumi.get(__response__, 'instances')))
