# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetVpsSnapshotsResult',
    'AwaitableGetVpsSnapshotsResult',
    'get_vps_snapshots',
    'get_vps_snapshots_output',
]

@pulumi.output_type
class GetVpsSnapshotsResult:
    """
    A collection of values returned by getVpsSnapshots.
    """
    def __init__(__self__, id=None, snapshots=None):
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if snapshots and not isinstance(snapshots, list):
            raise TypeError("Expected argument 'snapshots' to be a list")
        pulumi.set(__self__, "snapshots", snapshots)

    @property
    @pulumi.getter
    def id(self) -> str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @property
    @pulumi.getter
    def snapshots(self) -> Sequence['outputs.GetVpsSnapshotsSnapshotResult']:
        return pulumi.get(self, "snapshots")


class AwaitableGetVpsSnapshotsResult(GetVpsSnapshotsResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetVpsSnapshotsResult(
            id=self.id,
            snapshots=self.snapshots)


def get_vps_snapshots(opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetVpsSnapshotsResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('danubedata:index/getVpsSnapshots:getVpsSnapshots', __args__, opts=opts, typ=GetVpsSnapshotsResult).value

    return AwaitableGetVpsSnapshotsResult(
        id=pulumi.get(__ret__, 'id'),
        snapshots=pulumi.get(__ret__, 'snapshots'))
def get_vps_snapshots_output(opts: Optional[pulumi.InvokeOptions] = None) -> pulumi.Output[GetVpsSnapshotsResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('danubedata:index/getVpsSnapshots:getVpsSnapshots', __args__, opts=opts, typ=GetVpsSnapshotsResult)
    return __ret__.apply(lambda __response__: GetVpsSnapshotsResult(
        id=pulumi.get(__response__, 'id'),
        snapshots=pulumi.get(__response__, 'snapshots')))
