# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetStorageAccessKeysResult',
    'AwaitableGetStorageAccessKeysResult',
    'get_storage_access_keys',
    'get_storage_access_keys_output',
]

@pulumi.output_type
class GetStorageAccessKeysResult:
    """
    A collection of values returned by getStorageAccessKeys.
    """
    def __init__(__self__, id=None, keys=None):
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if keys and not isinstance(keys, list):
            raise TypeError("Expected argument 'keys' to be a list")
        pulumi.set(__self__, "keys", keys)

    @property
    @pulumi.getter
    def id(self) -> str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @property
    @pulumi.getter
    def keys(self) -> Sequence['outputs.GetStorageAccessKeysKeyResult']:
        return pulumi.get(self, "keys")


class AwaitableGetStorageAccessKeysResult(GetStorageAccessKeysResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetStorageAccessKeysResult(
            id=self.id,
            keys=self.keys)


def get_storage_access_keys(opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetStorageAccessKeysResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('danubedata:index/getStorageAccessKeys:getStorageAccessKeys', __args__, opts=opts, typ=GetStorageAccessKeysResult).value

    return AwaitableGetStorageAccessKeysResult(
        id=pulumi.get(__ret__, 'id'),
        keys=pulumi.get(__ret__, 'keys'))
def get_storage_access_keys_output(opts: Optional[pulumi.InvokeOptions] = None) -> pulumi.Output[GetStorageAccessKeysResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('danubedata:index/getStorageAccessKeys:getStorageAccessKeys', __args__, opts=opts, typ=GetStorageAccessKeysResult)
    return __ret__.apply(lambda __response__: GetStorageAccessKeysResult(
        id=pulumi.get(__response__, 'id'),
        keys=pulumi.get(__response__, 'keys')))
