# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetVpsImagesResult',
    'AwaitableGetVpsImagesResult',
    'get_vps_images',
    'get_vps_images_output',
]

@pulumi.output_type
class GetVpsImagesResult:
    """
    A collection of values returned by getVpsImages.
    """
    def __init__(__self__, id=None, images=None):
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if images and not isinstance(images, list):
            raise TypeError("Expected argument 'images' to be a list")
        pulumi.set(__self__, "images", images)

    @property
    @pulumi.getter
    def id(self) -> str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @property
    @pulumi.getter
    def images(self) -> Sequence['outputs.GetVpsImagesImageResult']:
        return pulumi.get(self, "images")


class AwaitableGetVpsImagesResult(GetVpsImagesResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetVpsImagesResult(
            id=self.id,
            images=self.images)


def get_vps_images(opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetVpsImagesResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('danubedata:index/getVpsImages:getVpsImages', __args__, opts=opts, typ=GetVpsImagesResult).value

    return AwaitableGetVpsImagesResult(
        id=pulumi.get(__ret__, 'id'),
        images=pulumi.get(__ret__, 'images'))
def get_vps_images_output(opts: Optional[pulumi.InvokeOptions] = None) -> pulumi.Output[GetVpsImagesResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('danubedata:index/getVpsImages:getVpsImages', __args__, opts=opts, typ=GetVpsImagesResult)
    return __ret__.apply(lambda __response__: GetVpsImagesResult(
        id=pulumi.get(__response__, 'id'),
        images=pulumi.get(__response__, 'images')))
