// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface CacheTimeouts {
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
     */
    create?: string;
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
     */
    delete?: string;
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
     */
    update?: string;
}

export interface DatabaseTimeouts {
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
     */
    create?: string;
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
     */
    delete?: string;
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
     */
    update?: string;
}

export interface FirewallRule {
    /**
     * Action to take: 'accept' or 'drop'.
     */
    action: string;
    /**
     * Direction: 'inbound' or 'outbound'.
     */
    direction: string;
    /**
     * Rule ID (computed by API).
     */
    id: string;
    /**
     * Name/description of the rule.
     */
    name?: string;
    /**
     * End of port range (1-65535).
     */
    portRangeEnd?: number;
    /**
     * Start of port range (1-65535).
     */
    portRangeStart?: number;
    /**
     * Rule priority (lower numbers = higher priority).
     */
    priority?: number;
    /**
     * Protocol: 'tcp', 'udp', 'icmp', or 'any'.
     */
    protocol: string;
    /**
     * List of source IP addresses or CIDR blocks.
     */
    sourceIps?: string[];
}

export interface GetCacheProvidersProvider {
    /**
     * Default port number.
     */
    defaultPort: number;
    /**
     * Provider description.
     */
    description: string;
    /**
     * Provider ID to use when creating cache instances.
     */
    id: number;
    /**
     * Provider name (Redis, Valkey, Dragonfly).
     */
    name: string;
    /**
     * Provider type identifier.
     */
    type: string;
    /**
     * Default version.
     */
    version: string;
}

export interface GetCachesInstance {
    /**
     * Cache provider (redis, valkey, dragonfly).
     */
    cacheProvider: string;
    /**
     * Number of CPU cores.
     */
    cpuCores: number;
    /**
     * Timestamp when the instance was created.
     */
    createdAt: string;
    /**
     * Datacenter location.
     */
    datacenter: string;
    /**
     * Connection endpoint hostname.
     */
    endpoint: string;
    /**
     * Unique identifier for the cache instance.
     */
    id: string;
    /**
     * Memory size in MB.
     */
    memorySizeMb: number;
    /**
     * Estimated monthly cost.
     */
    monthlyCost: number;
    /**
     * Name of the cache instance.
     */
    name: string;
    /**
     * Connection port.
     */
    port: number;
    /**
     * Resource profile (predefined CPU/RAM configuration).
     */
    resourceProfile: string;
    /**
     * Current status of the cache instance.
     */
    status: string;
    /**
     * Cache version.
     */
    version: string;
}

export interface GetDatabaseProvidersProvider {
    /**
     * Default port number.
     */
    defaultPort: number;
    /**
     * Provider description.
     */
    description: string;
    /**
     * Provider ID to use when creating database instances.
     */
    id: number;
    /**
     * Provider name (MySQL, PostgreSQL, MariaDB).
     */
    name: string;
    /**
     * Provider type identifier.
     */
    type: string;
    /**
     * Default version.
     */
    version: string;
}

export interface GetDatabasesInstance {
    /**
     * Number of CPU cores.
     */
    cpuCores: number;
    /**
     * Timestamp when the instance was created.
     */
    createdAt: string;
    /**
     * Name of the database.
     */
    databaseName: string;
    /**
     * Datacenter location.
     */
    datacenter: string;
    /**
     * Connection endpoint hostname.
     */
    endpoint: string;
    /**
     * Database engine (mysql, postgresql, mariadb).
     */
    engine: string;
    /**
     * Unique identifier for the database instance.
     */
    id: string;
    /**
     * Memory size in MB.
     */
    memorySizeMb: number;
    /**
     * Estimated monthly cost.
     */
    monthlyCost: number;
    /**
     * Name of the database instance.
     */
    name: string;
    /**
     * Connection port.
     */
    port: number;
    /**
     * Resource profile (predefined CPU/RAM/Storage configuration).
     */
    resourceProfile: string;
    /**
     * Current status of the database instance.
     */
    status: string;
    /**
     * Storage size in GB.
     */
    storageSizeGb: number;
    /**
     * Database admin username.
     */
    username: string;
    /**
     * Database version.
     */
    version: string;
}

export interface GetFirewallsFirewall {
    /**
     * Timestamp when the firewall was created.
     */
    createdAt: string;
    /**
     * Default action for unmatched traffic (allow or deny).
     */
    defaultAction: string;
    /**
     * Description of the firewall.
     */
    description: string;
    /**
     * Unique identifier for the firewall.
     */
    id: string;
    /**
     * Whether this is the default firewall.
     */
    isDefault: boolean;
    /**
     * Name of the firewall.
     */
    name: string;
    /**
     * Number of rules in the firewall.
     */
    rulesCount: number;
    /**
     * Current status of the firewall.
     */
    status: string;
}

export interface GetServerlessContainersContainer {
    /**
     * Timestamp when the container was created.
     */
    createdAt: string;
    /**
     * Deployment type (docker or git).
     */
    deploymentType: string;
    /**
     * Git branch (for git deployment).
     */
    gitBranch: string;
    /**
     * Git repository URL (for git deployment).
     */
    gitRepository: string;
    /**
     * Unique identifier for the serverless container.
     */
    id: string;
    /**
     * Docker image URL (for docker deployment).
     */
    imageUrl: string;
    /**
     * Maximum number of instances.
     */
    maxInstances: number;
    /**
     * Minimum number of instances.
     */
    minInstances: number;
    /**
     * Name of the serverless container.
     */
    name: string;
    /**
     * Container port.
     */
    port: number;
    /**
     * Current status of the container.
     */
    status: string;
    /**
     * Public HTTPS URL for the container.
     */
    url: string;
}

export interface GetSshKeysKey {
    /**
     * Timestamp when the key was created.
     */
    createdAt: string;
    /**
     * SHA256 fingerprint of the SSH key.
     */
    fingerprint: string;
    /**
     * Unique identifier for the SSH key.
     */
    id: string;
    /**
     * Name of the SSH key.
     */
    name: string;
    /**
     * The SSH public key.
     */
    publicKey: string;
}

export interface GetStorageAccessKeysKey {
    /**
     * The S3 access key ID for authentication.
     */
    accessKeyId: string;
    /**
     * Access type (full or restricted).
     */
    accessType: string;
    /**
     * Timestamp when the key was created.
     */
    createdAt: string;
    /**
     * Expiration timestamp (if set).
     */
    expiresAt: string;
    /**
     * Unique identifier for the access key.
     */
    id: string;
    /**
     * Whether the key has expired.
     */
    isExpired: boolean;
    /**
     * Whether the key is scoped to specific bucket prefixes.
     */
    isPrefixScoped: boolean;
    /**
     * Timestamp when the key was last used.
     */
    lastUsedAt: string;
    /**
     * Name of the access key.
     */
    name: string;
    /**
     * Current status of the key.
     */
    status: string;
}

export interface GetStorageBucketsBucket {
    /**
     * Timestamp when the bucket was created.
     */
    createdAt: string;
    /**
     * Human-readable display name.
     */
    displayName: string;
    /**
     * Whether encryption is enabled.
     */
    encryptionEnabled: boolean;
    /**
     * S3-compatible endpoint URL.
     */
    endpointUrl: string;
    /**
     * Unique identifier for the storage bucket.
     */
    id: string;
    /**
     * Internal bucket name.
     */
    minioBucketName: string;
    /**
     * Estimated monthly cost.
     */
    monthlyCost: number;
    /**
     * Name of the storage bucket.
     */
    name: string;
    /**
     * Number of objects in the bucket.
     */
    objectCount: number;
    /**
     * Whether public access is enabled.
     */
    publicAccess: boolean;
    /**
     * Public URL (if public access enabled).
     */
    publicUrl: string;
    /**
     * Region where the bucket is located.
     */
    region: string;
    /**
     * Current size in bytes.
     */
    sizeBytes: number;
    /**
     * Current status of the bucket.
     */
    status: string;
    /**
     * Whether versioning is enabled.
     */
    versioningEnabled: boolean;
}

export interface GetVpsImagesImage {
    /**
     * Default SSH user.
     */
    defaultUser: string;
    /**
     * Image description.
     */
    description: string;
    /**
     * Distribution (ubuntu, debian, alma, rocky, fedora, alpine).
     */
    distro: string;
    /**
     * OS family (debian, redhat, fedora, alpine).
     */
    family: string;
    /**
     * Image identifier (e.g., 'ubuntu-24.04').
     */
    id: string;
    /**
     * Full image reference.
     */
    image: string;
    /**
     * Human-readable label.
     */
    label: string;
    /**
     * Distribution version.
     */
    version: string;
}

export interface GetVpsSnapshotsSnapshot {
    /**
     * Timestamp when the snapshot was created.
     */
    createdAt: string;
    /**
     * Description of the snapshot.
     */
    description: string;
    /**
     * Unique identifier for the snapshot.
     */
    id: string;
    /**
     * Name of the snapshot.
     */
    name: string;
    /**
     * Size of the snapshot in GB.
     */
    sizeGb: number;
    /**
     * Current status of the snapshot (creating, ready, error).
     */
    status: string;
    /**
     * ID of the VPS instance this snapshot belongs to.
     */
    vpsInstanceId: string;
}

export interface GetVpssInstance {
    /**
     * CPU allocation type (shared or dedicated).
     */
    cpuAllocationType: string;
    /**
     * Number of CPU cores.
     */
    cpuCores: number;
    /**
     * Timestamp when the instance was created.
     */
    createdAt: string;
    /**
     * Datacenter location.
     */
    datacenter: string;
    /**
     * Unique identifier for the VPS instance.
     */
    id: string;
    /**
     * Operating system image.
     */
    image: string;
    /**
     * IPv6 address.
     */
    ipv6Address: string;
    /**
     * Memory size in GB.
     */
    memorySizeGb: number;
    /**
     * Estimated monthly cost.
     */
    monthlyCost: number;
    /**
     * Name of the VPS instance.
     */
    name: string;
    /**
     * Private IP address.
     */
    privateIp: string;
    /**
     * Public IPv4 address.
     */
    publicIp: string;
    /**
     * Resource profile (predefined CPU/RAM/Storage configuration).
     */
    resourceProfile: string;
    /**
     * Current status of the VPS instance.
     */
    status: string;
    /**
     * Storage size in GB.
     */
    storageSizeGb: number;
}

export interface ServerlessTimeouts {
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
     */
    create?: string;
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
     */
    delete?: string;
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
     */
    update?: string;
}

export interface StorageBucketTimeouts {
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
     */
    create?: string;
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
     */
    delete?: string;
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
     */
    update?: string;
}

export interface VpsSnapshotTimeouts {
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
     */
    create?: string;
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
     */
    delete?: string;
}

export interface VpsTimeouts {
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
     */
    create?: string;
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
     */
    delete?: string;
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
     */
    update?: string;
}

