// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DanubeData.DanubeData.Inputs
{

    public sealed class VpsSnapshotTimeoutsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Time to wait for snapshot creation.
        /// </summary>
        [Input("create")]
        public Input<string>? Create { get; set; }

        /// <summary>
        /// Time to wait for snapshot deletion.
        /// </summary>
        [Input("delete")]
        public Input<string>? Delete { get; set; }

        public VpsSnapshotTimeoutsArgs()
        {
        }
        public static new VpsSnapshotTimeoutsArgs Empty => new VpsSnapshotTimeoutsArgs();
    }
}
