// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DanubeData.DanubeData.Inputs
{

    public sealed class VpsTimeoutsGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Time to wait for VPS creation.
        /// </summary>
        [Input("create")]
        public Input<string>? Create { get; set; }

        /// <summary>
        /// Time to wait for VPS deletion.
        /// </summary>
        [Input("delete")]
        public Input<string>? Delete { get; set; }

        /// <summary>
        /// Time to wait for VPS updates.
        /// </summary>
        [Input("update")]
        public Input<string>? Update { get; set; }

        public VpsTimeoutsGetArgs()
        {
        }
        public static new VpsTimeoutsGetArgs Empty => new VpsTimeoutsGetArgs();
    }
}
