// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package danubedata

import (
	"context"
	"reflect"

	"errors"
	"github.com/AdrianSilaghi/pulumi-danubedata/sdk/go/danubedata/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// ## # Cache
//
// Manages an in-memory cache instance (Redis, Valkey, or Dragonfly).
//
// ## Example Usage
//
// ### Redis Cache
//
// ```go
// package main
//
// import (
//
//	"github.com/AdrianSilaghi/pulumi-danubedata/sdk/go/danubedata"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			redis, err := danubedata.NewCache(ctx, "redis", &danubedata.CacheArgs{
//				CacheProvider: pulumi.String("redis"),
//				MemorySizeMb:  pulumi.Int(512),
//				CpuCores:      pulumi.Int(1),
//				Datacenter:    pulumi.String("fsn1"),
//				Version:       pulumi.String("7.2"),
//			})
//			if err != nil {
//				return err
//			}
//			ctx.Export("redisEndpoint", redis.Endpoint)
//			return nil
//		})
//	}
//
// ```
//
// ### Valkey Cache (Redis Fork)
//
// ```go
// package main
//
// import (
//
//	"github.com/AdrianSilaghi/pulumi-danubedata/sdk/go/danubedata"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := danubedata.NewCache(ctx, "valkey", &danubedata.CacheArgs{
//				CacheProvider: pulumi.String("valkey"),
//				CpuCores:      pulumi.Int(2),
//				Datacenter:    pulumi.String("fsn1"),
//				MemorySizeMb:  pulumi.Int(1024),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ### Dragonfly Cache (High Performance)
//
// ```go
// package main
//
// import (
//
//	"github.com/AdrianSilaghi/pulumi-danubedata/sdk/go/danubedata"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := danubedata.NewCache(ctx, "dragonfly", &danubedata.CacheArgs{
//				CacheProvider: pulumi.String("dragonfly"),
//				CpuCores:      pulumi.Int(4),
//				Datacenter:    pulumi.String("fsn1"),
//				MemorySizeMb:  pulumi.Int(2048),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ### Using Resource Profile
//
// ```go
// package main
//
// import (
//
//	"github.com/AdrianSilaghi/pulumi-danubedata/sdk/go/danubedata"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := danubedata.NewCache(ctx, "standard", &danubedata.CacheArgs{
//				ResourceProfile: pulumi.String("cache-medium"),
//				Datacenter:      pulumi.String("fsn1"),
//			}, pulumi.Provider("redis"))
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// Cache instances can be imported using their ID:
//
// bash
//
// ```sh
// $ pulumi import danubedata:index/cache:Cache example cache-abc123
// ```
type Cache struct {
	pulumi.CustomResourceState

	// Cache provider type (redis, valkey, dragonfly).
	CacheProvider pulumi.StringOutput `pulumi:"cacheProvider"`
	// Number of CPU cores. If not specified, determined by resource_profile.
	CpuCores pulumi.IntOutput `pulumi:"cpuCores"`
	// Creation timestamp.
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// Datacenter location (ash, fsn1, nbg1, hel1).
	Datacenter pulumi.StringOutput `pulumi:"datacenter"`
	// Deployment timestamp.
	DeployedAt pulumi.StringOutput `pulumi:"deployedAt"`
	// Connection endpoint hostname.
	Endpoint pulumi.StringOutput `pulumi:"endpoint"`
	// Memory size in MB. If not specified, determined by resource_profile.
	MemorySizeMb pulumi.IntOutput `pulumi:"memorySizeMb"`
	// Estimated monthly cost.
	MonthlyCost pulumi.Float64Output `pulumi:"monthlyCost"`
	// Monthly cost in cents.
	MonthlyCostCents pulumi.IntOutput `pulumi:"monthlyCostCents"`
	// Name of the cache instance.
	Name pulumi.StringOutput `pulumi:"name"`
	// ID of the parameter group to use for custom configuration.
	ParameterGroupId pulumi.StringPtrOutput `pulumi:"parameterGroupId"`
	// Connection port.
	Port pulumi.IntOutput `pulumi:"port"`
	// Resource profile for the cache (micro, small, medium, large).
	ResourceProfile pulumi.StringOutput `pulumi:"resourceProfile"`
	// Current status.
	Status   pulumi.StringOutput    `pulumi:"status"`
	Timeouts CacheTimeoutsPtrOutput `pulumi:"timeouts"`
	// Timestamp when the cache instance was last updated.
	UpdatedAt pulumi.StringOutput `pulumi:"updatedAt"`
	// Version of the cache software.
	Version pulumi.StringOutput `pulumi:"version"`
}

// NewCache registers a new resource with the given unique name, arguments, and options.
func NewCache(ctx *pulumi.Context,
	name string, args *CacheArgs, opts ...pulumi.ResourceOption) (*Cache, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.CacheProvider == nil {
		return nil, errors.New("invalid value for required argument 'CacheProvider'")
	}
	if args.Datacenter == nil {
		return nil, errors.New("invalid value for required argument 'Datacenter'")
	}
	if args.ResourceProfile == nil {
		return nil, errors.New("invalid value for required argument 'ResourceProfile'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Cache
	err := ctx.RegisterResource("danubedata:index/cache:Cache", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetCache gets an existing Cache resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetCache(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *CacheState, opts ...pulumi.ResourceOption) (*Cache, error) {
	var resource Cache
	err := ctx.ReadResource("danubedata:index/cache:Cache", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Cache resources.
type cacheState struct {
	// Cache provider type (redis, valkey, dragonfly).
	CacheProvider *string `pulumi:"cacheProvider"`
	// Number of CPU cores. If not specified, determined by resource_profile.
	CpuCores *int `pulumi:"cpuCores"`
	// Creation timestamp.
	CreatedAt *string `pulumi:"createdAt"`
	// Datacenter location (ash, fsn1, nbg1, hel1).
	Datacenter *string `pulumi:"datacenter"`
	// Deployment timestamp.
	DeployedAt *string `pulumi:"deployedAt"`
	// Connection endpoint hostname.
	Endpoint *string `pulumi:"endpoint"`
	// Memory size in MB. If not specified, determined by resource_profile.
	MemorySizeMb *int `pulumi:"memorySizeMb"`
	// Estimated monthly cost.
	MonthlyCost *float64 `pulumi:"monthlyCost"`
	// Monthly cost in cents.
	MonthlyCostCents *int `pulumi:"monthlyCostCents"`
	// Name of the cache instance.
	Name *string `pulumi:"name"`
	// ID of the parameter group to use for custom configuration.
	ParameterGroupId *string `pulumi:"parameterGroupId"`
	// Connection port.
	Port *int `pulumi:"port"`
	// Resource profile for the cache (micro, small, medium, large).
	ResourceProfile *string `pulumi:"resourceProfile"`
	// Current status.
	Status   *string        `pulumi:"status"`
	Timeouts *CacheTimeouts `pulumi:"timeouts"`
	// Timestamp when the cache instance was last updated.
	UpdatedAt *string `pulumi:"updatedAt"`
	// Version of the cache software.
	Version *string `pulumi:"version"`
}

type CacheState struct {
	// Cache provider type (redis, valkey, dragonfly).
	CacheProvider pulumi.StringPtrInput
	// Number of CPU cores. If not specified, determined by resource_profile.
	CpuCores pulumi.IntPtrInput
	// Creation timestamp.
	CreatedAt pulumi.StringPtrInput
	// Datacenter location (ash, fsn1, nbg1, hel1).
	Datacenter pulumi.StringPtrInput
	// Deployment timestamp.
	DeployedAt pulumi.StringPtrInput
	// Connection endpoint hostname.
	Endpoint pulumi.StringPtrInput
	// Memory size in MB. If not specified, determined by resource_profile.
	MemorySizeMb pulumi.IntPtrInput
	// Estimated monthly cost.
	MonthlyCost pulumi.Float64PtrInput
	// Monthly cost in cents.
	MonthlyCostCents pulumi.IntPtrInput
	// Name of the cache instance.
	Name pulumi.StringPtrInput
	// ID of the parameter group to use for custom configuration.
	ParameterGroupId pulumi.StringPtrInput
	// Connection port.
	Port pulumi.IntPtrInput
	// Resource profile for the cache (micro, small, medium, large).
	ResourceProfile pulumi.StringPtrInput
	// Current status.
	Status   pulumi.StringPtrInput
	Timeouts CacheTimeoutsPtrInput
	// Timestamp when the cache instance was last updated.
	UpdatedAt pulumi.StringPtrInput
	// Version of the cache software.
	Version pulumi.StringPtrInput
}

func (CacheState) ElementType() reflect.Type {
	return reflect.TypeOf((*cacheState)(nil)).Elem()
}

type cacheArgs struct {
	// Cache provider type (redis, valkey, dragonfly).
	CacheProvider string `pulumi:"cacheProvider"`
	// Number of CPU cores. If not specified, determined by resource_profile.
	CpuCores *int `pulumi:"cpuCores"`
	// Datacenter location (ash, fsn1, nbg1, hel1).
	Datacenter string `pulumi:"datacenter"`
	// Memory size in MB. If not specified, determined by resource_profile.
	MemorySizeMb *int `pulumi:"memorySizeMb"`
	// Name of the cache instance.
	Name *string `pulumi:"name"`
	// ID of the parameter group to use for custom configuration.
	ParameterGroupId *string `pulumi:"parameterGroupId"`
	// Resource profile for the cache (micro, small, medium, large).
	ResourceProfile string         `pulumi:"resourceProfile"`
	Timeouts        *CacheTimeouts `pulumi:"timeouts"`
	// Version of the cache software.
	Version *string `pulumi:"version"`
}

// The set of arguments for constructing a Cache resource.
type CacheArgs struct {
	// Cache provider type (redis, valkey, dragonfly).
	CacheProvider pulumi.StringInput
	// Number of CPU cores. If not specified, determined by resource_profile.
	CpuCores pulumi.IntPtrInput
	// Datacenter location (ash, fsn1, nbg1, hel1).
	Datacenter pulumi.StringInput
	// Memory size in MB. If not specified, determined by resource_profile.
	MemorySizeMb pulumi.IntPtrInput
	// Name of the cache instance.
	Name pulumi.StringPtrInput
	// ID of the parameter group to use for custom configuration.
	ParameterGroupId pulumi.StringPtrInput
	// Resource profile for the cache (micro, small, medium, large).
	ResourceProfile pulumi.StringInput
	Timeouts        CacheTimeoutsPtrInput
	// Version of the cache software.
	Version pulumi.StringPtrInput
}

func (CacheArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*cacheArgs)(nil)).Elem()
}

type CacheInput interface {
	pulumi.Input

	ToCacheOutput() CacheOutput
	ToCacheOutputWithContext(ctx context.Context) CacheOutput
}

func (*Cache) ElementType() reflect.Type {
	return reflect.TypeOf((**Cache)(nil)).Elem()
}

func (i *Cache) ToCacheOutput() CacheOutput {
	return i.ToCacheOutputWithContext(context.Background())
}

func (i *Cache) ToCacheOutputWithContext(ctx context.Context) CacheOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CacheOutput)
}

// CacheArrayInput is an input type that accepts CacheArray and CacheArrayOutput values.
// You can construct a concrete instance of `CacheArrayInput` via:
//
//	CacheArray{ CacheArgs{...} }
type CacheArrayInput interface {
	pulumi.Input

	ToCacheArrayOutput() CacheArrayOutput
	ToCacheArrayOutputWithContext(context.Context) CacheArrayOutput
}

type CacheArray []CacheInput

func (CacheArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Cache)(nil)).Elem()
}

func (i CacheArray) ToCacheArrayOutput() CacheArrayOutput {
	return i.ToCacheArrayOutputWithContext(context.Background())
}

func (i CacheArray) ToCacheArrayOutputWithContext(ctx context.Context) CacheArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CacheArrayOutput)
}

// CacheMapInput is an input type that accepts CacheMap and CacheMapOutput values.
// You can construct a concrete instance of `CacheMapInput` via:
//
//	CacheMap{ "key": CacheArgs{...} }
type CacheMapInput interface {
	pulumi.Input

	ToCacheMapOutput() CacheMapOutput
	ToCacheMapOutputWithContext(context.Context) CacheMapOutput
}

type CacheMap map[string]CacheInput

func (CacheMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Cache)(nil)).Elem()
}

func (i CacheMap) ToCacheMapOutput() CacheMapOutput {
	return i.ToCacheMapOutputWithContext(context.Background())
}

func (i CacheMap) ToCacheMapOutputWithContext(ctx context.Context) CacheMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CacheMapOutput)
}

type CacheOutput struct{ *pulumi.OutputState }

func (CacheOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Cache)(nil)).Elem()
}

func (o CacheOutput) ToCacheOutput() CacheOutput {
	return o
}

func (o CacheOutput) ToCacheOutputWithContext(ctx context.Context) CacheOutput {
	return o
}

// Cache provider type (redis, valkey, dragonfly).
func (o CacheOutput) CacheProvider() pulumi.StringOutput {
	return o.ApplyT(func(v *Cache) pulumi.StringOutput { return v.CacheProvider }).(pulumi.StringOutput)
}

// Number of CPU cores. If not specified, determined by resource_profile.
func (o CacheOutput) CpuCores() pulumi.IntOutput {
	return o.ApplyT(func(v *Cache) pulumi.IntOutput { return v.CpuCores }).(pulumi.IntOutput)
}

// Creation timestamp.
func (o CacheOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *Cache) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// Datacenter location (ash, fsn1, nbg1, hel1).
func (o CacheOutput) Datacenter() pulumi.StringOutput {
	return o.ApplyT(func(v *Cache) pulumi.StringOutput { return v.Datacenter }).(pulumi.StringOutput)
}

// Deployment timestamp.
func (o CacheOutput) DeployedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *Cache) pulumi.StringOutput { return v.DeployedAt }).(pulumi.StringOutput)
}

// Connection endpoint hostname.
func (o CacheOutput) Endpoint() pulumi.StringOutput {
	return o.ApplyT(func(v *Cache) pulumi.StringOutput { return v.Endpoint }).(pulumi.StringOutput)
}

// Memory size in MB. If not specified, determined by resource_profile.
func (o CacheOutput) MemorySizeMb() pulumi.IntOutput {
	return o.ApplyT(func(v *Cache) pulumi.IntOutput { return v.MemorySizeMb }).(pulumi.IntOutput)
}

// Estimated monthly cost.
func (o CacheOutput) MonthlyCost() pulumi.Float64Output {
	return o.ApplyT(func(v *Cache) pulumi.Float64Output { return v.MonthlyCost }).(pulumi.Float64Output)
}

// Monthly cost in cents.
func (o CacheOutput) MonthlyCostCents() pulumi.IntOutput {
	return o.ApplyT(func(v *Cache) pulumi.IntOutput { return v.MonthlyCostCents }).(pulumi.IntOutput)
}

// Name of the cache instance.
func (o CacheOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Cache) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// ID of the parameter group to use for custom configuration.
func (o CacheOutput) ParameterGroupId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Cache) pulumi.StringPtrOutput { return v.ParameterGroupId }).(pulumi.StringPtrOutput)
}

// Connection port.
func (o CacheOutput) Port() pulumi.IntOutput {
	return o.ApplyT(func(v *Cache) pulumi.IntOutput { return v.Port }).(pulumi.IntOutput)
}

// Resource profile for the cache (micro, small, medium, large).
func (o CacheOutput) ResourceProfile() pulumi.StringOutput {
	return o.ApplyT(func(v *Cache) pulumi.StringOutput { return v.ResourceProfile }).(pulumi.StringOutput)
}

// Current status.
func (o CacheOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v *Cache) pulumi.StringOutput { return v.Status }).(pulumi.StringOutput)
}

func (o CacheOutput) Timeouts() CacheTimeoutsPtrOutput {
	return o.ApplyT(func(v *Cache) CacheTimeoutsPtrOutput { return v.Timeouts }).(CacheTimeoutsPtrOutput)
}

// Timestamp when the cache instance was last updated.
func (o CacheOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *Cache) pulumi.StringOutput { return v.UpdatedAt }).(pulumi.StringOutput)
}

// Version of the cache software.
func (o CacheOutput) Version() pulumi.StringOutput {
	return o.ApplyT(func(v *Cache) pulumi.StringOutput { return v.Version }).(pulumi.StringOutput)
}

type CacheArrayOutput struct{ *pulumi.OutputState }

func (CacheArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Cache)(nil)).Elem()
}

func (o CacheArrayOutput) ToCacheArrayOutput() CacheArrayOutput {
	return o
}

func (o CacheArrayOutput) ToCacheArrayOutputWithContext(ctx context.Context) CacheArrayOutput {
	return o
}

func (o CacheArrayOutput) Index(i pulumi.IntInput) CacheOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Cache {
		return vs[0].([]*Cache)[vs[1].(int)]
	}).(CacheOutput)
}

type CacheMapOutput struct{ *pulumi.OutputState }

func (CacheMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Cache)(nil)).Elem()
}

func (o CacheMapOutput) ToCacheMapOutput() CacheMapOutput {
	return o
}

func (o CacheMapOutput) ToCacheMapOutputWithContext(ctx context.Context) CacheMapOutput {
	return o
}

func (o CacheMapOutput) MapIndex(k pulumi.StringInput) CacheOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Cache {
		return vs[0].(map[string]*Cache)[vs[1].(string)]
	}).(CacheOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*CacheInput)(nil)).Elem(), &Cache{})
	pulumi.RegisterInputType(reflect.TypeOf((*CacheArrayInput)(nil)).Elem(), CacheArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*CacheMapInput)(nil)).Elem(), CacheMap{})
	pulumi.RegisterOutputType(CacheOutput{})
	pulumi.RegisterOutputType(CacheArrayOutput{})
	pulumi.RegisterOutputType(CacheMapOutput{})
}
