// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package danubedata

import (
	"context"
	"reflect"

	"errors"
	"github.com/AdrianSilaghi/pulumi-danubedata/sdk/go/danubedata/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// ## # Database
//
// Manages a managed database instance (MySQL, PostgreSQL, or MariaDB).
//
// ## Example Usage
//
// ### Using Resource Profile
//
// ```go
// package main
//
// import (
//
//	"github.com/AdrianSilaghi/pulumi-danubedata/sdk/go/danubedata"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := danubedata.NewDatabase(ctx, "standard", &danubedata.DatabaseArgs{
//				Datacenter:      pulumi.String("fsn1"),
//				Engine:          pulumi.String("mysql"),
//				ResourceProfile: pulumi.String("db-medium"),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Notes
//
// - Database credentials are managed separately and can be retrieved via the API.
// - Storage size can only be increased, not decreased.
// - Version upgrades may cause brief downtime.
//
// ## Import
//
// Database instances can be imported using their ID:
//
// bash
//
// ```sh
// $ pulumi import danubedata:index/database:Database example db-abc123
// ```
type Database struct {
	pulumi.CustomResourceState

	// Number of CPU cores. Derived from resource_profile.
	CpuCores pulumi.IntOutput `pulumi:"cpuCores"`
	// Creation timestamp.
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// Name of the initial database to create. Must start with a letter and contain only letters, numbers, and underscores.
	DatabaseName pulumi.StringPtrOutput `pulumi:"databaseName"`
	// Datacenter location (fsn1, nbg1, hel1).
	Datacenter pulumi.StringOutput `pulumi:"datacenter"`
	// Deployment timestamp.
	DeployedAt pulumi.StringOutput `pulumi:"deployedAt"`
	// Connection endpoint hostname.
	Endpoint pulumi.StringOutput `pulumi:"endpoint"`
	// Database engine (mysql, postgresql, mariadb).
	Engine pulumi.StringOutput `pulumi:"engine"`
	// Memory size in MB. Derived from resource_profile.
	MemorySizeMb pulumi.IntOutput `pulumi:"memorySizeMb"`
	// Estimated monthly cost.
	MonthlyCost pulumi.Float64Output `pulumi:"monthlyCost"`
	// Monthly cost in cents.
	MonthlyCostCents pulumi.IntOutput `pulumi:"monthlyCostCents"`
	// Name of the database instance. Must be lowercase alphanumeric with hyphens (DNS compatible).
	Name pulumi.StringOutput `pulumi:"name"`
	// ID of the parameter group to use for custom configuration.
	ParameterGroupId pulumi.StringPtrOutput `pulumi:"parameterGroupId"`
	// Connection port.
	Port pulumi.IntOutput `pulumi:"port"`
	// Resource profile for the database (small, medium, large).
	ResourceProfile pulumi.StringOutput `pulumi:"resourceProfile"`
	// Current status.
	Status pulumi.StringOutput `pulumi:"status"`
	// Storage size in GB. Derived from resource_profile.
	StorageSizeGb pulumi.IntOutput          `pulumi:"storageSizeGb"`
	Timeouts      DatabaseTimeoutsPtrOutput `pulumi:"timeouts"`
	// Timestamp when the database instance was last updated.
	UpdatedAt pulumi.StringOutput `pulumi:"updatedAt"`
	// Database admin username.
	Username pulumi.StringOutput `pulumi:"username"`
	// Version of the database software.
	Version pulumi.StringOutput `pulumi:"version"`
}

// NewDatabase registers a new resource with the given unique name, arguments, and options.
func NewDatabase(ctx *pulumi.Context,
	name string, args *DatabaseArgs, opts ...pulumi.ResourceOption) (*Database, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Datacenter == nil {
		return nil, errors.New("invalid value for required argument 'Datacenter'")
	}
	if args.Engine == nil {
		return nil, errors.New("invalid value for required argument 'Engine'")
	}
	if args.ResourceProfile == nil {
		return nil, errors.New("invalid value for required argument 'ResourceProfile'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Database
	err := ctx.RegisterResource("danubedata:index/database:Database", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetDatabase gets an existing Database resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetDatabase(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *DatabaseState, opts ...pulumi.ResourceOption) (*Database, error) {
	var resource Database
	err := ctx.ReadResource("danubedata:index/database:Database", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Database resources.
type databaseState struct {
	// Number of CPU cores. Derived from resource_profile.
	CpuCores *int `pulumi:"cpuCores"`
	// Creation timestamp.
	CreatedAt *string `pulumi:"createdAt"`
	// Name of the initial database to create. Must start with a letter and contain only letters, numbers, and underscores.
	DatabaseName *string `pulumi:"databaseName"`
	// Datacenter location (fsn1, nbg1, hel1).
	Datacenter *string `pulumi:"datacenter"`
	// Deployment timestamp.
	DeployedAt *string `pulumi:"deployedAt"`
	// Connection endpoint hostname.
	Endpoint *string `pulumi:"endpoint"`
	// Database engine (mysql, postgresql, mariadb).
	Engine *string `pulumi:"engine"`
	// Memory size in MB. Derived from resource_profile.
	MemorySizeMb *int `pulumi:"memorySizeMb"`
	// Estimated monthly cost.
	MonthlyCost *float64 `pulumi:"monthlyCost"`
	// Monthly cost in cents.
	MonthlyCostCents *int `pulumi:"monthlyCostCents"`
	// Name of the database instance. Must be lowercase alphanumeric with hyphens (DNS compatible).
	Name *string `pulumi:"name"`
	// ID of the parameter group to use for custom configuration.
	ParameterGroupId *string `pulumi:"parameterGroupId"`
	// Connection port.
	Port *int `pulumi:"port"`
	// Resource profile for the database (small, medium, large).
	ResourceProfile *string `pulumi:"resourceProfile"`
	// Current status.
	Status *string `pulumi:"status"`
	// Storage size in GB. Derived from resource_profile.
	StorageSizeGb *int              `pulumi:"storageSizeGb"`
	Timeouts      *DatabaseTimeouts `pulumi:"timeouts"`
	// Timestamp when the database instance was last updated.
	UpdatedAt *string `pulumi:"updatedAt"`
	// Database admin username.
	Username *string `pulumi:"username"`
	// Version of the database software.
	Version *string `pulumi:"version"`
}

type DatabaseState struct {
	// Number of CPU cores. Derived from resource_profile.
	CpuCores pulumi.IntPtrInput
	// Creation timestamp.
	CreatedAt pulumi.StringPtrInput
	// Name of the initial database to create. Must start with a letter and contain only letters, numbers, and underscores.
	DatabaseName pulumi.StringPtrInput
	// Datacenter location (fsn1, nbg1, hel1).
	Datacenter pulumi.StringPtrInput
	// Deployment timestamp.
	DeployedAt pulumi.StringPtrInput
	// Connection endpoint hostname.
	Endpoint pulumi.StringPtrInput
	// Database engine (mysql, postgresql, mariadb).
	Engine pulumi.StringPtrInput
	// Memory size in MB. Derived from resource_profile.
	MemorySizeMb pulumi.IntPtrInput
	// Estimated monthly cost.
	MonthlyCost pulumi.Float64PtrInput
	// Monthly cost in cents.
	MonthlyCostCents pulumi.IntPtrInput
	// Name of the database instance. Must be lowercase alphanumeric with hyphens (DNS compatible).
	Name pulumi.StringPtrInput
	// ID of the parameter group to use for custom configuration.
	ParameterGroupId pulumi.StringPtrInput
	// Connection port.
	Port pulumi.IntPtrInput
	// Resource profile for the database (small, medium, large).
	ResourceProfile pulumi.StringPtrInput
	// Current status.
	Status pulumi.StringPtrInput
	// Storage size in GB. Derived from resource_profile.
	StorageSizeGb pulumi.IntPtrInput
	Timeouts      DatabaseTimeoutsPtrInput
	// Timestamp when the database instance was last updated.
	UpdatedAt pulumi.StringPtrInput
	// Database admin username.
	Username pulumi.StringPtrInput
	// Version of the database software.
	Version pulumi.StringPtrInput
}

func (DatabaseState) ElementType() reflect.Type {
	return reflect.TypeOf((*databaseState)(nil)).Elem()
}

type databaseArgs struct {
	// Name of the initial database to create. Must start with a letter and contain only letters, numbers, and underscores.
	DatabaseName *string `pulumi:"databaseName"`
	// Datacenter location (fsn1, nbg1, hel1).
	Datacenter string `pulumi:"datacenter"`
	// Database engine (mysql, postgresql, mariadb).
	Engine string `pulumi:"engine"`
	// Name of the database instance. Must be lowercase alphanumeric with hyphens (DNS compatible).
	Name *string `pulumi:"name"`
	// ID of the parameter group to use for custom configuration.
	ParameterGroupId *string `pulumi:"parameterGroupId"`
	// Resource profile for the database (small, medium, large).
	ResourceProfile string            `pulumi:"resourceProfile"`
	Timeouts        *DatabaseTimeouts `pulumi:"timeouts"`
	// Version of the database software.
	Version *string `pulumi:"version"`
}

// The set of arguments for constructing a Database resource.
type DatabaseArgs struct {
	// Name of the initial database to create. Must start with a letter and contain only letters, numbers, and underscores.
	DatabaseName pulumi.StringPtrInput
	// Datacenter location (fsn1, nbg1, hel1).
	Datacenter pulumi.StringInput
	// Database engine (mysql, postgresql, mariadb).
	Engine pulumi.StringInput
	// Name of the database instance. Must be lowercase alphanumeric with hyphens (DNS compatible).
	Name pulumi.StringPtrInput
	// ID of the parameter group to use for custom configuration.
	ParameterGroupId pulumi.StringPtrInput
	// Resource profile for the database (small, medium, large).
	ResourceProfile pulumi.StringInput
	Timeouts        DatabaseTimeoutsPtrInput
	// Version of the database software.
	Version pulumi.StringPtrInput
}

func (DatabaseArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*databaseArgs)(nil)).Elem()
}

type DatabaseInput interface {
	pulumi.Input

	ToDatabaseOutput() DatabaseOutput
	ToDatabaseOutputWithContext(ctx context.Context) DatabaseOutput
}

func (*Database) ElementType() reflect.Type {
	return reflect.TypeOf((**Database)(nil)).Elem()
}

func (i *Database) ToDatabaseOutput() DatabaseOutput {
	return i.ToDatabaseOutputWithContext(context.Background())
}

func (i *Database) ToDatabaseOutputWithContext(ctx context.Context) DatabaseOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DatabaseOutput)
}

// DatabaseArrayInput is an input type that accepts DatabaseArray and DatabaseArrayOutput values.
// You can construct a concrete instance of `DatabaseArrayInput` via:
//
//	DatabaseArray{ DatabaseArgs{...} }
type DatabaseArrayInput interface {
	pulumi.Input

	ToDatabaseArrayOutput() DatabaseArrayOutput
	ToDatabaseArrayOutputWithContext(context.Context) DatabaseArrayOutput
}

type DatabaseArray []DatabaseInput

func (DatabaseArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Database)(nil)).Elem()
}

func (i DatabaseArray) ToDatabaseArrayOutput() DatabaseArrayOutput {
	return i.ToDatabaseArrayOutputWithContext(context.Background())
}

func (i DatabaseArray) ToDatabaseArrayOutputWithContext(ctx context.Context) DatabaseArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DatabaseArrayOutput)
}

// DatabaseMapInput is an input type that accepts DatabaseMap and DatabaseMapOutput values.
// You can construct a concrete instance of `DatabaseMapInput` via:
//
//	DatabaseMap{ "key": DatabaseArgs{...} }
type DatabaseMapInput interface {
	pulumi.Input

	ToDatabaseMapOutput() DatabaseMapOutput
	ToDatabaseMapOutputWithContext(context.Context) DatabaseMapOutput
}

type DatabaseMap map[string]DatabaseInput

func (DatabaseMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Database)(nil)).Elem()
}

func (i DatabaseMap) ToDatabaseMapOutput() DatabaseMapOutput {
	return i.ToDatabaseMapOutputWithContext(context.Background())
}

func (i DatabaseMap) ToDatabaseMapOutputWithContext(ctx context.Context) DatabaseMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DatabaseMapOutput)
}

type DatabaseOutput struct{ *pulumi.OutputState }

func (DatabaseOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Database)(nil)).Elem()
}

func (o DatabaseOutput) ToDatabaseOutput() DatabaseOutput {
	return o
}

func (o DatabaseOutput) ToDatabaseOutputWithContext(ctx context.Context) DatabaseOutput {
	return o
}

// Number of CPU cores. Derived from resource_profile.
func (o DatabaseOutput) CpuCores() pulumi.IntOutput {
	return o.ApplyT(func(v *Database) pulumi.IntOutput { return v.CpuCores }).(pulumi.IntOutput)
}

// Creation timestamp.
func (o DatabaseOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *Database) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// Name of the initial database to create. Must start with a letter and contain only letters, numbers, and underscores.
func (o DatabaseOutput) DatabaseName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Database) pulumi.StringPtrOutput { return v.DatabaseName }).(pulumi.StringPtrOutput)
}

// Datacenter location (fsn1, nbg1, hel1).
func (o DatabaseOutput) Datacenter() pulumi.StringOutput {
	return o.ApplyT(func(v *Database) pulumi.StringOutput { return v.Datacenter }).(pulumi.StringOutput)
}

// Deployment timestamp.
func (o DatabaseOutput) DeployedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *Database) pulumi.StringOutput { return v.DeployedAt }).(pulumi.StringOutput)
}

// Connection endpoint hostname.
func (o DatabaseOutput) Endpoint() pulumi.StringOutput {
	return o.ApplyT(func(v *Database) pulumi.StringOutput { return v.Endpoint }).(pulumi.StringOutput)
}

// Database engine (mysql, postgresql, mariadb).
func (o DatabaseOutput) Engine() pulumi.StringOutput {
	return o.ApplyT(func(v *Database) pulumi.StringOutput { return v.Engine }).(pulumi.StringOutput)
}

// Memory size in MB. Derived from resource_profile.
func (o DatabaseOutput) MemorySizeMb() pulumi.IntOutput {
	return o.ApplyT(func(v *Database) pulumi.IntOutput { return v.MemorySizeMb }).(pulumi.IntOutput)
}

// Estimated monthly cost.
func (o DatabaseOutput) MonthlyCost() pulumi.Float64Output {
	return o.ApplyT(func(v *Database) pulumi.Float64Output { return v.MonthlyCost }).(pulumi.Float64Output)
}

// Monthly cost in cents.
func (o DatabaseOutput) MonthlyCostCents() pulumi.IntOutput {
	return o.ApplyT(func(v *Database) pulumi.IntOutput { return v.MonthlyCostCents }).(pulumi.IntOutput)
}

// Name of the database instance. Must be lowercase alphanumeric with hyphens (DNS compatible).
func (o DatabaseOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Database) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// ID of the parameter group to use for custom configuration.
func (o DatabaseOutput) ParameterGroupId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Database) pulumi.StringPtrOutput { return v.ParameterGroupId }).(pulumi.StringPtrOutput)
}

// Connection port.
func (o DatabaseOutput) Port() pulumi.IntOutput {
	return o.ApplyT(func(v *Database) pulumi.IntOutput { return v.Port }).(pulumi.IntOutput)
}

// Resource profile for the database (small, medium, large).
func (o DatabaseOutput) ResourceProfile() pulumi.StringOutput {
	return o.ApplyT(func(v *Database) pulumi.StringOutput { return v.ResourceProfile }).(pulumi.StringOutput)
}

// Current status.
func (o DatabaseOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v *Database) pulumi.StringOutput { return v.Status }).(pulumi.StringOutput)
}

// Storage size in GB. Derived from resource_profile.
func (o DatabaseOutput) StorageSizeGb() pulumi.IntOutput {
	return o.ApplyT(func(v *Database) pulumi.IntOutput { return v.StorageSizeGb }).(pulumi.IntOutput)
}

func (o DatabaseOutput) Timeouts() DatabaseTimeoutsPtrOutput {
	return o.ApplyT(func(v *Database) DatabaseTimeoutsPtrOutput { return v.Timeouts }).(DatabaseTimeoutsPtrOutput)
}

// Timestamp when the database instance was last updated.
func (o DatabaseOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *Database) pulumi.StringOutput { return v.UpdatedAt }).(pulumi.StringOutput)
}

// Database admin username.
func (o DatabaseOutput) Username() pulumi.StringOutput {
	return o.ApplyT(func(v *Database) pulumi.StringOutput { return v.Username }).(pulumi.StringOutput)
}

// Version of the database software.
func (o DatabaseOutput) Version() pulumi.StringOutput {
	return o.ApplyT(func(v *Database) pulumi.StringOutput { return v.Version }).(pulumi.StringOutput)
}

type DatabaseArrayOutput struct{ *pulumi.OutputState }

func (DatabaseArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Database)(nil)).Elem()
}

func (o DatabaseArrayOutput) ToDatabaseArrayOutput() DatabaseArrayOutput {
	return o
}

func (o DatabaseArrayOutput) ToDatabaseArrayOutputWithContext(ctx context.Context) DatabaseArrayOutput {
	return o
}

func (o DatabaseArrayOutput) Index(i pulumi.IntInput) DatabaseOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Database {
		return vs[0].([]*Database)[vs[1].(int)]
	}).(DatabaseOutput)
}

type DatabaseMapOutput struct{ *pulumi.OutputState }

func (DatabaseMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Database)(nil)).Elem()
}

func (o DatabaseMapOutput) ToDatabaseMapOutput() DatabaseMapOutput {
	return o
}

func (o DatabaseMapOutput) ToDatabaseMapOutputWithContext(ctx context.Context) DatabaseMapOutput {
	return o
}

func (o DatabaseMapOutput) MapIndex(k pulumi.StringInput) DatabaseOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Database {
		return vs[0].(map[string]*Database)[vs[1].(string)]
	}).(DatabaseOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*DatabaseInput)(nil)).Elem(), &Database{})
	pulumi.RegisterInputType(reflect.TypeOf((*DatabaseArrayInput)(nil)).Elem(), DatabaseArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*DatabaseMapInput)(nil)).Elem(), DatabaseMap{})
	pulumi.RegisterOutputType(DatabaseOutput{})
	pulumi.RegisterOutputType(DatabaseArrayOutput{})
	pulumi.RegisterOutputType(DatabaseMapOutput{})
}
