// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package danubedata

import (
	"context"
	"reflect"

	"github.com/AdrianSilaghi/pulumi-danubedata/sdk/go/danubedata/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// ## # Firewall
//
// Manages a firewall with rules for network traffic control.
//
// ## Example Usage
//
// ## Import
//
// Firewalls can be imported using their ID:
//
// bash
//
// ```sh
// $ pulumi import danubedata:index/firewall:Firewall example fw-abc123
// ```
type Firewall struct {
	pulumi.CustomResourceState

	// Creation timestamp.
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// Default action for traffic not matching any rule: 'drop' or 'accept'.
	DefaultAction pulumi.StringOutput `pulumi:"defaultAction"`
	// Description of the firewall.
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// Whether this is the default firewall for the team.
	IsDefault pulumi.BoolOutput `pulumi:"isDefault"`
	// Name of the firewall.
	Name pulumi.StringOutput `pulumi:"name"`
	// List of firewall rules.
	Rules FirewallRuleArrayOutput `pulumi:"rules"`
	// Current status of the firewall.
	Status pulumi.StringOutput `pulumi:"status"`
	// Timestamp when the firewall was last updated.
	UpdatedAt pulumi.StringOutput `pulumi:"updatedAt"`
}

// NewFirewall registers a new resource with the given unique name, arguments, and options.
func NewFirewall(ctx *pulumi.Context,
	name string, args *FirewallArgs, opts ...pulumi.ResourceOption) (*Firewall, error) {
	if args == nil {
		args = &FirewallArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Firewall
	err := ctx.RegisterResource("danubedata:index/firewall:Firewall", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetFirewall gets an existing Firewall resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetFirewall(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *FirewallState, opts ...pulumi.ResourceOption) (*Firewall, error) {
	var resource Firewall
	err := ctx.ReadResource("danubedata:index/firewall:Firewall", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Firewall resources.
type firewallState struct {
	// Creation timestamp.
	CreatedAt *string `pulumi:"createdAt"`
	// Default action for traffic not matching any rule: 'drop' or 'accept'.
	DefaultAction *string `pulumi:"defaultAction"`
	// Description of the firewall.
	Description *string `pulumi:"description"`
	// Whether this is the default firewall for the team.
	IsDefault *bool `pulumi:"isDefault"`
	// Name of the firewall.
	Name *string `pulumi:"name"`
	// List of firewall rules.
	Rules []FirewallRule `pulumi:"rules"`
	// Current status of the firewall.
	Status *string `pulumi:"status"`
	// Timestamp when the firewall was last updated.
	UpdatedAt *string `pulumi:"updatedAt"`
}

type FirewallState struct {
	// Creation timestamp.
	CreatedAt pulumi.StringPtrInput
	// Default action for traffic not matching any rule: 'drop' or 'accept'.
	DefaultAction pulumi.StringPtrInput
	// Description of the firewall.
	Description pulumi.StringPtrInput
	// Whether this is the default firewall for the team.
	IsDefault pulumi.BoolPtrInput
	// Name of the firewall.
	Name pulumi.StringPtrInput
	// List of firewall rules.
	Rules FirewallRuleArrayInput
	// Current status of the firewall.
	Status pulumi.StringPtrInput
	// Timestamp when the firewall was last updated.
	UpdatedAt pulumi.StringPtrInput
}

func (FirewallState) ElementType() reflect.Type {
	return reflect.TypeOf((*firewallState)(nil)).Elem()
}

type firewallArgs struct {
	// Default action for traffic not matching any rule: 'drop' or 'accept'.
	DefaultAction *string `pulumi:"defaultAction"`
	// Description of the firewall.
	Description *string `pulumi:"description"`
	// Whether this is the default firewall for the team.
	IsDefault *bool `pulumi:"isDefault"`
	// Name of the firewall.
	Name *string `pulumi:"name"`
	// List of firewall rules.
	Rules []FirewallRule `pulumi:"rules"`
}

// The set of arguments for constructing a Firewall resource.
type FirewallArgs struct {
	// Default action for traffic not matching any rule: 'drop' or 'accept'.
	DefaultAction pulumi.StringPtrInput
	// Description of the firewall.
	Description pulumi.StringPtrInput
	// Whether this is the default firewall for the team.
	IsDefault pulumi.BoolPtrInput
	// Name of the firewall.
	Name pulumi.StringPtrInput
	// List of firewall rules.
	Rules FirewallRuleArrayInput
}

func (FirewallArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*firewallArgs)(nil)).Elem()
}

type FirewallInput interface {
	pulumi.Input

	ToFirewallOutput() FirewallOutput
	ToFirewallOutputWithContext(ctx context.Context) FirewallOutput
}

func (*Firewall) ElementType() reflect.Type {
	return reflect.TypeOf((**Firewall)(nil)).Elem()
}

func (i *Firewall) ToFirewallOutput() FirewallOutput {
	return i.ToFirewallOutputWithContext(context.Background())
}

func (i *Firewall) ToFirewallOutputWithContext(ctx context.Context) FirewallOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FirewallOutput)
}

// FirewallArrayInput is an input type that accepts FirewallArray and FirewallArrayOutput values.
// You can construct a concrete instance of `FirewallArrayInput` via:
//
//	FirewallArray{ FirewallArgs{...} }
type FirewallArrayInput interface {
	pulumi.Input

	ToFirewallArrayOutput() FirewallArrayOutput
	ToFirewallArrayOutputWithContext(context.Context) FirewallArrayOutput
}

type FirewallArray []FirewallInput

func (FirewallArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Firewall)(nil)).Elem()
}

func (i FirewallArray) ToFirewallArrayOutput() FirewallArrayOutput {
	return i.ToFirewallArrayOutputWithContext(context.Background())
}

func (i FirewallArray) ToFirewallArrayOutputWithContext(ctx context.Context) FirewallArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FirewallArrayOutput)
}

// FirewallMapInput is an input type that accepts FirewallMap and FirewallMapOutput values.
// You can construct a concrete instance of `FirewallMapInput` via:
//
//	FirewallMap{ "key": FirewallArgs{...} }
type FirewallMapInput interface {
	pulumi.Input

	ToFirewallMapOutput() FirewallMapOutput
	ToFirewallMapOutputWithContext(context.Context) FirewallMapOutput
}

type FirewallMap map[string]FirewallInput

func (FirewallMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Firewall)(nil)).Elem()
}

func (i FirewallMap) ToFirewallMapOutput() FirewallMapOutput {
	return i.ToFirewallMapOutputWithContext(context.Background())
}

func (i FirewallMap) ToFirewallMapOutputWithContext(ctx context.Context) FirewallMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FirewallMapOutput)
}

type FirewallOutput struct{ *pulumi.OutputState }

func (FirewallOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Firewall)(nil)).Elem()
}

func (o FirewallOutput) ToFirewallOutput() FirewallOutput {
	return o
}

func (o FirewallOutput) ToFirewallOutputWithContext(ctx context.Context) FirewallOutput {
	return o
}

// Creation timestamp.
func (o FirewallOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *Firewall) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// Default action for traffic not matching any rule: 'drop' or 'accept'.
func (o FirewallOutput) DefaultAction() pulumi.StringOutput {
	return o.ApplyT(func(v *Firewall) pulumi.StringOutput { return v.DefaultAction }).(pulumi.StringOutput)
}

// Description of the firewall.
func (o FirewallOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Firewall) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

// Whether this is the default firewall for the team.
func (o FirewallOutput) IsDefault() pulumi.BoolOutput {
	return o.ApplyT(func(v *Firewall) pulumi.BoolOutput { return v.IsDefault }).(pulumi.BoolOutput)
}

// Name of the firewall.
func (o FirewallOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Firewall) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// List of firewall rules.
func (o FirewallOutput) Rules() FirewallRuleArrayOutput {
	return o.ApplyT(func(v *Firewall) FirewallRuleArrayOutput { return v.Rules }).(FirewallRuleArrayOutput)
}

// Current status of the firewall.
func (o FirewallOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v *Firewall) pulumi.StringOutput { return v.Status }).(pulumi.StringOutput)
}

// Timestamp when the firewall was last updated.
func (o FirewallOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *Firewall) pulumi.StringOutput { return v.UpdatedAt }).(pulumi.StringOutput)
}

type FirewallArrayOutput struct{ *pulumi.OutputState }

func (FirewallArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Firewall)(nil)).Elem()
}

func (o FirewallArrayOutput) ToFirewallArrayOutput() FirewallArrayOutput {
	return o
}

func (o FirewallArrayOutput) ToFirewallArrayOutputWithContext(ctx context.Context) FirewallArrayOutput {
	return o
}

func (o FirewallArrayOutput) Index(i pulumi.IntInput) FirewallOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Firewall {
		return vs[0].([]*Firewall)[vs[1].(int)]
	}).(FirewallOutput)
}

type FirewallMapOutput struct{ *pulumi.OutputState }

func (FirewallMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Firewall)(nil)).Elem()
}

func (o FirewallMapOutput) ToFirewallMapOutput() FirewallMapOutput {
	return o
}

func (o FirewallMapOutput) ToFirewallMapOutputWithContext(ctx context.Context) FirewallMapOutput {
	return o
}

func (o FirewallMapOutput) MapIndex(k pulumi.StringInput) FirewallOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Firewall {
		return vs[0].(map[string]*Firewall)[vs[1].(string)]
	}).(FirewallOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*FirewallInput)(nil)).Elem(), &Firewall{})
	pulumi.RegisterInputType(reflect.TypeOf((*FirewallArrayInput)(nil)).Elem(), FirewallArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*FirewallMapInput)(nil)).Elem(), FirewallMap{})
	pulumi.RegisterOutputType(FirewallOutput{})
	pulumi.RegisterOutputType(FirewallArrayOutput{})
	pulumi.RegisterOutputType(FirewallMapOutput{})
}
