// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package danubedata

import (
	"context"
	"reflect"

	"github.com/AdrianSilaghi/pulumi-danubedata/sdk/go/danubedata/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// ## # getCacheProviders
//
// Lists available cache providers (Redis, Valkey, Dragonfly).
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/AdrianSilaghi/pulumi-danubedata/sdk/go/danubedata"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			all, err := danubedata.GetCacheProviders(ctx, map[string]interface{}{}, nil)
//			if err != nil {
//				return err
//			}
//			ctx.Export("cacheProviders", pulumi.MapArray("TODO: For expression"))
//			return nil
//		})
//	}
//
// ```
func GetCacheProviders(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*GetCacheProvidersResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetCacheProvidersResult
	err := ctx.Invoke("danubedata:index/getCacheProviders:getCacheProviders", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getCacheProviders.
type GetCacheProvidersResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// List of cache providers. Each provider contains:
	Providers []GetCacheProvidersProvider `pulumi:"providers"`
}

func GetCacheProvidersOutput(ctx *pulumi.Context, opts ...pulumi.InvokeOption) GetCacheProvidersResultOutput {
	return pulumi.ToOutput(0).ApplyT(func(int) (GetCacheProvidersResultOutput, error) {
		opts = internal.PkgInvokeDefaultOpts(opts)
		var rv GetCacheProvidersResult
		secret, err := ctx.InvokePackageRaw("danubedata:index/getCacheProviders:getCacheProviders", nil, &rv, "", opts...)
		if err != nil {
			return GetCacheProvidersResultOutput{}, err
		}

		output := pulumi.ToOutput(rv).(GetCacheProvidersResultOutput)
		if secret {
			return pulumi.ToSecret(output).(GetCacheProvidersResultOutput), nil
		}
		return output, nil
	}).(GetCacheProvidersResultOutput)
}

// A collection of values returned by getCacheProviders.
type GetCacheProvidersResultOutput struct{ *pulumi.OutputState }

func (GetCacheProvidersResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetCacheProvidersResult)(nil)).Elem()
}

func (o GetCacheProvidersResultOutput) ToGetCacheProvidersResultOutput() GetCacheProvidersResultOutput {
	return o
}

func (o GetCacheProvidersResultOutput) ToGetCacheProvidersResultOutputWithContext(ctx context.Context) GetCacheProvidersResultOutput {
	return o
}

// The provider-assigned unique ID for this managed resource.
func (o GetCacheProvidersResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetCacheProvidersResult) string { return v.Id }).(pulumi.StringOutput)
}

// List of cache providers. Each provider contains:
func (o GetCacheProvidersResultOutput) Providers() GetCacheProvidersProviderArrayOutput {
	return o.ApplyT(func(v GetCacheProvidersResult) []GetCacheProvidersProvider { return v.Providers }).(GetCacheProvidersProviderArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetCacheProvidersResultOutput{})
}
