// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package danubedata

import (
	"context"
	"reflect"

	"github.com/AdrianSilaghi/pulumi-danubedata/sdk/go/danubedata/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// ## # getDatabaseProviders
//
// Lists available database providers (MySQL, PostgreSQL, MariaDB).
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/AdrianSilaghi/pulumi-danubedata/sdk/go/danubedata"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			all, err := danubedata.GetDatabaseProviders(ctx, map[string]interface{}{}, nil)
//			if err != nil {
//				return err
//			}
//			ctx.Export("databaseProviders", pulumi.MapArray("TODO: For expression"))
//			return nil
//		})
//	}
//
// ```
func GetDatabaseProviders(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*GetDatabaseProvidersResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetDatabaseProvidersResult
	err := ctx.Invoke("danubedata:index/getDatabaseProviders:getDatabaseProviders", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getDatabaseProviders.
type GetDatabaseProvidersResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// List of database providers. Each provider contains:
	Providers []GetDatabaseProvidersProvider `pulumi:"providers"`
}

func GetDatabaseProvidersOutput(ctx *pulumi.Context, opts ...pulumi.InvokeOption) GetDatabaseProvidersResultOutput {
	return pulumi.ToOutput(0).ApplyT(func(int) (GetDatabaseProvidersResultOutput, error) {
		opts = internal.PkgInvokeDefaultOpts(opts)
		var rv GetDatabaseProvidersResult
		secret, err := ctx.InvokePackageRaw("danubedata:index/getDatabaseProviders:getDatabaseProviders", nil, &rv, "", opts...)
		if err != nil {
			return GetDatabaseProvidersResultOutput{}, err
		}

		output := pulumi.ToOutput(rv).(GetDatabaseProvidersResultOutput)
		if secret {
			return pulumi.ToSecret(output).(GetDatabaseProvidersResultOutput), nil
		}
		return output, nil
	}).(GetDatabaseProvidersResultOutput)
}

// A collection of values returned by getDatabaseProviders.
type GetDatabaseProvidersResultOutput struct{ *pulumi.OutputState }

func (GetDatabaseProvidersResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDatabaseProvidersResult)(nil)).Elem()
}

func (o GetDatabaseProvidersResultOutput) ToGetDatabaseProvidersResultOutput() GetDatabaseProvidersResultOutput {
	return o
}

func (o GetDatabaseProvidersResultOutput) ToGetDatabaseProvidersResultOutputWithContext(ctx context.Context) GetDatabaseProvidersResultOutput {
	return o
}

// The provider-assigned unique ID for this managed resource.
func (o GetDatabaseProvidersResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetDatabaseProvidersResult) string { return v.Id }).(pulumi.StringOutput)
}

// List of database providers. Each provider contains:
func (o GetDatabaseProvidersResultOutput) Providers() GetDatabaseProvidersProviderArrayOutput {
	return o.ApplyT(func(v GetDatabaseProvidersResult) []GetDatabaseProvidersProvider { return v.Providers }).(GetDatabaseProvidersProviderArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetDatabaseProvidersResultOutput{})
}
