// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package danubedata

import (
	"context"
	"reflect"

	"github.com/AdrianSilaghi/pulumi-danubedata/sdk/go/danubedata/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// ## # getFirewalls
//
// Lists all firewalls in your account.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/AdrianSilaghi/pulumi-danubedata/sdk/go/danubedata"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			all, err := danubedata.GetFirewalls(ctx, map[string]interface{}{}, nil)
//			if err != nil {
//				return err
//			}
//			ctx.Export("firewallCount", pulumi.Int(len(all.Firewalls)))
//			ctx.Export("firewallNames", pulumi.StringArray("TODO: For expression"))
//			return nil
//		})
//	}
//
// ```
//
// ### Find Firewall by Name
//
// ```go
// package main
//
// import (
//
//	"github.com/AdrianSilaghi/pulumi-danubedata/sdk/go/danubedata"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			all, err := danubedata.GetFirewalls(ctx, map[string]interface{}{}, nil)
//			if err != nil {
//				return err
//			}
//			webFirewall := "TODO: For expression"[0]
//			ctx.Export("webFirewallId", webFirewall.Id)
//			ctx.Export("webFirewallRules", webFirewall.RulesCount)
//			return nil
//		})
//	}
//
// ```
//
// ### Find Default Firewall
//
// ```go
// package main
//
// import (
//
//	"github.com/AdrianSilaghi/pulumi-danubedata/sdk/go/danubedata"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			all, err := danubedata.GetFirewalls(ctx, map[string]interface{}{}, nil)
//			if err != nil {
//				return err
//			}
//			defaultFirewall := "TODO: For expression"[0]
//			ctx.Export("defaultFirewallId", defaultFirewall.Id)
//			return nil
//		})
//	}
//
// ```
func GetFirewalls(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*GetFirewallsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetFirewallsResult
	err := ctx.Invoke("danubedata:index/getFirewalls:getFirewalls", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getFirewalls.
type GetFirewallsResult struct {
	// List of firewalls. Each firewall contains:
	Firewalls []GetFirewallsFirewall `pulumi:"firewalls"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
}

func GetFirewallsOutput(ctx *pulumi.Context, opts ...pulumi.InvokeOption) GetFirewallsResultOutput {
	return pulumi.ToOutput(0).ApplyT(func(int) (GetFirewallsResultOutput, error) {
		opts = internal.PkgInvokeDefaultOpts(opts)
		var rv GetFirewallsResult
		secret, err := ctx.InvokePackageRaw("danubedata:index/getFirewalls:getFirewalls", nil, &rv, "", opts...)
		if err != nil {
			return GetFirewallsResultOutput{}, err
		}

		output := pulumi.ToOutput(rv).(GetFirewallsResultOutput)
		if secret {
			return pulumi.ToSecret(output).(GetFirewallsResultOutput), nil
		}
		return output, nil
	}).(GetFirewallsResultOutput)
}

// A collection of values returned by getFirewalls.
type GetFirewallsResultOutput struct{ *pulumi.OutputState }

func (GetFirewallsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetFirewallsResult)(nil)).Elem()
}

func (o GetFirewallsResultOutput) ToGetFirewallsResultOutput() GetFirewallsResultOutput {
	return o
}

func (o GetFirewallsResultOutput) ToGetFirewallsResultOutputWithContext(ctx context.Context) GetFirewallsResultOutput {
	return o
}

// List of firewalls. Each firewall contains:
func (o GetFirewallsResultOutput) Firewalls() GetFirewallsFirewallArrayOutput {
	return o.ApplyT(func(v GetFirewallsResult) []GetFirewallsFirewall { return v.Firewalls }).(GetFirewallsFirewallArrayOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetFirewallsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetFirewallsResult) string { return v.Id }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetFirewallsResultOutput{})
}
