// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package danubedata

import (
	"context"
	"reflect"

	"github.com/AdrianSilaghi/pulumi-danubedata/sdk/go/danubedata/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// ## # getSshKeys
//
// Lists all SSH keys in your account.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/AdrianSilaghi/pulumi-danubedata/sdk/go/danubedata"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			all, err := danubedata.GetSshKeys(ctx, map[string]interface{}{}, nil)
//			if err != nil {
//				return err
//			}
//			ctx.Export("sshKeyIds", pulumi.StringArray("TODO: For expression"))
//			ctx.Export("sshKeyNames", pulumi.StringArray("TODO: For expression"))
//			return nil
//		})
//	}
//
// ```
//
// ### Find Key by Name
//
// ```go
// package main
//
// import (
//
//	"github.com/AdrianSilaghi/pulumi-danubedata/sdk/go/danubedata"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			all, err := danubedata.GetSshKeys(ctx, map[string]interface{}{}, nil)
//			if err != nil {
//				return err
//			}
//			deployKey := "TODO: For expression"[0]
//			_, err = danubedata.NewVps(ctx, "server", &danubedata.VpsArgs{
//				Image:      pulumi.String("ubuntu-22.04"),
//				Datacenter: pulumi.String("fsn1"),
//				AuthMethod: pulumi.String("ssh_key"),
//				SshKeyId:   pulumi.String(deployKey.Id),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func GetSshKeys(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*GetSshKeysResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetSshKeysResult
	err := ctx.Invoke("danubedata:index/getSshKeys:getSshKeys", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getSshKeys.
type GetSshKeysResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// List of SSH keys. Each key contains:
	Keys []GetSshKeysKey `pulumi:"keys"`
}

func GetSshKeysOutput(ctx *pulumi.Context, opts ...pulumi.InvokeOption) GetSshKeysResultOutput {
	return pulumi.ToOutput(0).ApplyT(func(int) (GetSshKeysResultOutput, error) {
		opts = internal.PkgInvokeDefaultOpts(opts)
		var rv GetSshKeysResult
		secret, err := ctx.InvokePackageRaw("danubedata:index/getSshKeys:getSshKeys", nil, &rv, "", opts...)
		if err != nil {
			return GetSshKeysResultOutput{}, err
		}

		output := pulumi.ToOutput(rv).(GetSshKeysResultOutput)
		if secret {
			return pulumi.ToSecret(output).(GetSshKeysResultOutput), nil
		}
		return output, nil
	}).(GetSshKeysResultOutput)
}

// A collection of values returned by getSshKeys.
type GetSshKeysResultOutput struct{ *pulumi.OutputState }

func (GetSshKeysResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetSshKeysResult)(nil)).Elem()
}

func (o GetSshKeysResultOutput) ToGetSshKeysResultOutput() GetSshKeysResultOutput {
	return o
}

func (o GetSshKeysResultOutput) ToGetSshKeysResultOutputWithContext(ctx context.Context) GetSshKeysResultOutput {
	return o
}

// The provider-assigned unique ID for this managed resource.
func (o GetSshKeysResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetSshKeysResult) string { return v.Id }).(pulumi.StringOutput)
}

// List of SSH keys. Each key contains:
func (o GetSshKeysResultOutput) Keys() GetSshKeysKeyArrayOutput {
	return o.ApplyT(func(v GetSshKeysResult) []GetSshKeysKey { return v.Keys }).(GetSshKeysKeyArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetSshKeysResultOutput{})
}
