// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package danubedata

import (
	"context"
	"reflect"

	"github.com/AdrianSilaghi/pulumi-danubedata/sdk/go/danubedata/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// ## # getStorageBuckets
//
// Lists all S3-compatible storage buckets in your account.
//
// ### Find Bucket by Name
//
// ```go
// package main
//
// import (
//
//	"github.com/AdrianSilaghi/pulumi-danubedata/sdk/go/danubedata"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			all, err := danubedata.GetStorageBuckets(ctx, map[string]interface{}{}, nil)
//			if err != nil {
//				return err
//			}
//			assetsBucket := "TODO: For expression"[0]
//			ctx.Export("assetsEndpoint", assetsBucket.EndpointUrl)
//			ctx.Export("assetsBucketName", assetsBucket.MinioBucketName)
//			return nil
//		})
//	}
//
// ```
//
// ### Filter Public Buckets
//
// ```go
// package main
//
// import (
//
//	"github.com/AdrianSilaghi/pulumi-danubedata/sdk/go/danubedata"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			all, err := danubedata.GetStorageBuckets(ctx, map[string]interface{}{}, nil)
//			if err != nil {
//				return err
//			}
//			publicBuckets := "TODO: For expression"
//			ctx.Export("publicBucketUrls", pulumi.StringArray("TODO: For expression"))
//			return nil
//		})
//	}
//
// ```
func GetStorageBuckets(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*GetStorageBucketsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetStorageBucketsResult
	err := ctx.Invoke("danubedata:index/getStorageBuckets:getStorageBuckets", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getStorageBuckets.
type GetStorageBucketsResult struct {
	// List of storage buckets. Each bucket contains:
	Buckets []GetStorageBucketsBucket `pulumi:"buckets"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
}

func GetStorageBucketsOutput(ctx *pulumi.Context, opts ...pulumi.InvokeOption) GetStorageBucketsResultOutput {
	return pulumi.ToOutput(0).ApplyT(func(int) (GetStorageBucketsResultOutput, error) {
		opts = internal.PkgInvokeDefaultOpts(opts)
		var rv GetStorageBucketsResult
		secret, err := ctx.InvokePackageRaw("danubedata:index/getStorageBuckets:getStorageBuckets", nil, &rv, "", opts...)
		if err != nil {
			return GetStorageBucketsResultOutput{}, err
		}

		output := pulumi.ToOutput(rv).(GetStorageBucketsResultOutput)
		if secret {
			return pulumi.ToSecret(output).(GetStorageBucketsResultOutput), nil
		}
		return output, nil
	}).(GetStorageBucketsResultOutput)
}

// A collection of values returned by getStorageBuckets.
type GetStorageBucketsResultOutput struct{ *pulumi.OutputState }

func (GetStorageBucketsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetStorageBucketsResult)(nil)).Elem()
}

func (o GetStorageBucketsResultOutput) ToGetStorageBucketsResultOutput() GetStorageBucketsResultOutput {
	return o
}

func (o GetStorageBucketsResultOutput) ToGetStorageBucketsResultOutputWithContext(ctx context.Context) GetStorageBucketsResultOutput {
	return o
}

// List of storage buckets. Each bucket contains:
func (o GetStorageBucketsResultOutput) Buckets() GetStorageBucketsBucketArrayOutput {
	return o.ApplyT(func(v GetStorageBucketsResult) []GetStorageBucketsBucket { return v.Buckets }).(GetStorageBucketsBucketArrayOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetStorageBucketsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetStorageBucketsResult) string { return v.Id }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetStorageBucketsResultOutput{})
}
