// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package danubedata

import (
	"context"
	"reflect"

	"github.com/AdrianSilaghi/pulumi-danubedata/sdk/go/danubedata/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// ## # getVpsSnapshots
//
// Lists all VPS snapshots in your account.
//
// ### Find Snapshot by Name
//
// ```go
// package main
//
// import (
//
//	"github.com/AdrianSilaghi/pulumi-danubedata/sdk/go/danubedata"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			all, err := danubedata.GetVpsSnapshots(ctx, map[string]interface{}{}, nil)
//			if err != nil {
//				return err
//			}
//			preUpgrade := "TODO: For expression"[0]
//			ctx.Export("preUpgradeSnapshotId", preUpgrade.Id)
//			return nil
//		})
//	}
//
// ```
//
// ### Filter Snapshots by VPS Instance
//
// ```go
// package main
//
// import (
//
//	"github.com/AdrianSilaghi/pulumi-danubedata/sdk/go/danubedata"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			all, err := danubedata.GetVpsSnapshots(ctx, map[string]interface{}{}, nil)
//			if err != nil {
//				return err
//			}
//			cfg := config.New(ctx, "")
//			vpsId := "vps-abc123"
//			if param := cfg.Get("vpsId"); param != "" {
//				vpsId = param
//			}
//			vpsSnapshots := "TODO: For expression"
//			ctx.Export("vpsSnapshotCount", pulumi.Int(len(vpsSnapshots)))
//			return nil
//		})
//	}
//
// ```
//
// ### Filter Ready Snapshots
//
// ```go
// package main
//
// import (
//
//	"github.com/AdrianSilaghi/pulumi-danubedata/sdk/go/danubedata"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			all, err := danubedata.GetVpsSnapshots(ctx, map[string]interface{}{}, nil)
//			if err != nil {
//				return err
//			}
//			readySnapshots := "TODO: For expression"
//			ctx.Export("readyCount", pulumi.Int(len(readySnapshots)))
//			return nil
//		})
//	}
//
// ```
func GetVpsSnapshots(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*GetVpsSnapshotsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetVpsSnapshotsResult
	err := ctx.Invoke("danubedata:index/getVpsSnapshots:getVpsSnapshots", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getVpsSnapshots.
type GetVpsSnapshotsResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// List of VPS snapshots. Each snapshot contains:
	Snapshots []GetVpsSnapshotsSnapshot `pulumi:"snapshots"`
}

func GetVpsSnapshotsOutput(ctx *pulumi.Context, opts ...pulumi.InvokeOption) GetVpsSnapshotsResultOutput {
	return pulumi.ToOutput(0).ApplyT(func(int) (GetVpsSnapshotsResultOutput, error) {
		opts = internal.PkgInvokeDefaultOpts(opts)
		var rv GetVpsSnapshotsResult
		secret, err := ctx.InvokePackageRaw("danubedata:index/getVpsSnapshots:getVpsSnapshots", nil, &rv, "", opts...)
		if err != nil {
			return GetVpsSnapshotsResultOutput{}, err
		}

		output := pulumi.ToOutput(rv).(GetVpsSnapshotsResultOutput)
		if secret {
			return pulumi.ToSecret(output).(GetVpsSnapshotsResultOutput), nil
		}
		return output, nil
	}).(GetVpsSnapshotsResultOutput)
}

// A collection of values returned by getVpsSnapshots.
type GetVpsSnapshotsResultOutput struct{ *pulumi.OutputState }

func (GetVpsSnapshotsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetVpsSnapshotsResult)(nil)).Elem()
}

func (o GetVpsSnapshotsResultOutput) ToGetVpsSnapshotsResultOutput() GetVpsSnapshotsResultOutput {
	return o
}

func (o GetVpsSnapshotsResultOutput) ToGetVpsSnapshotsResultOutputWithContext(ctx context.Context) GetVpsSnapshotsResultOutput {
	return o
}

// The provider-assigned unique ID for this managed resource.
func (o GetVpsSnapshotsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetVpsSnapshotsResult) string { return v.Id }).(pulumi.StringOutput)
}

// List of VPS snapshots. Each snapshot contains:
func (o GetVpsSnapshotsResultOutput) Snapshots() GetVpsSnapshotsSnapshotArrayOutput {
	return o.ApplyT(func(v GetVpsSnapshotsResult) []GetVpsSnapshotsSnapshot { return v.Snapshots }).(GetVpsSnapshotsSnapshotArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetVpsSnapshotsResultOutput{})
}
