// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package danubedata

import (
	"context"
	"reflect"

	"errors"
	"github.com/AdrianSilaghi/pulumi-danubedata/sdk/go/danubedata/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// ## # VpsSnapshot
//
// Manages a VPS snapshot for backup and recovery.
//
// ## Example Usage
//
// ### Basic Snapshot
//
// ```go
// package main
//
// import (
//
//	"github.com/AdrianSilaghi/pulumi-danubedata/sdk/go/danubedata"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			server, err := danubedata.NewVps(ctx, "server", &danubedata.VpsArgs{
//				Image:      pulumi.String("ubuntu-22.04"),
//				Datacenter: pulumi.String("fsn1"),
//				AuthMethod: pulumi.String("ssh_key"),
//				SshKeyId:   pulumi.Any(danubedata_ssh_key.Main.Id),
//			})
//			if err != nil {
//				return err
//			}
//			_, err = danubedata.NewVpsSnapshot(ctx, "backup", &danubedata.VpsSnapshotArgs{
//				VpsInstanceId: server.ID(),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ### Snapshot with Description
//
// ```go
// package main
//
// import (
//
//	"github.com/AdrianSilaghi/pulumi-danubedata/sdk/go/danubedata"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := danubedata.NewVpsSnapshot(ctx, "release", &danubedata.VpsSnapshotArgs{
//				Description:   pulumi.String("Snapshot before v1.0 release deployment"),
//				VpsInstanceId: pulumi.Any(danubedata_vps.Server.Id),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// VPS snapshots can be imported using their ID:
//
// bash
//
// ```sh
// $ pulumi import danubedata:index/vpsSnapshot:VpsSnapshot example snap-abc123
// ```
type VpsSnapshot struct {
	pulumi.CustomResourceState

	// Creation timestamp.
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// Description of the snapshot.
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// Name of the snapshot.
	Name pulumi.StringOutput `pulumi:"name"`
	// Size of the snapshot in GB.
	SizeGb pulumi.Float64Output `pulumi:"sizeGb"`
	// Current status (`creating`, `ready`, `error`).
	Status   pulumi.StringOutput          `pulumi:"status"`
	Timeouts VpsSnapshotTimeoutsPtrOutput `pulumi:"timeouts"`
	// Timestamp when the snapshot was last updated.
	UpdatedAt pulumi.StringOutput `pulumi:"updatedAt"`
	// ID of the VPS instance to snapshot.
	VpsInstanceId pulumi.StringOutput `pulumi:"vpsInstanceId"`
}

// NewVpsSnapshot registers a new resource with the given unique name, arguments, and options.
func NewVpsSnapshot(ctx *pulumi.Context,
	name string, args *VpsSnapshotArgs, opts ...pulumi.ResourceOption) (*VpsSnapshot, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.VpsInstanceId == nil {
		return nil, errors.New("invalid value for required argument 'VpsInstanceId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource VpsSnapshot
	err := ctx.RegisterResource("danubedata:index/vpsSnapshot:VpsSnapshot", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetVpsSnapshot gets an existing VpsSnapshot resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetVpsSnapshot(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *VpsSnapshotState, opts ...pulumi.ResourceOption) (*VpsSnapshot, error) {
	var resource VpsSnapshot
	err := ctx.ReadResource("danubedata:index/vpsSnapshot:VpsSnapshot", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering VpsSnapshot resources.
type vpsSnapshotState struct {
	// Creation timestamp.
	CreatedAt *string `pulumi:"createdAt"`
	// Description of the snapshot.
	Description *string `pulumi:"description"`
	// Name of the snapshot.
	Name *string `pulumi:"name"`
	// Size of the snapshot in GB.
	SizeGb *float64 `pulumi:"sizeGb"`
	// Current status (`creating`, `ready`, `error`).
	Status   *string              `pulumi:"status"`
	Timeouts *VpsSnapshotTimeouts `pulumi:"timeouts"`
	// Timestamp when the snapshot was last updated.
	UpdatedAt *string `pulumi:"updatedAt"`
	// ID of the VPS instance to snapshot.
	VpsInstanceId *string `pulumi:"vpsInstanceId"`
}

type VpsSnapshotState struct {
	// Creation timestamp.
	CreatedAt pulumi.StringPtrInput
	// Description of the snapshot.
	Description pulumi.StringPtrInput
	// Name of the snapshot.
	Name pulumi.StringPtrInput
	// Size of the snapshot in GB.
	SizeGb pulumi.Float64PtrInput
	// Current status (`creating`, `ready`, `error`).
	Status   pulumi.StringPtrInput
	Timeouts VpsSnapshotTimeoutsPtrInput
	// Timestamp when the snapshot was last updated.
	UpdatedAt pulumi.StringPtrInput
	// ID of the VPS instance to snapshot.
	VpsInstanceId pulumi.StringPtrInput
}

func (VpsSnapshotState) ElementType() reflect.Type {
	return reflect.TypeOf((*vpsSnapshotState)(nil)).Elem()
}

type vpsSnapshotArgs struct {
	// Description of the snapshot.
	Description *string `pulumi:"description"`
	// Name of the snapshot.
	Name     *string              `pulumi:"name"`
	Timeouts *VpsSnapshotTimeouts `pulumi:"timeouts"`
	// ID of the VPS instance to snapshot.
	VpsInstanceId string `pulumi:"vpsInstanceId"`
}

// The set of arguments for constructing a VpsSnapshot resource.
type VpsSnapshotArgs struct {
	// Description of the snapshot.
	Description pulumi.StringPtrInput
	// Name of the snapshot.
	Name     pulumi.StringPtrInput
	Timeouts VpsSnapshotTimeoutsPtrInput
	// ID of the VPS instance to snapshot.
	VpsInstanceId pulumi.StringInput
}

func (VpsSnapshotArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*vpsSnapshotArgs)(nil)).Elem()
}

type VpsSnapshotInput interface {
	pulumi.Input

	ToVpsSnapshotOutput() VpsSnapshotOutput
	ToVpsSnapshotOutputWithContext(ctx context.Context) VpsSnapshotOutput
}

func (*VpsSnapshot) ElementType() reflect.Type {
	return reflect.TypeOf((**VpsSnapshot)(nil)).Elem()
}

func (i *VpsSnapshot) ToVpsSnapshotOutput() VpsSnapshotOutput {
	return i.ToVpsSnapshotOutputWithContext(context.Background())
}

func (i *VpsSnapshot) ToVpsSnapshotOutputWithContext(ctx context.Context) VpsSnapshotOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VpsSnapshotOutput)
}

// VpsSnapshotArrayInput is an input type that accepts VpsSnapshotArray and VpsSnapshotArrayOutput values.
// You can construct a concrete instance of `VpsSnapshotArrayInput` via:
//
//	VpsSnapshotArray{ VpsSnapshotArgs{...} }
type VpsSnapshotArrayInput interface {
	pulumi.Input

	ToVpsSnapshotArrayOutput() VpsSnapshotArrayOutput
	ToVpsSnapshotArrayOutputWithContext(context.Context) VpsSnapshotArrayOutput
}

type VpsSnapshotArray []VpsSnapshotInput

func (VpsSnapshotArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*VpsSnapshot)(nil)).Elem()
}

func (i VpsSnapshotArray) ToVpsSnapshotArrayOutput() VpsSnapshotArrayOutput {
	return i.ToVpsSnapshotArrayOutputWithContext(context.Background())
}

func (i VpsSnapshotArray) ToVpsSnapshotArrayOutputWithContext(ctx context.Context) VpsSnapshotArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VpsSnapshotArrayOutput)
}

// VpsSnapshotMapInput is an input type that accepts VpsSnapshotMap and VpsSnapshotMapOutput values.
// You can construct a concrete instance of `VpsSnapshotMapInput` via:
//
//	VpsSnapshotMap{ "key": VpsSnapshotArgs{...} }
type VpsSnapshotMapInput interface {
	pulumi.Input

	ToVpsSnapshotMapOutput() VpsSnapshotMapOutput
	ToVpsSnapshotMapOutputWithContext(context.Context) VpsSnapshotMapOutput
}

type VpsSnapshotMap map[string]VpsSnapshotInput

func (VpsSnapshotMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*VpsSnapshot)(nil)).Elem()
}

func (i VpsSnapshotMap) ToVpsSnapshotMapOutput() VpsSnapshotMapOutput {
	return i.ToVpsSnapshotMapOutputWithContext(context.Background())
}

func (i VpsSnapshotMap) ToVpsSnapshotMapOutputWithContext(ctx context.Context) VpsSnapshotMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VpsSnapshotMapOutput)
}

type VpsSnapshotOutput struct{ *pulumi.OutputState }

func (VpsSnapshotOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**VpsSnapshot)(nil)).Elem()
}

func (o VpsSnapshotOutput) ToVpsSnapshotOutput() VpsSnapshotOutput {
	return o
}

func (o VpsSnapshotOutput) ToVpsSnapshotOutputWithContext(ctx context.Context) VpsSnapshotOutput {
	return o
}

// Creation timestamp.
func (o VpsSnapshotOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *VpsSnapshot) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// Description of the snapshot.
func (o VpsSnapshotOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *VpsSnapshot) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

// Name of the snapshot.
func (o VpsSnapshotOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *VpsSnapshot) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Size of the snapshot in GB.
func (o VpsSnapshotOutput) SizeGb() pulumi.Float64Output {
	return o.ApplyT(func(v *VpsSnapshot) pulumi.Float64Output { return v.SizeGb }).(pulumi.Float64Output)
}

// Current status (`creating`, `ready`, `error`).
func (o VpsSnapshotOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v *VpsSnapshot) pulumi.StringOutput { return v.Status }).(pulumi.StringOutput)
}

func (o VpsSnapshotOutput) Timeouts() VpsSnapshotTimeoutsPtrOutput {
	return o.ApplyT(func(v *VpsSnapshot) VpsSnapshotTimeoutsPtrOutput { return v.Timeouts }).(VpsSnapshotTimeoutsPtrOutput)
}

// Timestamp when the snapshot was last updated.
func (o VpsSnapshotOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *VpsSnapshot) pulumi.StringOutput { return v.UpdatedAt }).(pulumi.StringOutput)
}

// ID of the VPS instance to snapshot.
func (o VpsSnapshotOutput) VpsInstanceId() pulumi.StringOutput {
	return o.ApplyT(func(v *VpsSnapshot) pulumi.StringOutput { return v.VpsInstanceId }).(pulumi.StringOutput)
}

type VpsSnapshotArrayOutput struct{ *pulumi.OutputState }

func (VpsSnapshotArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*VpsSnapshot)(nil)).Elem()
}

func (o VpsSnapshotArrayOutput) ToVpsSnapshotArrayOutput() VpsSnapshotArrayOutput {
	return o
}

func (o VpsSnapshotArrayOutput) ToVpsSnapshotArrayOutputWithContext(ctx context.Context) VpsSnapshotArrayOutput {
	return o
}

func (o VpsSnapshotArrayOutput) Index(i pulumi.IntInput) VpsSnapshotOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *VpsSnapshot {
		return vs[0].([]*VpsSnapshot)[vs[1].(int)]
	}).(VpsSnapshotOutput)
}

type VpsSnapshotMapOutput struct{ *pulumi.OutputState }

func (VpsSnapshotMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*VpsSnapshot)(nil)).Elem()
}

func (o VpsSnapshotMapOutput) ToVpsSnapshotMapOutput() VpsSnapshotMapOutput {
	return o
}

func (o VpsSnapshotMapOutput) ToVpsSnapshotMapOutputWithContext(ctx context.Context) VpsSnapshotMapOutput {
	return o
}

func (o VpsSnapshotMapOutput) MapIndex(k pulumi.StringInput) VpsSnapshotOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *VpsSnapshot {
		return vs[0].(map[string]*VpsSnapshot)[vs[1].(string)]
	}).(VpsSnapshotOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*VpsSnapshotInput)(nil)).Elem(), &VpsSnapshot{})
	pulumi.RegisterInputType(reflect.TypeOf((*VpsSnapshotArrayInput)(nil)).Elem(), VpsSnapshotArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*VpsSnapshotMapInput)(nil)).Elem(), VpsSnapshotMap{})
	pulumi.RegisterOutputType(VpsSnapshotOutput{})
	pulumi.RegisterOutputType(VpsSnapshotArrayOutput{})
	pulumi.RegisterOutputType(VpsSnapshotMapOutput{})
}
