// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Cache extends pulumi.CustomResource {
    /**
     * Get an existing Cache resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: CacheState, opts?: pulumi.CustomResourceOptions): Cache {
        return new Cache(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'danubedata:index/cache:Cache';

    /**
     * Returns true if the given object is an instance of Cache.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Cache {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Cache.__pulumiType;
    }

    /**
     * Cache provider type (redis, valkey, dragonfly).
     */
    public readonly cacheProvider!: pulumi.Output<string>;
    /**
     * Number of CPU cores. If not specified, determined by resource_profile.
     */
    public readonly cpuCores!: pulumi.Output<number>;
    /**
     * Timestamp when the cache instance was created.
     */
    public /*out*/ readonly createdAt!: pulumi.Output<string>;
    /**
     * Datacenter location (ash, fsn1, nbg1, hel1).
     */
    public readonly datacenter!: pulumi.Output<string>;
    /**
     * Timestamp when the cache instance was deployed.
     */
    public /*out*/ readonly deployedAt!: pulumi.Output<string>;
    /**
     * Connection endpoint for the cache instance.
     */
    public /*out*/ readonly endpoint!: pulumi.Output<string>;
    /**
     * Memory size in MB. If not specified, determined by resource_profile.
     */
    public readonly memorySizeMb!: pulumi.Output<number>;
    /**
     * Monthly cost in dollars.
     */
    public /*out*/ readonly monthlyCost!: pulumi.Output<number>;
    /**
     * Monthly cost in cents.
     */
    public /*out*/ readonly monthlyCostCents!: pulumi.Output<number>;
    /**
     * Name of the cache instance.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * ID of the parameter group to use for custom configuration.
     */
    public readonly parameterGroupId!: pulumi.Output<string | undefined>;
    /**
     * Port number for the cache instance.
     */
    public /*out*/ readonly port!: pulumi.Output<number>;
    /**
     * Resource profile for the cache (micro, small, medium, large).
     */
    public readonly resourceProfile!: pulumi.Output<string>;
    /**
     * Current status of the cache instance (pending, provisioning, running, stopped, error).
     */
    public /*out*/ readonly status!: pulumi.Output<string>;
    public readonly timeouts!: pulumi.Output<outputs.CacheTimeouts | undefined>;
    /**
     * Timestamp when the cache instance was last updated.
     */
    public /*out*/ readonly updatedAt!: pulumi.Output<string>;
    /**
     * Version of the cache software.
     */
    public readonly version!: pulumi.Output<string>;

    /**
     * Create a Cache resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: CacheArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: CacheArgs | CacheState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as CacheState | undefined;
            resourceInputs["cacheProvider"] = state ? state.cacheProvider : undefined;
            resourceInputs["cpuCores"] = state ? state.cpuCores : undefined;
            resourceInputs["createdAt"] = state ? state.createdAt : undefined;
            resourceInputs["datacenter"] = state ? state.datacenter : undefined;
            resourceInputs["deployedAt"] = state ? state.deployedAt : undefined;
            resourceInputs["endpoint"] = state ? state.endpoint : undefined;
            resourceInputs["memorySizeMb"] = state ? state.memorySizeMb : undefined;
            resourceInputs["monthlyCost"] = state ? state.monthlyCost : undefined;
            resourceInputs["monthlyCostCents"] = state ? state.monthlyCostCents : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["parameterGroupId"] = state ? state.parameterGroupId : undefined;
            resourceInputs["port"] = state ? state.port : undefined;
            resourceInputs["resourceProfile"] = state ? state.resourceProfile : undefined;
            resourceInputs["status"] = state ? state.status : undefined;
            resourceInputs["timeouts"] = state ? state.timeouts : undefined;
            resourceInputs["updatedAt"] = state ? state.updatedAt : undefined;
            resourceInputs["version"] = state ? state.version : undefined;
        } else {
            const args = argsOrState as CacheArgs | undefined;
            if ((!args || args.cacheProvider === undefined) && !opts.urn) {
                throw new Error("Missing required property 'cacheProvider'");
            }
            if ((!args || args.datacenter === undefined) && !opts.urn) {
                throw new Error("Missing required property 'datacenter'");
            }
            if ((!args || args.resourceProfile === undefined) && !opts.urn) {
                throw new Error("Missing required property 'resourceProfile'");
            }
            resourceInputs["cacheProvider"] = args ? args.cacheProvider : undefined;
            resourceInputs["cpuCores"] = args ? args.cpuCores : undefined;
            resourceInputs["datacenter"] = args ? args.datacenter : undefined;
            resourceInputs["memorySizeMb"] = args ? args.memorySizeMb : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["parameterGroupId"] = args ? args.parameterGroupId : undefined;
            resourceInputs["resourceProfile"] = args ? args.resourceProfile : undefined;
            resourceInputs["timeouts"] = args ? args.timeouts : undefined;
            resourceInputs["version"] = args ? args.version : undefined;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["deployedAt"] = undefined /*out*/;
            resourceInputs["endpoint"] = undefined /*out*/;
            resourceInputs["monthlyCost"] = undefined /*out*/;
            resourceInputs["monthlyCostCents"] = undefined /*out*/;
            resourceInputs["port"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
            resourceInputs["updatedAt"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Cache.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Cache resources.
 */
export interface CacheState {
    /**
     * Cache provider type (redis, valkey, dragonfly).
     */
    cacheProvider?: pulumi.Input<string>;
    /**
     * Number of CPU cores. If not specified, determined by resource_profile.
     */
    cpuCores?: pulumi.Input<number>;
    /**
     * Timestamp when the cache instance was created.
     */
    createdAt?: pulumi.Input<string>;
    /**
     * Datacenter location (ash, fsn1, nbg1, hel1).
     */
    datacenter?: pulumi.Input<string>;
    /**
     * Timestamp when the cache instance was deployed.
     */
    deployedAt?: pulumi.Input<string>;
    /**
     * Connection endpoint for the cache instance.
     */
    endpoint?: pulumi.Input<string>;
    /**
     * Memory size in MB. If not specified, determined by resource_profile.
     */
    memorySizeMb?: pulumi.Input<number>;
    /**
     * Monthly cost in dollars.
     */
    monthlyCost?: pulumi.Input<number>;
    /**
     * Monthly cost in cents.
     */
    monthlyCostCents?: pulumi.Input<number>;
    /**
     * Name of the cache instance.
     */
    name?: pulumi.Input<string>;
    /**
     * ID of the parameter group to use for custom configuration.
     */
    parameterGroupId?: pulumi.Input<string>;
    /**
     * Port number for the cache instance.
     */
    port?: pulumi.Input<number>;
    /**
     * Resource profile for the cache (micro, small, medium, large).
     */
    resourceProfile?: pulumi.Input<string>;
    /**
     * Current status of the cache instance (pending, provisioning, running, stopped, error).
     */
    status?: pulumi.Input<string>;
    timeouts?: pulumi.Input<inputs.CacheTimeouts>;
    /**
     * Timestamp when the cache instance was last updated.
     */
    updatedAt?: pulumi.Input<string>;
    /**
     * Version of the cache software.
     */
    version?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Cache resource.
 */
export interface CacheArgs {
    /**
     * Cache provider type (redis, valkey, dragonfly).
     */
    cacheProvider: pulumi.Input<string>;
    /**
     * Number of CPU cores. If not specified, determined by resource_profile.
     */
    cpuCores?: pulumi.Input<number>;
    /**
     * Datacenter location (ash, fsn1, nbg1, hel1).
     */
    datacenter: pulumi.Input<string>;
    /**
     * Memory size in MB. If not specified, determined by resource_profile.
     */
    memorySizeMb?: pulumi.Input<number>;
    /**
     * Name of the cache instance.
     */
    name?: pulumi.Input<string>;
    /**
     * ID of the parameter group to use for custom configuration.
     */
    parameterGroupId?: pulumi.Input<string>;
    /**
     * Resource profile for the cache (micro, small, medium, large).
     */
    resourceProfile: pulumi.Input<string>;
    timeouts?: pulumi.Input<inputs.CacheTimeouts>;
    /**
     * Version of the cache software.
     */
    version?: pulumi.Input<string>;
}
