// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * ## # danubedata.Database
 *
 * Manages a managed database instance (MySQL, PostgreSQL, or MariaDB).
 *
 * ## Example Usage
 *
 * ### Using Resource Profile
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as danubedata from "@danubedata/pulumi";
 *
 * const standard = new danubedata.Database("standard", {
 *     datacenter: "fsn1",
 *     engine: "mysql",
 *     resourceProfile: "db-medium",
 * });
 * ```
 *
 * ## Notes
 *
 * - Database credentials are managed separately and can be retrieved via the API.
 * - Storage size can only be increased, not decreased.
 * - Version upgrades may cause brief downtime.
 *
 * ## Import
 *
 * Database instances can be imported using their ID:
 *
 * bash
 *
 * ```sh
 * $ pulumi import danubedata:index/database:Database example db-abc123
 * ```
 */
export class Database extends pulumi.CustomResource {
    /**
     * Get an existing Database resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: DatabaseState, opts?: pulumi.CustomResourceOptions): Database {
        return new Database(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'danubedata:index/database:Database';

    /**
     * Returns true if the given object is an instance of Database.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Database {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Database.__pulumiType;
    }

    /**
     * Number of CPU cores. Derived from resource_profile.
     */
    public /*out*/ readonly cpuCores!: pulumi.Output<number>;
    /**
     * Creation timestamp.
     */
    public /*out*/ readonly createdAt!: pulumi.Output<string>;
    /**
     * Name of the initial database to create. Must start with a letter and contain only letters, numbers, and underscores.
     */
    public readonly databaseName!: pulumi.Output<string | undefined>;
    /**
     * Datacenter location (fsn1, nbg1, hel1).
     */
    public readonly datacenter!: pulumi.Output<string>;
    /**
     * Deployment timestamp.
     */
    public /*out*/ readonly deployedAt!: pulumi.Output<string>;
    /**
     * Connection endpoint hostname.
     */
    public /*out*/ readonly endpoint!: pulumi.Output<string>;
    /**
     * Database engine (mysql, postgresql, mariadb).
     */
    public readonly engine!: pulumi.Output<string>;
    /**
     * Memory size in MB. Derived from resource_profile.
     */
    public /*out*/ readonly memorySizeMb!: pulumi.Output<number>;
    /**
     * Estimated monthly cost.
     */
    public /*out*/ readonly monthlyCost!: pulumi.Output<number>;
    /**
     * Monthly cost in cents.
     */
    public /*out*/ readonly monthlyCostCents!: pulumi.Output<number>;
    /**
     * Name of the database instance. Must be lowercase alphanumeric with hyphens (DNS compatible).
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * ID of the parameter group to use for custom configuration.
     */
    public readonly parameterGroupId!: pulumi.Output<string | undefined>;
    /**
     * Connection port.
     */
    public /*out*/ readonly port!: pulumi.Output<number>;
    /**
     * Resource profile for the database (small, medium, large).
     */
    public readonly resourceProfile!: pulumi.Output<string>;
    /**
     * Current status.
     */
    public /*out*/ readonly status!: pulumi.Output<string>;
    /**
     * Storage size in GB. Derived from resource_profile.
     */
    public /*out*/ readonly storageSizeGb!: pulumi.Output<number>;
    public readonly timeouts!: pulumi.Output<outputs.DatabaseTimeouts | undefined>;
    /**
     * Timestamp when the database instance was last updated.
     */
    public /*out*/ readonly updatedAt!: pulumi.Output<string>;
    /**
     * Database admin username.
     */
    public /*out*/ readonly username!: pulumi.Output<string>;
    /**
     * Version of the database software.
     */
    public readonly version!: pulumi.Output<string>;

    /**
     * Create a Database resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: DatabaseArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: DatabaseArgs | DatabaseState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as DatabaseState | undefined;
            resourceInputs["cpuCores"] = state ? state.cpuCores : undefined;
            resourceInputs["createdAt"] = state ? state.createdAt : undefined;
            resourceInputs["databaseName"] = state ? state.databaseName : undefined;
            resourceInputs["datacenter"] = state ? state.datacenter : undefined;
            resourceInputs["deployedAt"] = state ? state.deployedAt : undefined;
            resourceInputs["endpoint"] = state ? state.endpoint : undefined;
            resourceInputs["engine"] = state ? state.engine : undefined;
            resourceInputs["memorySizeMb"] = state ? state.memorySizeMb : undefined;
            resourceInputs["monthlyCost"] = state ? state.monthlyCost : undefined;
            resourceInputs["monthlyCostCents"] = state ? state.monthlyCostCents : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["parameterGroupId"] = state ? state.parameterGroupId : undefined;
            resourceInputs["port"] = state ? state.port : undefined;
            resourceInputs["resourceProfile"] = state ? state.resourceProfile : undefined;
            resourceInputs["status"] = state ? state.status : undefined;
            resourceInputs["storageSizeGb"] = state ? state.storageSizeGb : undefined;
            resourceInputs["timeouts"] = state ? state.timeouts : undefined;
            resourceInputs["updatedAt"] = state ? state.updatedAt : undefined;
            resourceInputs["username"] = state ? state.username : undefined;
            resourceInputs["version"] = state ? state.version : undefined;
        } else {
            const args = argsOrState as DatabaseArgs | undefined;
            if ((!args || args.datacenter === undefined) && !opts.urn) {
                throw new Error("Missing required property 'datacenter'");
            }
            if ((!args || args.engine === undefined) && !opts.urn) {
                throw new Error("Missing required property 'engine'");
            }
            if ((!args || args.resourceProfile === undefined) && !opts.urn) {
                throw new Error("Missing required property 'resourceProfile'");
            }
            resourceInputs["databaseName"] = args ? args.databaseName : undefined;
            resourceInputs["datacenter"] = args ? args.datacenter : undefined;
            resourceInputs["engine"] = args ? args.engine : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["parameterGroupId"] = args ? args.parameterGroupId : undefined;
            resourceInputs["resourceProfile"] = args ? args.resourceProfile : undefined;
            resourceInputs["timeouts"] = args ? args.timeouts : undefined;
            resourceInputs["version"] = args ? args.version : undefined;
            resourceInputs["cpuCores"] = undefined /*out*/;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["deployedAt"] = undefined /*out*/;
            resourceInputs["endpoint"] = undefined /*out*/;
            resourceInputs["memorySizeMb"] = undefined /*out*/;
            resourceInputs["monthlyCost"] = undefined /*out*/;
            resourceInputs["monthlyCostCents"] = undefined /*out*/;
            resourceInputs["port"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
            resourceInputs["storageSizeGb"] = undefined /*out*/;
            resourceInputs["updatedAt"] = undefined /*out*/;
            resourceInputs["username"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Database.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Database resources.
 */
export interface DatabaseState {
    /**
     * Number of CPU cores. Derived from resource_profile.
     */
    cpuCores?: pulumi.Input<number>;
    /**
     * Creation timestamp.
     */
    createdAt?: pulumi.Input<string>;
    /**
     * Name of the initial database to create. Must start with a letter and contain only letters, numbers, and underscores.
     */
    databaseName?: pulumi.Input<string>;
    /**
     * Datacenter location (fsn1, nbg1, hel1).
     */
    datacenter?: pulumi.Input<string>;
    /**
     * Deployment timestamp.
     */
    deployedAt?: pulumi.Input<string>;
    /**
     * Connection endpoint hostname.
     */
    endpoint?: pulumi.Input<string>;
    /**
     * Database engine (mysql, postgresql, mariadb).
     */
    engine?: pulumi.Input<string>;
    /**
     * Memory size in MB. Derived from resource_profile.
     */
    memorySizeMb?: pulumi.Input<number>;
    /**
     * Estimated monthly cost.
     */
    monthlyCost?: pulumi.Input<number>;
    /**
     * Monthly cost in cents.
     */
    monthlyCostCents?: pulumi.Input<number>;
    /**
     * Name of the database instance. Must be lowercase alphanumeric with hyphens (DNS compatible).
     */
    name?: pulumi.Input<string>;
    /**
     * ID of the parameter group to use for custom configuration.
     */
    parameterGroupId?: pulumi.Input<string>;
    /**
     * Connection port.
     */
    port?: pulumi.Input<number>;
    /**
     * Resource profile for the database (small, medium, large).
     */
    resourceProfile?: pulumi.Input<string>;
    /**
     * Current status.
     */
    status?: pulumi.Input<string>;
    /**
     * Storage size in GB. Derived from resource_profile.
     */
    storageSizeGb?: pulumi.Input<number>;
    timeouts?: pulumi.Input<inputs.DatabaseTimeouts>;
    /**
     * Timestamp when the database instance was last updated.
     */
    updatedAt?: pulumi.Input<string>;
    /**
     * Database admin username.
     */
    username?: pulumi.Input<string>;
    /**
     * Version of the database software.
     */
    version?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Database resource.
 */
export interface DatabaseArgs {
    /**
     * Name of the initial database to create. Must start with a letter and contain only letters, numbers, and underscores.
     */
    databaseName?: pulumi.Input<string>;
    /**
     * Datacenter location (fsn1, nbg1, hel1).
     */
    datacenter: pulumi.Input<string>;
    /**
     * Database engine (mysql, postgresql, mariadb).
     */
    engine: pulumi.Input<string>;
    /**
     * Name of the database instance. Must be lowercase alphanumeric with hyphens (DNS compatible).
     */
    name?: pulumi.Input<string>;
    /**
     * ID of the parameter group to use for custom configuration.
     */
    parameterGroupId?: pulumi.Input<string>;
    /**
     * Resource profile for the database (small, medium, large).
     */
    resourceProfile: pulumi.Input<string>;
    timeouts?: pulumi.Input<inputs.DatabaseTimeouts>;
    /**
     * Version of the database software.
     */
    version?: pulumi.Input<string>;
}
