// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * ## # danubedata.Firewall
 *
 * Manages a firewall with rules for network traffic control.
 *
 * ## Example Usage
 *
 * ## Import
 *
 * Firewalls can be imported using their ID:
 *
 * bash
 *
 * ```sh
 * $ pulumi import danubedata:index/firewall:Firewall example fw-abc123
 * ```
 */
export class Firewall extends pulumi.CustomResource {
    /**
     * Get an existing Firewall resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: FirewallState, opts?: pulumi.CustomResourceOptions): Firewall {
        return new Firewall(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'danubedata:index/firewall:Firewall';

    /**
     * Returns true if the given object is an instance of Firewall.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Firewall {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Firewall.__pulumiType;
    }

    /**
     * Creation timestamp.
     */
    public /*out*/ readonly createdAt!: pulumi.Output<string>;
    /**
     * Default action for traffic not matching any rule: 'drop' or 'accept'.
     */
    public readonly defaultAction!: pulumi.Output<string>;
    /**
     * Description of the firewall.
     */
    public readonly description!: pulumi.Output<string | undefined>;
    /**
     * Whether this is the default firewall for the team.
     */
    public readonly isDefault!: pulumi.Output<boolean>;
    /**
     * Name of the firewall.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * List of firewall rules.
     */
    public readonly rules!: pulumi.Output<outputs.FirewallRule[] | undefined>;
    /**
     * Current status of the firewall.
     */
    public /*out*/ readonly status!: pulumi.Output<string>;
    /**
     * Timestamp when the firewall was last updated.
     */
    public /*out*/ readonly updatedAt!: pulumi.Output<string>;

    /**
     * Create a Firewall resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: FirewallArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: FirewallArgs | FirewallState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as FirewallState | undefined;
            resourceInputs["createdAt"] = state ? state.createdAt : undefined;
            resourceInputs["defaultAction"] = state ? state.defaultAction : undefined;
            resourceInputs["description"] = state ? state.description : undefined;
            resourceInputs["isDefault"] = state ? state.isDefault : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["rules"] = state ? state.rules : undefined;
            resourceInputs["status"] = state ? state.status : undefined;
            resourceInputs["updatedAt"] = state ? state.updatedAt : undefined;
        } else {
            const args = argsOrState as FirewallArgs | undefined;
            resourceInputs["defaultAction"] = args ? args.defaultAction : undefined;
            resourceInputs["description"] = args ? args.description : undefined;
            resourceInputs["isDefault"] = args ? args.isDefault : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["rules"] = args ? args.rules : undefined;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
            resourceInputs["updatedAt"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Firewall.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Firewall resources.
 */
export interface FirewallState {
    /**
     * Creation timestamp.
     */
    createdAt?: pulumi.Input<string>;
    /**
     * Default action for traffic not matching any rule: 'drop' or 'accept'.
     */
    defaultAction?: pulumi.Input<string>;
    /**
     * Description of the firewall.
     */
    description?: pulumi.Input<string>;
    /**
     * Whether this is the default firewall for the team.
     */
    isDefault?: pulumi.Input<boolean>;
    /**
     * Name of the firewall.
     */
    name?: pulumi.Input<string>;
    /**
     * List of firewall rules.
     */
    rules?: pulumi.Input<pulumi.Input<inputs.FirewallRule>[]>;
    /**
     * Current status of the firewall.
     */
    status?: pulumi.Input<string>;
    /**
     * Timestamp when the firewall was last updated.
     */
    updatedAt?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Firewall resource.
 */
export interface FirewallArgs {
    /**
     * Default action for traffic not matching any rule: 'drop' or 'accept'.
     */
    defaultAction?: pulumi.Input<string>;
    /**
     * Description of the firewall.
     */
    description?: pulumi.Input<string>;
    /**
     * Whether this is the default firewall for the team.
     */
    isDefault?: pulumi.Input<boolean>;
    /**
     * Name of the firewall.
     */
    name?: pulumi.Input<string>;
    /**
     * List of firewall rules.
     */
    rules?: pulumi.Input<pulumi.Input<inputs.FirewallRule>[]>;
}
