// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getCacheProviders(opts?: pulumi.InvokeOptions): Promise<GetCacheProvidersResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("danubedata:index/getCacheProviders:getCacheProviders", {
    }, opts);
}

/**
 * A collection of values returned by getCacheProviders.
 */
export interface GetCacheProvidersResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly providers: outputs.GetCacheProvidersProvider[];
}
export function getCacheProvidersOutput(opts?: pulumi.InvokeOptions): pulumi.Output<GetCacheProvidersResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("danubedata:index/getCacheProviders:getCacheProviders", {
    }, opts);
}
