// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * ## # danubedata.getDatabaseProviders
 *
 * Lists available database providers (MySQL, PostgreSQL, MariaDB).
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as danubedata from "@pulumi/danubedata";
 *
 * const all = danubedata.getDatabaseProviders({});
 * export const databaseProviders = all.then(all => .map(p => ({
 *     id: p.id,
 *     name: p.name,
 * })));
 * ```
 */
export function getDatabaseProviders(opts?: pulumi.InvokeOptions): Promise<GetDatabaseProvidersResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("danubedata:index/getDatabaseProviders:getDatabaseProviders", {
    }, opts);
}

/**
 * A collection of values returned by getDatabaseProviders.
 */
export interface GetDatabaseProvidersResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * List of database providers. Each provider contains:
     */
    readonly providers: outputs.GetDatabaseProvidersProvider[];
}
/**
 * ## # danubedata.getDatabaseProviders
 *
 * Lists available database providers (MySQL, PostgreSQL, MariaDB).
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as danubedata from "@pulumi/danubedata";
 *
 * const all = danubedata.getDatabaseProviders({});
 * export const databaseProviders = all.then(all => .map(p => ({
 *     id: p.id,
 *     name: p.name,
 * })));
 * ```
 */
export function getDatabaseProvidersOutput(opts?: pulumi.InvokeOptions): pulumi.Output<GetDatabaseProvidersResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("danubedata:index/getDatabaseProviders:getDatabaseProviders", {
    }, opts);
}
