// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getFirewalls(opts?: pulumi.InvokeOptions): Promise<GetFirewallsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("danubedata:index/getFirewalls:getFirewalls", {
    }, opts);
}

/**
 * A collection of values returned by getFirewalls.
 */
export interface GetFirewallsResult {
    readonly firewalls: outputs.GetFirewallsFirewall[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
}
export function getFirewallsOutput(opts?: pulumi.InvokeOptions): pulumi.Output<GetFirewallsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("danubedata:index/getFirewalls:getFirewalls", {
    }, opts);
}
