// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getStorageAccessKeys(opts?: pulumi.InvokeOptions): Promise<GetStorageAccessKeysResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("danubedata:index/getStorageAccessKeys:getStorageAccessKeys", {
    }, opts);
}

/**
 * A collection of values returned by getStorageAccessKeys.
 */
export interface GetStorageAccessKeysResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly keys: outputs.GetStorageAccessKeysKey[];
}
export function getStorageAccessKeysOutput(opts?: pulumi.InvokeOptions): pulumi.Output<GetStorageAccessKeysResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("danubedata:index/getStorageAccessKeys:getStorageAccessKeys", {
    }, opts);
}
