// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getStorageBuckets(opts?: pulumi.InvokeOptions): Promise<GetStorageBucketsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("danubedata:index/getStorageBuckets:getStorageBuckets", {
    }, opts);
}

/**
 * A collection of values returned by getStorageBuckets.
 */
export interface GetStorageBucketsResult {
    readonly buckets: outputs.GetStorageBucketsBucket[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
}
export function getStorageBucketsOutput(opts?: pulumi.InvokeOptions): pulumi.Output<GetStorageBucketsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("danubedata:index/getStorageBuckets:getStorageBuckets", {
    }, opts);
}
