// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getVpsSnapshots(opts?: pulumi.InvokeOptions): Promise<GetVpsSnapshotsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("danubedata:index/getVpsSnapshots:getVpsSnapshots", {
    }, opts);
}

/**
 * A collection of values returned by getVpsSnapshots.
 */
export interface GetVpsSnapshotsResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly snapshots: outputs.GetVpsSnapshotsSnapshot[];
}
export function getVpsSnapshotsOutput(opts?: pulumi.InvokeOptions): pulumi.Output<GetVpsSnapshotsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("danubedata:index/getVpsSnapshots:getVpsSnapshots", {
    }, opts);
}
