// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { CacheArgs, CacheState } from "./cache";
export type Cache = import("./cache").Cache;
export const Cache: typeof import("./cache").Cache = null as any;
utilities.lazyLoad(exports, ["Cache"], () => require("./cache"));

export { DatabaseArgs, DatabaseState } from "./database";
export type Database = import("./database").Database;
export const Database: typeof import("./database").Database = null as any;
utilities.lazyLoad(exports, ["Database"], () => require("./database"));

export { FirewallArgs, FirewallState } from "./firewall";
export type Firewall = import("./firewall").Firewall;
export const Firewall: typeof import("./firewall").Firewall = null as any;
utilities.lazyLoad(exports, ["Firewall"], () => require("./firewall"));

export { GetCacheProvidersResult } from "./getCacheProviders";
export const getCacheProviders: typeof import("./getCacheProviders").getCacheProviders = null as any;
export const getCacheProvidersOutput: typeof import("./getCacheProviders").getCacheProvidersOutput = null as any;
utilities.lazyLoad(exports, ["getCacheProviders","getCacheProvidersOutput"], () => require("./getCacheProviders"));

export { GetCachesResult } from "./getCaches";
export const getCaches: typeof import("./getCaches").getCaches = null as any;
export const getCachesOutput: typeof import("./getCaches").getCachesOutput = null as any;
utilities.lazyLoad(exports, ["getCaches","getCachesOutput"], () => require("./getCaches"));

export { GetDatabaseProvidersResult } from "./getDatabaseProviders";
export const getDatabaseProviders: typeof import("./getDatabaseProviders").getDatabaseProviders = null as any;
export const getDatabaseProvidersOutput: typeof import("./getDatabaseProviders").getDatabaseProvidersOutput = null as any;
utilities.lazyLoad(exports, ["getDatabaseProviders","getDatabaseProvidersOutput"], () => require("./getDatabaseProviders"));

export { GetDatabasesResult } from "./getDatabases";
export const getDatabases: typeof import("./getDatabases").getDatabases = null as any;
export const getDatabasesOutput: typeof import("./getDatabases").getDatabasesOutput = null as any;
utilities.lazyLoad(exports, ["getDatabases","getDatabasesOutput"], () => require("./getDatabases"));

export { GetFirewallsResult } from "./getFirewalls";
export const getFirewalls: typeof import("./getFirewalls").getFirewalls = null as any;
export const getFirewallsOutput: typeof import("./getFirewalls").getFirewallsOutput = null as any;
utilities.lazyLoad(exports, ["getFirewalls","getFirewallsOutput"], () => require("./getFirewalls"));

export { GetServerlessContainersResult } from "./getServerlessContainers";
export const getServerlessContainers: typeof import("./getServerlessContainers").getServerlessContainers = null as any;
export const getServerlessContainersOutput: typeof import("./getServerlessContainers").getServerlessContainersOutput = null as any;
utilities.lazyLoad(exports, ["getServerlessContainers","getServerlessContainersOutput"], () => require("./getServerlessContainers"));

export { GetSshKeysResult } from "./getSshKeys";
export const getSshKeys: typeof import("./getSshKeys").getSshKeys = null as any;
export const getSshKeysOutput: typeof import("./getSshKeys").getSshKeysOutput = null as any;
utilities.lazyLoad(exports, ["getSshKeys","getSshKeysOutput"], () => require("./getSshKeys"));

export { GetStorageAccessKeysResult } from "./getStorageAccessKeys";
export const getStorageAccessKeys: typeof import("./getStorageAccessKeys").getStorageAccessKeys = null as any;
export const getStorageAccessKeysOutput: typeof import("./getStorageAccessKeys").getStorageAccessKeysOutput = null as any;
utilities.lazyLoad(exports, ["getStorageAccessKeys","getStorageAccessKeysOutput"], () => require("./getStorageAccessKeys"));

export { GetStorageBucketsResult } from "./getStorageBuckets";
export const getStorageBuckets: typeof import("./getStorageBuckets").getStorageBuckets = null as any;
export const getStorageBucketsOutput: typeof import("./getStorageBuckets").getStorageBucketsOutput = null as any;
utilities.lazyLoad(exports, ["getStorageBuckets","getStorageBucketsOutput"], () => require("./getStorageBuckets"));

export { GetVpsImagesResult } from "./getVpsImages";
export const getVpsImages: typeof import("./getVpsImages").getVpsImages = null as any;
export const getVpsImagesOutput: typeof import("./getVpsImages").getVpsImagesOutput = null as any;
utilities.lazyLoad(exports, ["getVpsImages","getVpsImagesOutput"], () => require("./getVpsImages"));

export { GetVpsSnapshotsResult } from "./getVpsSnapshots";
export const getVpsSnapshots: typeof import("./getVpsSnapshots").getVpsSnapshots = null as any;
export const getVpsSnapshotsOutput: typeof import("./getVpsSnapshots").getVpsSnapshotsOutput = null as any;
utilities.lazyLoad(exports, ["getVpsSnapshots","getVpsSnapshotsOutput"], () => require("./getVpsSnapshots"));

export { GetVpssResult } from "./getVpss";
export const getVpss: typeof import("./getVpss").getVpss = null as any;
export const getVpssOutput: typeof import("./getVpss").getVpssOutput = null as any;
utilities.lazyLoad(exports, ["getVpss","getVpssOutput"], () => require("./getVpss"));

export { ProviderArgs } from "./provider";
export type Provider = import("./provider").Provider;
export const Provider: typeof import("./provider").Provider = null as any;
utilities.lazyLoad(exports, ["Provider"], () => require("./provider"));

export { ServerlessArgs, ServerlessState } from "./serverless";
export type Serverless = import("./serverless").Serverless;
export const Serverless: typeof import("./serverless").Serverless = null as any;
utilities.lazyLoad(exports, ["Serverless"], () => require("./serverless"));

export { SshKeyArgs, SshKeyState } from "./sshKey";
export type SshKey = import("./sshKey").SshKey;
export const SshKey: typeof import("./sshKey").SshKey = null as any;
utilities.lazyLoad(exports, ["SshKey"], () => require("./sshKey"));

export { StorageAccessKeyArgs, StorageAccessKeyState } from "./storageAccessKey";
export type StorageAccessKey = import("./storageAccessKey").StorageAccessKey;
export const StorageAccessKey: typeof import("./storageAccessKey").StorageAccessKey = null as any;
utilities.lazyLoad(exports, ["StorageAccessKey"], () => require("./storageAccessKey"));

export { StorageBucketArgs, StorageBucketState } from "./storageBucket";
export type StorageBucket = import("./storageBucket").StorageBucket;
export const StorageBucket: typeof import("./storageBucket").StorageBucket = null as any;
utilities.lazyLoad(exports, ["StorageBucket"], () => require("./storageBucket"));

export { VpsArgs, VpsState } from "./vps";
export type Vps = import("./vps").Vps;
export const Vps: typeof import("./vps").Vps = null as any;
utilities.lazyLoad(exports, ["Vps"], () => require("./vps"));

export { VpsSnapshotArgs, VpsSnapshotState } from "./vpsSnapshot";
export type VpsSnapshot = import("./vpsSnapshot").VpsSnapshot;
export const VpsSnapshot: typeof import("./vpsSnapshot").VpsSnapshot = null as any;
utilities.lazyLoad(exports, ["VpsSnapshot"], () => require("./vpsSnapshot"));


// Export sub-modules:
import * as config from "./config";
import * as types from "./types";

export {
    config,
    types,
};

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "danubedata:index/cache:Cache":
                return new Cache(name, <any>undefined, { urn })
            case "danubedata:index/database:Database":
                return new Database(name, <any>undefined, { urn })
            case "danubedata:index/firewall:Firewall":
                return new Firewall(name, <any>undefined, { urn })
            case "danubedata:index/serverless:Serverless":
                return new Serverless(name, <any>undefined, { urn })
            case "danubedata:index/sshKey:SshKey":
                return new SshKey(name, <any>undefined, { urn })
            case "danubedata:index/storageAccessKey:StorageAccessKey":
                return new StorageAccessKey(name, <any>undefined, { urn })
            case "danubedata:index/storageBucket:StorageBucket":
                return new StorageBucket(name, <any>undefined, { urn })
            case "danubedata:index/vps:Vps":
                return new Vps(name, <any>undefined, { urn })
            case "danubedata:index/vpsSnapshot:VpsSnapshot":
                return new VpsSnapshot(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("danubedata", "index/cache", _module)
pulumi.runtime.registerResourceModule("danubedata", "index/database", _module)
pulumi.runtime.registerResourceModule("danubedata", "index/firewall", _module)
pulumi.runtime.registerResourceModule("danubedata", "index/serverless", _module)
pulumi.runtime.registerResourceModule("danubedata", "index/sshKey", _module)
pulumi.runtime.registerResourceModule("danubedata", "index/storageAccessKey", _module)
pulumi.runtime.registerResourceModule("danubedata", "index/storageBucket", _module)
pulumi.runtime.registerResourceModule("danubedata", "index/vps", _module)
pulumi.runtime.registerResourceModule("danubedata", "index/vpsSnapshot", _module)
pulumi.runtime.registerResourcePackage("danubedata", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:danubedata") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
