// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Serverless extends pulumi.CustomResource {
    /**
     * Get an existing Serverless resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ServerlessState, opts?: pulumi.CustomResourceOptions): Serverless {
        return new Serverless(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'danubedata:index/serverless:Serverless';

    /**
     * Returns true if the given object is an instance of Serverless.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Serverless {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Serverless.__pulumiType;
    }

    /**
     * Timestamp when the container was created.
     */
    public /*out*/ readonly createdAt!: pulumi.Output<string>;
    /**
     * Current month's cost in cents.
     */
    public /*out*/ readonly currentMonthCostCents!: pulumi.Output<number>;
    /**
     * Deployment type: 'image' for Docker image, 'git' for Git repository.
     */
    public readonly deploymentType!: pulumi.Output<string>;
    /**
     * Environment variables for the container.
     */
    public readonly environmentVariables!: pulumi.Output<{[key: string]: string} | undefined>;
    /**
     * Git branch to deploy.
     */
    public readonly gitBranch!: pulumi.Output<string>;
    /**
     * Git repository URL (required if deploymentType is 'git').
     */
    public readonly gitRepository!: pulumi.Output<string | undefined>;
    /**
     * Docker image URL (required if deploymentType is 'image').
     */
    public readonly imageUrl!: pulumi.Output<string | undefined>;
    /**
     * Maximum number of instances.
     */
    public readonly maxInstances!: pulumi.Output<number>;
    /**
     * Minimum number of instances (0 for scale-to-zero).
     */
    public readonly minInstances!: pulumi.Output<number>;
    /**
     * Name of the serverless container.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * Port the container listens on.
     */
    public readonly port!: pulumi.Output<number>;
    /**
     * Resource profile for the container (small, medium, large).
     */
    public readonly resourceProfile!: pulumi.Output<string>;
    /**
     * Current status of the serverless container.
     */
    public /*out*/ readonly status!: pulumi.Output<string>;
    public readonly timeouts!: pulumi.Output<outputs.ServerlessTimeouts | undefined>;
    /**
     * Timestamp when the container was last updated.
     */
    public /*out*/ readonly updatedAt!: pulumi.Output<string>;
    /**
     * Public URL of the deployed service.
     */
    public /*out*/ readonly url!: pulumi.Output<string>;

    /**
     * Create a Serverless resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ServerlessArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ServerlessArgs | ServerlessState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ServerlessState | undefined;
            resourceInputs["createdAt"] = state ? state.createdAt : undefined;
            resourceInputs["currentMonthCostCents"] = state ? state.currentMonthCostCents : undefined;
            resourceInputs["deploymentType"] = state ? state.deploymentType : undefined;
            resourceInputs["environmentVariables"] = state ? state.environmentVariables : undefined;
            resourceInputs["gitBranch"] = state ? state.gitBranch : undefined;
            resourceInputs["gitRepository"] = state ? state.gitRepository : undefined;
            resourceInputs["imageUrl"] = state ? state.imageUrl : undefined;
            resourceInputs["maxInstances"] = state ? state.maxInstances : undefined;
            resourceInputs["minInstances"] = state ? state.minInstances : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["port"] = state ? state.port : undefined;
            resourceInputs["resourceProfile"] = state ? state.resourceProfile : undefined;
            resourceInputs["status"] = state ? state.status : undefined;
            resourceInputs["timeouts"] = state ? state.timeouts : undefined;
            resourceInputs["updatedAt"] = state ? state.updatedAt : undefined;
            resourceInputs["url"] = state ? state.url : undefined;
        } else {
            const args = argsOrState as ServerlessArgs | undefined;
            if ((!args || args.deploymentType === undefined) && !opts.urn) {
                throw new Error("Missing required property 'deploymentType'");
            }
            resourceInputs["deploymentType"] = args ? args.deploymentType : undefined;
            resourceInputs["environmentVariables"] = args ? args.environmentVariables : undefined;
            resourceInputs["gitBranch"] = args ? args.gitBranch : undefined;
            resourceInputs["gitRepository"] = args ? args.gitRepository : undefined;
            resourceInputs["imageUrl"] = args ? args.imageUrl : undefined;
            resourceInputs["maxInstances"] = args ? args.maxInstances : undefined;
            resourceInputs["minInstances"] = args ? args.minInstances : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["port"] = args ? args.port : undefined;
            resourceInputs["resourceProfile"] = args ? args.resourceProfile : undefined;
            resourceInputs["timeouts"] = args ? args.timeouts : undefined;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["currentMonthCostCents"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
            resourceInputs["updatedAt"] = undefined /*out*/;
            resourceInputs["url"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Serverless.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Serverless resources.
 */
export interface ServerlessState {
    /**
     * Timestamp when the container was created.
     */
    createdAt?: pulumi.Input<string>;
    /**
     * Current month's cost in cents.
     */
    currentMonthCostCents?: pulumi.Input<number>;
    /**
     * Deployment type: 'image' for Docker image, 'git' for Git repository.
     */
    deploymentType?: pulumi.Input<string>;
    /**
     * Environment variables for the container.
     */
    environmentVariables?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * Git branch to deploy.
     */
    gitBranch?: pulumi.Input<string>;
    /**
     * Git repository URL (required if deploymentType is 'git').
     */
    gitRepository?: pulumi.Input<string>;
    /**
     * Docker image URL (required if deploymentType is 'image').
     */
    imageUrl?: pulumi.Input<string>;
    /**
     * Maximum number of instances.
     */
    maxInstances?: pulumi.Input<number>;
    /**
     * Minimum number of instances (0 for scale-to-zero).
     */
    minInstances?: pulumi.Input<number>;
    /**
     * Name of the serverless container.
     */
    name?: pulumi.Input<string>;
    /**
     * Port the container listens on.
     */
    port?: pulumi.Input<number>;
    /**
     * Resource profile for the container (small, medium, large).
     */
    resourceProfile?: pulumi.Input<string>;
    /**
     * Current status of the serverless container.
     */
    status?: pulumi.Input<string>;
    timeouts?: pulumi.Input<inputs.ServerlessTimeouts>;
    /**
     * Timestamp when the container was last updated.
     */
    updatedAt?: pulumi.Input<string>;
    /**
     * Public URL of the deployed service.
     */
    url?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Serverless resource.
 */
export interface ServerlessArgs {
    /**
     * Deployment type: 'image' for Docker image, 'git' for Git repository.
     */
    deploymentType: pulumi.Input<string>;
    /**
     * Environment variables for the container.
     */
    environmentVariables?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * Git branch to deploy.
     */
    gitBranch?: pulumi.Input<string>;
    /**
     * Git repository URL (required if deploymentType is 'git').
     */
    gitRepository?: pulumi.Input<string>;
    /**
     * Docker image URL (required if deploymentType is 'image').
     */
    imageUrl?: pulumi.Input<string>;
    /**
     * Maximum number of instances.
     */
    maxInstances?: pulumi.Input<number>;
    /**
     * Minimum number of instances (0 for scale-to-zero).
     */
    minInstances?: pulumi.Input<number>;
    /**
     * Name of the serverless container.
     */
    name?: pulumi.Input<string>;
    /**
     * Port the container listens on.
     */
    port?: pulumi.Input<number>;
    /**
     * Resource profile for the container (small, medium, large).
     */
    resourceProfile?: pulumi.Input<string>;
    timeouts?: pulumi.Input<inputs.ServerlessTimeouts>;
}
