// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * ## # danubedata.SshKey
 *
 * Manages an SSH key for VPS authentication.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as danubedata from "@danubedata/pulumi";
 * import * as fs from "fs";
 *
 * const main = new danubedata.SshKey("main", {publicKey: fs.readFileSync("~/.ssh/id_ed25519.pub", "utf8")});
 * ```
 *
 * ### Using with VPS
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as danubedata from "@danubedata/pulumi";
 *
 * const deploy = new danubedata.SshKey("deploy", {publicKey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAA... deploy@example.com"});
 * const server = new danubedata.Vps("server", {
 *     image: "ubuntu-22.04",
 *     datacenter: "fsn1",
 *     authMethod: "ssh_key",
 *     sshKeyId: deploy.id,
 * });
 * ```
 *
 * ## Import
 *
 * SSH keys can be imported using their ID:
 *
 * bash
 *
 * ```sh
 * $ pulumi import danubedata:index/sshKey:SshKey example key-abc123
 * ```
 */
export class SshKey extends pulumi.CustomResource {
    /**
     * Get an existing SshKey resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SshKeyState, opts?: pulumi.CustomResourceOptions): SshKey {
        return new SshKey(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'danubedata:index/sshKey:SshKey';

    /**
     * Returns true if the given object is an instance of SshKey.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SshKey {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SshKey.__pulumiType;
    }

    /**
     * Creation timestamp.
     */
    public /*out*/ readonly createdAt!: pulumi.Output<string>;
    /**
     * The SSH key fingerprint.
     */
    public /*out*/ readonly fingerprint!: pulumi.Output<string>;
    /**
     * A descriptive name for the SSH key.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * The SSH public key in OpenSSH format (e.g., 'ssh-rsa AAAA...' or 'ssh-ed25519 AAAA...').
     */
    public readonly publicKey!: pulumi.Output<string>;
    /**
     * Timestamp when the SSH key was last updated.
     */
    public /*out*/ readonly updatedAt!: pulumi.Output<string>;

    /**
     * Create a SshKey resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SshKeyArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SshKeyArgs | SshKeyState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SshKeyState | undefined;
            resourceInputs["createdAt"] = state ? state.createdAt : undefined;
            resourceInputs["fingerprint"] = state ? state.fingerprint : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["publicKey"] = state ? state.publicKey : undefined;
            resourceInputs["updatedAt"] = state ? state.updatedAt : undefined;
        } else {
            const args = argsOrState as SshKeyArgs | undefined;
            if ((!args || args.publicKey === undefined) && !opts.urn) {
                throw new Error("Missing required property 'publicKey'");
            }
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["publicKey"] = args ? args.publicKey : undefined;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["fingerprint"] = undefined /*out*/;
            resourceInputs["updatedAt"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(SshKey.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering SshKey resources.
 */
export interface SshKeyState {
    /**
     * Creation timestamp.
     */
    createdAt?: pulumi.Input<string>;
    /**
     * The SSH key fingerprint.
     */
    fingerprint?: pulumi.Input<string>;
    /**
     * A descriptive name for the SSH key.
     */
    name?: pulumi.Input<string>;
    /**
     * The SSH public key in OpenSSH format (e.g., 'ssh-rsa AAAA...' or 'ssh-ed25519 AAAA...').
     */
    publicKey?: pulumi.Input<string>;
    /**
     * Timestamp when the SSH key was last updated.
     */
    updatedAt?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a SshKey resource.
 */
export interface SshKeyArgs {
    /**
     * A descriptive name for the SSH key.
     */
    name?: pulumi.Input<string>;
    /**
     * The SSH public key in OpenSSH format (e.g., 'ssh-rsa AAAA...' or 'ssh-ed25519 AAAA...').
     */
    publicKey: pulumi.Input<string>;
}
