// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class StorageBucket extends pulumi.CustomResource {
    /**
     * Get an existing StorageBucket resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: StorageBucketState, opts?: pulumi.CustomResourceOptions): StorageBucket {
        return new StorageBucket(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'danubedata:index/storageBucket:StorageBucket';

    /**
     * Returns true if the given object is an instance of StorageBucket.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is StorageBucket {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === StorageBucket.__pulumiType;
    }

    /**
     * Timestamp when the bucket was created.
     */
    public /*out*/ readonly createdAt!: pulumi.Output<string>;
    /**
     * Human-readable display name for the bucket.
     */
    public readonly displayName!: pulumi.Output<string | undefined>;
    /**
     * Whether server-side encryption is enabled.
     */
    public readonly encryptionEnabled!: pulumi.Output<boolean>;
    /**
     * Encryption type (none, sse-s3, sse-kms).
     */
    public readonly encryptionType!: pulumi.Output<string>;
    /**
     * S3 endpoint URL for accessing the bucket.
     */
    public /*out*/ readonly endpointUrl!: pulumi.Output<string>;
    /**
     * Internal MinIO bucket name (includes team prefix).
     */
    public /*out*/ readonly minioBucketName!: pulumi.Output<string>;
    /**
     * Monthly cost in dollars.
     */
    public /*out*/ readonly monthlyCost!: pulumi.Output<number>;
    /**
     * Monthly cost in cents.
     */
    public /*out*/ readonly monthlyCostCents!: pulumi.Output<number>;
    /**
     * Name of the storage bucket. Must follow S3 bucket naming rules (3-63 chars, lowercase alphanumeric with hyphens).
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * Number of objects in the bucket.
     */
    public /*out*/ readonly objectCount!: pulumi.Output<number>;
    /**
     * Whether the bucket has public read access enabled.
     */
    public readonly publicAccess!: pulumi.Output<boolean>;
    /**
     * Region for the storage bucket (fsn1).
     */
    public readonly region!: pulumi.Output<string>;
    /**
     * Current size of the bucket in bytes.
     */
    public /*out*/ readonly sizeBytes!: pulumi.Output<number>;
    /**
     * Current status of the storage bucket (pending, active, error, destroying).
     */
    public /*out*/ readonly status!: pulumi.Output<string>;
    public readonly timeouts!: pulumi.Output<outputs.StorageBucketTimeouts | undefined>;
    /**
     * Timestamp when the bucket was last updated.
     */
    public /*out*/ readonly updatedAt!: pulumi.Output<string>;
    /**
     * Whether object versioning is enabled.
     */
    public readonly versioningEnabled!: pulumi.Output<boolean>;

    /**
     * Create a StorageBucket resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: StorageBucketArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: StorageBucketArgs | StorageBucketState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as StorageBucketState | undefined;
            resourceInputs["createdAt"] = state ? state.createdAt : undefined;
            resourceInputs["displayName"] = state ? state.displayName : undefined;
            resourceInputs["encryptionEnabled"] = state ? state.encryptionEnabled : undefined;
            resourceInputs["encryptionType"] = state ? state.encryptionType : undefined;
            resourceInputs["endpointUrl"] = state ? state.endpointUrl : undefined;
            resourceInputs["minioBucketName"] = state ? state.minioBucketName : undefined;
            resourceInputs["monthlyCost"] = state ? state.monthlyCost : undefined;
            resourceInputs["monthlyCostCents"] = state ? state.monthlyCostCents : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["objectCount"] = state ? state.objectCount : undefined;
            resourceInputs["publicAccess"] = state ? state.publicAccess : undefined;
            resourceInputs["region"] = state ? state.region : undefined;
            resourceInputs["sizeBytes"] = state ? state.sizeBytes : undefined;
            resourceInputs["status"] = state ? state.status : undefined;
            resourceInputs["timeouts"] = state ? state.timeouts : undefined;
            resourceInputs["updatedAt"] = state ? state.updatedAt : undefined;
            resourceInputs["versioningEnabled"] = state ? state.versioningEnabled : undefined;
        } else {
            const args = argsOrState as StorageBucketArgs | undefined;
            if ((!args || args.region === undefined) && !opts.urn) {
                throw new Error("Missing required property 'region'");
            }
            resourceInputs["displayName"] = args ? args.displayName : undefined;
            resourceInputs["encryptionEnabled"] = args ? args.encryptionEnabled : undefined;
            resourceInputs["encryptionType"] = args ? args.encryptionType : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["publicAccess"] = args ? args.publicAccess : undefined;
            resourceInputs["region"] = args ? args.region : undefined;
            resourceInputs["timeouts"] = args ? args.timeouts : undefined;
            resourceInputs["versioningEnabled"] = args ? args.versioningEnabled : undefined;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["endpointUrl"] = undefined /*out*/;
            resourceInputs["minioBucketName"] = undefined /*out*/;
            resourceInputs["monthlyCost"] = undefined /*out*/;
            resourceInputs["monthlyCostCents"] = undefined /*out*/;
            resourceInputs["objectCount"] = undefined /*out*/;
            resourceInputs["sizeBytes"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
            resourceInputs["updatedAt"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(StorageBucket.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering StorageBucket resources.
 */
export interface StorageBucketState {
    /**
     * Timestamp when the bucket was created.
     */
    createdAt?: pulumi.Input<string>;
    /**
     * Human-readable display name for the bucket.
     */
    displayName?: pulumi.Input<string>;
    /**
     * Whether server-side encryption is enabled.
     */
    encryptionEnabled?: pulumi.Input<boolean>;
    /**
     * Encryption type (none, sse-s3, sse-kms).
     */
    encryptionType?: pulumi.Input<string>;
    /**
     * S3 endpoint URL for accessing the bucket.
     */
    endpointUrl?: pulumi.Input<string>;
    /**
     * Internal MinIO bucket name (includes team prefix).
     */
    minioBucketName?: pulumi.Input<string>;
    /**
     * Monthly cost in dollars.
     */
    monthlyCost?: pulumi.Input<number>;
    /**
     * Monthly cost in cents.
     */
    monthlyCostCents?: pulumi.Input<number>;
    /**
     * Name of the storage bucket. Must follow S3 bucket naming rules (3-63 chars, lowercase alphanumeric with hyphens).
     */
    name?: pulumi.Input<string>;
    /**
     * Number of objects in the bucket.
     */
    objectCount?: pulumi.Input<number>;
    /**
     * Whether the bucket has public read access enabled.
     */
    publicAccess?: pulumi.Input<boolean>;
    /**
     * Region for the storage bucket (fsn1).
     */
    region?: pulumi.Input<string>;
    /**
     * Current size of the bucket in bytes.
     */
    sizeBytes?: pulumi.Input<number>;
    /**
     * Current status of the storage bucket (pending, active, error, destroying).
     */
    status?: pulumi.Input<string>;
    timeouts?: pulumi.Input<inputs.StorageBucketTimeouts>;
    /**
     * Timestamp when the bucket was last updated.
     */
    updatedAt?: pulumi.Input<string>;
    /**
     * Whether object versioning is enabled.
     */
    versioningEnabled?: pulumi.Input<boolean>;
}

/**
 * The set of arguments for constructing a StorageBucket resource.
 */
export interface StorageBucketArgs {
    /**
     * Human-readable display name for the bucket.
     */
    displayName?: pulumi.Input<string>;
    /**
     * Whether server-side encryption is enabled.
     */
    encryptionEnabled?: pulumi.Input<boolean>;
    /**
     * Encryption type (none, sse-s3, sse-kms).
     */
    encryptionType?: pulumi.Input<string>;
    /**
     * Name of the storage bucket. Must follow S3 bucket naming rules (3-63 chars, lowercase alphanumeric with hyphens).
     */
    name?: pulumi.Input<string>;
    /**
     * Whether the bucket has public read access enabled.
     */
    publicAccess?: pulumi.Input<boolean>;
    /**
     * Region for the storage bucket (fsn1).
     */
    region: pulumi.Input<string>;
    timeouts?: pulumi.Input<inputs.StorageBucketTimeouts>;
    /**
     * Whether object versioning is enabled.
     */
    versioningEnabled?: pulumi.Input<boolean>;
}
