// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * ## # danubedata.VpsSnapshot
 *
 * Manages a VPS snapshot for backup and recovery.
 *
 * ## Example Usage
 *
 * ### Basic Snapshot
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as danubedata from "@danubedata/pulumi";
 *
 * const server = new danubedata.Vps("server", {
 *     image: "ubuntu-22.04",
 *     datacenter: "fsn1",
 *     authMethod: "ssh_key",
 *     sshKeyId: danubedata_ssh_key.main.id,
 * });
 * const backup = new danubedata.VpsSnapshot("backup", {vpsInstanceId: server.id});
 * ```
 *
 * ### Snapshot with Description
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as danubedata from "@danubedata/pulumi";
 *
 * const release = new danubedata.VpsSnapshot("release", {
 *     description: "Snapshot before v1.0 release deployment",
 *     vpsInstanceId: danubedata_vps.server.id,
 * });
 * ```
 *
 * ## Import
 *
 * VPS snapshots can be imported using their ID:
 *
 * bash
 *
 * ```sh
 * $ pulumi import danubedata:index/vpsSnapshot:VpsSnapshot example snap-abc123
 * ```
 */
export class VpsSnapshot extends pulumi.CustomResource {
    /**
     * Get an existing VpsSnapshot resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: VpsSnapshotState, opts?: pulumi.CustomResourceOptions): VpsSnapshot {
        return new VpsSnapshot(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'danubedata:index/vpsSnapshot:VpsSnapshot';

    /**
     * Returns true if the given object is an instance of VpsSnapshot.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is VpsSnapshot {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === VpsSnapshot.__pulumiType;
    }

    /**
     * Creation timestamp.
     */
    public /*out*/ readonly createdAt!: pulumi.Output<string>;
    /**
     * Description of the snapshot.
     */
    public readonly description!: pulumi.Output<string | undefined>;
    /**
     * Name of the snapshot.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * Size of the snapshot in GB.
     */
    public /*out*/ readonly sizeGb!: pulumi.Output<number>;
    /**
     * Current status (`creating`, `ready`, `error`).
     */
    public /*out*/ readonly status!: pulumi.Output<string>;
    public readonly timeouts!: pulumi.Output<outputs.VpsSnapshotTimeouts | undefined>;
    /**
     * Timestamp when the snapshot was last updated.
     */
    public /*out*/ readonly updatedAt!: pulumi.Output<string>;
    /**
     * ID of the VPS instance to snapshot.
     */
    public readonly vpsInstanceId!: pulumi.Output<string>;

    /**
     * Create a VpsSnapshot resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: VpsSnapshotArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: VpsSnapshotArgs | VpsSnapshotState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as VpsSnapshotState | undefined;
            resourceInputs["createdAt"] = state ? state.createdAt : undefined;
            resourceInputs["description"] = state ? state.description : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["sizeGb"] = state ? state.sizeGb : undefined;
            resourceInputs["status"] = state ? state.status : undefined;
            resourceInputs["timeouts"] = state ? state.timeouts : undefined;
            resourceInputs["updatedAt"] = state ? state.updatedAt : undefined;
            resourceInputs["vpsInstanceId"] = state ? state.vpsInstanceId : undefined;
        } else {
            const args = argsOrState as VpsSnapshotArgs | undefined;
            if ((!args || args.vpsInstanceId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'vpsInstanceId'");
            }
            resourceInputs["description"] = args ? args.description : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["timeouts"] = args ? args.timeouts : undefined;
            resourceInputs["vpsInstanceId"] = args ? args.vpsInstanceId : undefined;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["sizeGb"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
            resourceInputs["updatedAt"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(VpsSnapshot.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering VpsSnapshot resources.
 */
export interface VpsSnapshotState {
    /**
     * Creation timestamp.
     */
    createdAt?: pulumi.Input<string>;
    /**
     * Description of the snapshot.
     */
    description?: pulumi.Input<string>;
    /**
     * Name of the snapshot.
     */
    name?: pulumi.Input<string>;
    /**
     * Size of the snapshot in GB.
     */
    sizeGb?: pulumi.Input<number>;
    /**
     * Current status (`creating`, `ready`, `error`).
     */
    status?: pulumi.Input<string>;
    timeouts?: pulumi.Input<inputs.VpsSnapshotTimeouts>;
    /**
     * Timestamp when the snapshot was last updated.
     */
    updatedAt?: pulumi.Input<string>;
    /**
     * ID of the VPS instance to snapshot.
     */
    vpsInstanceId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a VpsSnapshot resource.
 */
export interface VpsSnapshotArgs {
    /**
     * Description of the snapshot.
     */
    description?: pulumi.Input<string>;
    /**
     * Name of the snapshot.
     */
    name?: pulumi.Input<string>;
    timeouts?: pulumi.Input<inputs.VpsSnapshotTimeouts>;
    /**
     * ID of the VPS instance to snapshot.
     */
    vpsInstanceId: pulumi.Input<string>;
}
